### ISSUE TITLE
Feature request: Codeblock text size

### ISSUE THREAD

**Issue by FlorianObermayer** [noties/Markwon#100]
Currently `Code text size` controls the text size for `code blocks` as well as for `inline code`. It would be great to have individual control for each individual element.

**Comment by noties** [comment]
Hello @FlorianObermayer !

I agree with you that this configuration option is indeed missing (we already have color and backgroundColor for each). I'm going to add textSize and typeface options in the next `3.0.0` release.
The reason to not include in current `2.x.x` branch is to minimize the difference between the two. After `3.0.0` release a special _legacy_ branch will be created and this feature could be backported.

Meanwhile in current version customization can be achieved via `SpannableFactory`:

```java
final SpannableConfiguration configuration = SpannableConfiguration.builder(context)
        /* your configuration */
        .factory(new SpannableFactoryDef(gifPlaceholder) {
            @Override
            public Object code(@NonNull SpannableTheme theme, boolean multiline) {
                // there is no check if super returns array, beware of this possibility
                if (multiline) {
                    return new Object[]{
                            super.code(theme, true),
                            new AbsoluteSizeSpan(24, true)
                    };
                } else {
                    return new Object[]{
                            super.code(theme, false),
                            new AbsoluteSizeSpan(8, true)
                    };
                }
            }
        })
        .build();
```

**Comment by noties** [comment]
This customization is in latest `3.0.0` release
