### ISSUE TITLE
How to custom the newline height?

### ISSUE THREAD

**Issue by zhuosun-rally** [noties/Markwon#106]
![image](https://user-images.githubusercontent.com/34255817/54649521-cba22980-4a67-11e9-8bbf-2aa2eaa17559.png)

Does Markwon support to custome the newline height? 
for example, we would like change the H tag newline height be 8dp, how to config it? thanks.

**Comment by noties** [comment]
Hello @zhuosun-rally !

It is possible of cause. There is no configurable option out-of-box, but you can control how the new-line character is displayed.

```java
final int dip8 = (int) (context.getResources().getDisplayMetrics().density * 8 + .5F);

final Markwon markwon = Markwon.builder(context)
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configureVisitor(@NonNull MarkwonVisitor.Builder builder) {
                builder.on(Heading.class, new MarkwonVisitor.NodeVisitor<Heading>() {
                    @Override
                    public void visit(@NonNull MarkwonVisitor visitor, @NonNull Heading heading) {
                        // this is how core plugin visits Heading nodes

                        visitor.ensureNewLine();

                        final int length = visitor.length();
                        visitor.visitChildren(heading);

                        CoreProps.HEADING_LEVEL.set(visitor.renderProps(), heading.getLevel());

                        visitor.setSpansForNodeOptional(heading, length);

                        if (visitor.hasNext(heading)) {
                            // save current index
                            final int start = visitor.length();
                            visitor.ensureNewLine();
                            visitor.forceNewLine();
                            // apply AbsoluteSizeSpan to new-line character
                            visitor.setSpans(start, new AbsoluteSizeSpan(dip8));
                        }
                    }
                });
            }
        })
        .build();
```

Please note that this solution uses `AbsoluteSizeSpan` which might result in the line-height not exactly of `8dip`. There is the `LineHeightSpan` interface in Android, but it does not provide implementation, and by looking at [stackoverflow answer](https://stackoverflow.com/a/12925719/6745174) it seems like a bit too much. Anyway, you can try this also

**Comment by zhuosun-rally** [comment]
Thanks @noties, it works for me, 
if you can put them to theme config or somewhere will much convenience, like paragraph space height and heading space height ^^, 
I will close the ticket, thank you.

**Comment by noties** [comment]
@zhuosun-rally I will have to think of how to do this customization. Meanwhile if you have any thoughts, they are welcome
