### ISSUE TITLE
Link not works when TextView android:textIsSelectable = true

### ISSUE THREAD

**Issue by zhuosun-rally** [noties/Markwon#108]
when put this android:textIsSelectable="true" to textview,
then click the Link can not go to browser, it will be no action,
please check it, thanks

**Comment by noties** [comment]
Hello @zhuosun-rally !

* Can you please specify version of Markwon that you are using? 
* Do you set a `MovementMethod` on a TextView?

**Comment by zhuosun-rally** [comment]
Hey @noties , my version is 3.0.0, the below code is my Textview, 
```
<?xml version="1.0" encoding="utf-8"?>
<TextView
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:textIsSelectable="true"
    android:layout_marginBottom="@dimen/margin_2x"
    />
```

I'm trying to make it support selectable, but I found the link click action not works, please check it, thanks.

**Comment by noties** [comment]
Hello @zhuosun-rally !

I can confirm that links are not clickable with `textIsSelectable=true`. Quick search gave me this [answer on stackoverflow](https://stackoverflow.com/a/16003280/6745174). Unfortunately switching to `ArrowKeyMovementMethod` didn't have an effect for me. But using [BetterLinkMovementMethod](https://github.com/saket/Better-Link-Movement-Method) did. 

Beware that I also had to apply movement method after changing `textIsSelectable` attribute as, looking at source code, it has such part:

```java
// mInputType should already be EditorInfo.TYPE_NULL and mInput should be null
setMovementMethod(selectable ? ArrowKeyMovementMethod.getInstance() : null);
```

So, if you apply `textIsSelectable` in your XML, you can manually set MovementMethod after TextView is created (or use `MovementMethodPlugin`), but if you change `textIsSelectable` attribute in code, then you will have to do something like this:

```java
markwon.setParsedMarkdown(textView, markdown);

textView.post(new Runnable() {
    @Override
    public void run() {
        textView.setTextIsSelectable(true);
        textView.setMovementMethod(BetterLinkMovementMethod.getInstance());
    }
});
```
