### ISSUE TITLE
text\ntext not parsed correctly

### ISSUE THREAD

**Issue by fordai** [noties/Markwon#111]
* **Markwon version**: The newest version 3.0.0

In the previous version, \n character can be handled by constructing a SpannableConfiguration and specify softBreakAddsNewLine option; however, there is no such option in version 3.0.0. Could you tell me how to solve this problem? 

I would appreciate it if you could help me out.

**Comment by noties** [comment]
Hey @fordai !

Sure, this can be achieved like this:

```java
final Markwon markwon = Markwon.builder(this)
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configureVisitor(@NonNull MarkwonVisitor.Builder builder) {
                builder.on(SoftLineBreak.class, (visitor, softLineBreak) ->
                        visitor.forceNewLine());
            }
        })
        .build();
```

(taken from [documentation](https://noties.github.io/Markwon/docs/v3/core/core-plugin.html#props) - scroll to the bottom)

**Comment by fordai** [comment]
Got it! Thanks for your help and your great library!

**Comment by noties** [comment]
You are welcome 🙌 !
