### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by Adonai** [noties/Markwon#112]
This project solved a major issue for my html2md rust pet app, and the developer is a nice guy, helped more than once.

So, how do I donate?

**Comment by noties** [comment]
Hello @Adonai !

Yeah, the nice developer is me, thanks :) At one point I decided to set-up a donation processing with idea to resend received funds to something _bigger_, but then I understood that I will be a middleman, unneeded link in a chain. So, let's make it official (and more efficient):

<strong>If you want to show your appreciation to the Markwon library, consider making a donation to the [f-droid](https://f-droid.org)</strong>

Thank you!

**Comment by Adonai** [comment]
Ok, I just did. Thanks!

P.S. Glad you're using F-Droid as well.

**Comment by noties** [comment]
I've added PayPal donation link to the repository. So, if you wish to support Markwon project specifically you are welcome. Still, consider donating to [f-droid](https://f-droid.org/), an open source Android app store, if you are looking for a meaningful to open source and Android in general financial contribution 🙌
