### ISSUE TITLE
How to scale text view with markdown?

### ISSUE THREAD

**Issue by merlin-zaraza** [noties/Markwon#113]
* **Markwon version**: _3.0.0_

Is there a way to scale text view with markdown inside?

**Comment by noties** [comment]
Hello @merlin-zaraza !

I'm not sure what you are asking about, but in general - I think yes, it's possible 😄 

Can you please give me more details how exactly you want to _scale_ textView? Change text size?

**Comment by merlin-zaraza** [comment]
Yes, change text size, but respect formatting. Something like webview doing with zoom in/out.

**Comment by noties** [comment]
Well, Markwon has little to do with it. You should apply your scaling logic to a TextView in which markdown is displayed directly. Here is a link to get your started: [stackoverflow](https://stackoverflow.com/questions/10239891/how-to-zoom-a-textview-in-android)

**Comment by merlin-zaraza** [comment]
Got it. Thanks!
