### ISSUE TITLE
[Question]Customise Header color

### ISSUE THREAD

**Issue by nksaroj** [noties/Markwon#116]
* **Markwon version**: _{3.0.0}_

I am looking to implement a different colour for the headers.
Also, I've seen someone asked this in past with this  https://github.com/noties/Markwon/issues/32.
Looks like SpannableMarkdownVisitor contract has been changed.

I've tried the below code and the issue with the code is the header is not being visible after my change and even it doesn't show the default color.
```
 Markwon.builder(context)
                .usePlugin(object : AbstractMarkwonPlugin() {
                    override fun configureVisitor(builder: MarkwonVisitor.Builder) {
                        builder.on(Heading::class.java) { visitor, heading ->

                            val start = visitor.length()

                            visitor.setSpans(start, ForegroundColorSpan(Color.BLACK))

                            super.configureVisitor(builder)
                        }
                    }
                })
                .build()

```
Could you please let me know how this can be achieved now.

**Comment by noties** [comment]
Hello @nksaroj !

Version `3.0.0` allows customizing spans via factory. So you no longer need to customize visitor. What you are asking can be achieved like this:

```java
.usePlugin(new AbstractMarkwonPlugin() {
    @Override
    public void configureSpansFactory(@NonNull MarkwonSpansFactory.Builder builder) {

        // obtain _origin_ factory to use it with our custom one
        // NB, `requireFactory` is relatively new method that is still in 3.0.1-SNAPSHOT
        // older versions have `getFactory` which returns nullable object
        final SpanFactory origin = builder.requireFactory(Heading.class);

        // register you own
        builder.setFactory(Heading.class, new SpanFactory() {
            @Override
            public Object getSpans(@NonNull MarkwonConfiguration configuration, @NonNull RenderProps props) {

                // here you can also check for heading level for further customizations
                final int level = CoreProps.HEADING_LEVEL.require(props);

                // return an array of spans (origin heading + our color)
                return new Object[]{
                        origin.getSpans(configuration, props),
                        new ForegroundColorSpan(Color.GREEN)
                };
            }
        });
    }
})
```

The snippet that you had shared could've also work, but it needs a few changes:

```java
.usePlugin(new AbstractMarkwonPlugin() {
    @Override
    public void configureVisitor(@NonNull MarkwonVisitor.Builder builder) {
        builder.on(Heading.class, new MarkwonVisitor.NodeVisitor<Heading>() {
            @Override
            public void visit(@NonNull MarkwonVisitor visitor, @NonNull Heading heading) {

                final int start = visitor.length();

                // this is important to visit children
                visitor.visitChildren(heading);

                // if you are passing span logic to a factory we should indicate the heading level
                CoreProps.HEADING_LEVEL.set(visitor.renderProps(), heading.getLevel());
                // let visitor apply spans from specific SpannableFactory
                visitor.setSpansForNode(heading, start);

                // OR, you can set your spans here directly
                visitor.setSpans(start, new ForegroundColorSpan(Color.BLACK));
                // NB, original HeadingSpan is not used here, but this can be changed
                // or you can use your own span for heading
                visitor.setSpans(start, new HeadingSpan(visitor.configuration().theme(), heading.getLevel()));

                // additional new-line after heading
                if (visitor.hasNext(heading)) {
                    visitor.ensureNewLine();
                    visitor.forceNewLine();
                }
            }
        });
    }
})
```

So, it's up to you to pick the solution that works for you. But I had added `SpanFactory` exactly for easier customization of spans that are used (so you don't have to use visitor until you absolutely need to)

**Comment by nksaroj** [comment]
@noties , Thanks for your quick response highly appreciated and like the option #1.
But noticed the few of lines are being rendered instead of two line break below the head line.
Is there any configuration to manage that too?

**Comment by noties** [comment]
Can you please provide more details (like a screenshot)? As I not quite sure I understand

**Comment by nksaroj** [comment]
<img width="289" alt="Screen Shot 2019-04-17 at 3 15 33 pm" src="https://user-images.githubusercontent.com/3455448/56262821-b3373480-6123-11e9-8796-aec0d2c213d7.png">

Please see there is a big gap below the header text "The detail". Also another question, I am wondering how do I adjust the line spacing for both paragraphs and a bulleted list.

**Comment by noties** [comment]
Well, in order to have no empty line between header and paragraph, you will have to go with option no. 2 (the visitor one). Look at these lines:

```java
// additional new-line after heading
if (visitor.hasNext(heading)) {
    visitor.ensureNewLine();
    visitor.forceNewLine();
}
```

As for line height.. You will have better results if you apply line height in your TextView directly. Because everything is a paragraph in commonmark. So, try that first. If it doesn't work for you, you can look into #85 issue there we have a working span for that

**Comment by nksaroj** [comment]
@noties , Thank you for your help so far...
Maybe this is the last question for you as of now. Can we achieve the line breaks with the bullet list .
I've tried https://github.com/noties/Markwon/issues/85 but looks like the contract has been changed.

```
@Override
public Object bulletListItem(@NonNull SpannableTheme theme, int level) {
    return new Object[]{
            super.bulletListItem(theme, level),
            new LastLineSpacingSpan(spacing)
    };
}
```
Not sure where I can put the above snippet of code.

```
 builder.setFactory(BulletList::class.java, object : SpanFactory {
                            override fun getSpans(configuration: MarkwonConfiguration, props: RenderProps): Any {

                                return arrayOf(LastLineSpacingSpan(400))
                            }
                        })
```

I've tried the above code and no luck so far.

Another question: How to adjust the bullet size .Looks like it's considering the font size.

```
//bulletWidth in px
 override fun configureTheme(builder: MarkwonTheme.Builder) {
                        builder.linkColor(Color.BLUE)
                                .headingTypeface(headerFontFace)
                                .headingBreakHeight(0)
                                .bulletListItemStrokeWidth(bulletWidth)
                                .build()
```

bulletListItemStrokeWidth is not working too.

**Comment by noties** [comment]
Hello @nksaroj !

You place it in a custom plugin, of cause 😄 !
```java
.usePlugin(new AbstractMarkwonPlugin() {
    @Override
    public void configureSpansFactory(@NonNull MarkwonSpansFactory.Builder builder) {

        final SpanFactory original = builder.requireFactory(ListItem.class);

        // please note that this factory is used for both bullet and ordered lists
        builder.setFactory(ListItem.class, new SpanFactory() {
            @Override
            public Object getSpans(@NonNull MarkwonConfiguration configuration, @NonNull RenderProps props) {

                // if you would like to detect which type of list it is ->
                final CoreProps.ListItemType type = CoreProps.LIST_ITEM_TYPE.require(props);
                switch (type) {
                    case BULLET:
                        break;
                    case ORDERED:
                        break;
                }

                return new Object[]{
                        original.getSpans(configuration, props),
                        new LastLineSpacingSpan(400)
                };
            }
        });
    }
})
```

BTW, I'm going to add `addFactory` method for easier factories management, it will published with next SNAPSHOT.

Now, bullet size. Well, you cannot easily change it's width. First of all - because a bullet item cannot modify metrics. (So no line height change, no left margin will grow to fit a bigger bullet item). Currently it's width calculated like this:

```
bulletMaximumWidth = Math.min(blockMargin, lineHeight) / 2
if (bulletWidth > bulletMaximumWidth) {
  return bulletMaximumWidth
} else {
  return bulletWidth
}
```
So, it cannot be greater than half of `blockMargin` or `lineHeight` (whatever is smaller). Please note, that it can be less. `blockMargin` is a property of `MarkwonTheme`. It controls the _right margin_ for text content for bullet-list, ordered-list, block-quote and task-list. If you increase it and also increase line height -> then you can also make bullet greater.

```java
.usePlugin(new AbstractMarkwonPlugin() {
    @Override
    public void configureTheme(@NonNull MarkwonTheme.Builder builder) {
        // you can pass here a relatively big value, it will be 
        // adjusted anyway by calculations that I had mentioned above
        builder.bulletWidth(128);
    }
})
```

`bulletListItemStrokeWidth` is working. Although its name is not clear, I agree that it can be confusing. All it does is &mdash; control the stroke width of a bullet point of the second level list, see the second line:
* first
   * second

**Comment by nksaroj** [comment]
Thank you very much @noties!!! It's an awesome library and great support too..
Highly recommended!
