### ISSUE TITLE
Lists not rendered through data binding

### ISSUE THREAD

**Issue by stephanepechard** [noties/Markwon#117]
* **Markwon version**: 3.0.0

1. Expected behavior can be seen in Markwon own app that you build from this repo clone. You get lists well rendered:
![Screenshot of well rendered lists](https://user-images.githubusercontent.com/703194/56370594-c61d3800-61fb-11e9-816f-09ffa55aa230.png)

Actual behavior is lists not rendered at all. This is what I get in my own app (truncated to first items).
![Screenshot of not well rendered lists](https://user-images.githubusercontent.com/703194/56371557-9f600100-61fd-11e9-91c9-c66563b52f01.png)

2. I use data binding to populate my TextView with its content, but I'm not particularly sure it is what causes the problem. Here is my layout:

```XML
<?xml version="1.0" encoding="utf-8"?>
<layout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools">

    <data>

        <variable
                name="model"
                type="StaticTextFieldItem"/>
    </data>

    <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingBottom="@dimen/editor_field_separation"
            android:background="@android:color/transparent">

        <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:richText="@{model.content}"
                app:isRich="@{model.isRich}"
                app:markdownProvider="@{model.markdownProvider}"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintStart_toStartOf="parent" />

    </androidx.constraintlayout.widget.ConstraintLayout>
</layout>
```

and the binding adapter where I hardcoded the list from the repo `README.md`:

```Kotlin
@BindingAdapter("richText", "markdownProvider", "isRich")
fun setRichText(view: TextView, richText: String, markdownProvider: MarkdownProvider, isRich: Boolean) {

    val markdown = "## Supported markdown features:\n" +
            "* Emphasis (`*`, `_`)\n" +
            "* Strong emphasis (`**`, `__`)\n" +
            "* Strike-through (`~~`)\n" +
            "* Headers (`#{1,6}`)\n" +
            "* Links (`[]()` && `[][]`)\n" +
            "* Images\n" +
            "* Thematic break (`---`, `***`, `___`)\n"

    val mw: Markwon = Markwon.create(markdownProvider.getAndroidContext())
    mw.setMarkdown(view, markdown)
}
```

I tried to edit the theme (`listItemColor`, `bulletListItemStrokeWidth` and `bulletWidth`) through the theme plugin, but nothing changed.

What I found curious is that titles and style (bold and italic) are well rendered. It only lacks lists and numbered lists which are not demonstrated here.

**Comment by noties** [comment]
Hello @stephanepechard !

Can you please try applying sample markdown to a TextView directly without databinding first? There are multiple possibilities:
* databinding fault
* layout fault
* markwon fault
* device fault

And we need to narrow them down

**Comment by stephanepechard** [comment]
Hello @noties !
Thanks for your help. I've tried to narrow my bug down, without success for now. I've succeeded in creating a small app combining Marwon and databinding and it works as expected. My app is kinda complex and it is not easy to simplify the usage of Markwon to a simple case.
What puzzles me the most is that some parts are rendered (titles, text styling, links) and some are not,  list bullets here. Do you have any idea what may be the cause of such a behaviour? Or if there's a specific part I should into?

Thanks in advance!

**Comment by stephanepechard** [comment]
Hello again,
I've found more valuable information. It seems that there's an incompatibility between Markwon and another dependency I use, [Android-Iconics](https://github.com/mikepenz/Android-Iconics). More specifically, I an option that enable automatic XML icons detection ([see here](https://github.com/mikepenz/Android-Iconics#3-define-iconicslayoutinflater-to-enable-automatic-xml-icons-detection-optional)). Removing this line shows the list bullets back in Markwon-rendered TextView.
I'll therefore need to find a way to combine both libraries into my project. If you have any idea, I'll be glad to hear it :-)

Thanks!

**Comment by noties** [comment]
Hey @stephanepechard !

After a quick glance at iconics, I think I know there the problem is: [Iconics only copies `ParcelableSpan` and `CharacterStyle` spans and ignores all the rest](https://github.com/mikepenz/Android-Iconics/blob/0b2c8f7d07b6d2715a417563c66311e7e1fcc7d8/library-core/src/main/java/com/mikepenz/iconics/utils/IconicsUtils.java#L144-L150). The obvious workaround would be to copy all the spans, for example like this:

```java
for (Object span : spannable.getSpans(0, spannable.length(), Object.class)) {
    existingSpans.add(new StyleContainer(spannable.getSpanStart(span), spannable.getSpanEnd(span), span, spannable.getSpanFlags(span)));
}
```

But I haven't invested much time in this solution. For starters it's not clear why copying is required in the first place... so, take this solution with a grain of salt.

But in general solution for this problem can actually be good for Iconics library also, because current implementation breaks some things that rely of spans (Markwon for example 😄 ).
