### ISSUE TITLE
Is there a way to better show tables with many columns?

### ISSUE THREAD

**Issue by victorlaerte** [noties/Markwon#12]
It's more a question, than a issue. 
I'm trying to show a table that has many columns, and the result is seen below.
![screenshot_1509973741](https://user-images.githubusercontent.com/7623098/32504062-a612da16-c3bd-11e7-84b9-a7818447c14f.png)
![screenshot_1509999018](https://user-images.githubusercontent.com/7623098/32504063-a66ee6a8-c3bd-11e7-8c21-ebbefcd153db.png)

Is there any way to make it more readable?

**Comment by noties** [comment]
Hey @victorlaerte !

Yeah, table support is really limited. A table will always take the full width of a TextView and make all columns equal. 

As an idea: if you can display table in a separate TextView, you can place it in a HorizontalScrollView for example and expand TextView width (to be more than screen width). This way you can achieve a more readable version... Unfortunately I do not see any other way

**Comment by victorlaerte** [comment]
By the way, it's worth to say, you did a really great job with this lib. Awesome.

**Comment by noties** [comment]
@victorlaerte thanks! Really appreciate it 🙌

**Comment by dreaming-butterfly** [comment]
Hello, how do you solve the problem of table drawing flickering?
