### ISSUE TITLE
Inconsistent line spacing after bullet point

### ISSUE THREAD

**Issue by jschnall** [noties/Markwon#122]
* **Markwon version**: 3.0.0 & 3.0.1

Observed behavior:
When a bullet item is very long, spanning multiple lines of text, the vertical spacing increases between each successive line.

Expected result:
The spacing between lines should remain consistent.

Original text:
- __The group session introduces the content for the following week.__ For example, after you have Group Session 3, you’ll be in Week 3 the next morning. You’ll pick a new daily action for the week and see new content on your dashboard.

<img width="387" alt="Screen Shot 2019-05-15 at 1 05 19 PM" src="https://user-images.githubusercontent.com/1756136/57874447-7c594a80-77c5-11e9-85b9-947b88a7366e.png">

**Comment by noties** [comment]
Hello @jschnall !

Are you sure you do not use `LineHeightSpan` for bullet lists? Because, I hate to say it, but it's working on my machine 😄

**Comment by jschnall** [comment]
Thanks @noties. I confirm it was a local issue after all.  Your comment pointed me in the right direction.  Someone was using a custom BulletSpan that was also implementing LineHeightSpan.
