### ISSUE TITLE
Load images from Drawable resources

### ISSUE THREAD

**Issue by SmileHub** [noties/Markwon#123]
* **Markwon version**: 3.0.1

Couldn't find more suitable place to adress the following question:
1. Is there a simple way how to load already existing Drawable images from the Resources (by file name? by resourceId? by anything related to them?)? (couldn't find an example and the other examples seemed to be complicated)
2. Consideration for the future: some interface allowing to load any custom images.

p.s. Awesome library! Thank you for it!

**Comment by noties** [comment]
Hello @SmileHub !

Well, we certainly can load images from resources. Here is a quick plugin to help with that:

```java
.usePlugin(new AbstractMarkwonPlugin() {
    @Override
    public void configureImages(@NonNull AsyncDrawableLoader.Builder builder) {

        // pseudo content-type for the drawable
        final String contentType = "android/drawable";

        builder
                // scheme handler for `drawable://res-id` urls
                .addSchemeHandler("drawable", new SchemeHandler() {
                    @Override
                    public ImageItem handle(@NonNull String raw, @NonNull Uri uri) {
                        return new ImageItem(
                                contentType,
                                // this is weird part -> convert to InputStream, as
                                // MediaDecoder expects InputStream...
                                new ByteArrayInputStream(raw.substring("drawable://".length()).getBytes()));
                    }
                })
                .addMediaDecoder(contentType, new MediaDecoder() {
                    @Nullable
                    @Override
                    public Drawable decode(@NonNull InputStream inputStream) {

                        // use scanner to read the stream fully, can be non-optimal for large input,
                        // and actually used here for demo purposes only,
                        // consider using something more robust
                        final Scanner scanner = new Scanner(inputStream, "UTF-8")
                                .useDelimiter("\\A");

                        // read the resource identifier
                        final String res = scanner.hasNext()
                                ? scanner.next()
                                : null;

                        // if it's not found -> return null
                        if (res == null) {
                            return null;
                        }

                        // now, obtain actual resource id
                        final int resId = context.getResources().getIdentifier(
                                res,
                                "drawable",
                                context.getPackageName());

                        if (resId != 0) {
                            // or ContextCompat.getDrawable
                            // also, we can additionally process the drawable here: apply bounds or color, etc
                            return context.getResources().getDrawable(resId);
                        }

                        return null;
                    }
                });
    }
})
```

You are raising proper concern about image loading. I actually find current implementation is far from perfect and plan to roll out an update to image loading in the next major library update. Current implementation although provides a lot of useful things (like images referenced in inline data-uri) still missing some crucial parts - mainly caching and memory-efficient image decoding. And usability is also, hgm, _so-so_. So, I'm planning to create multiple `image-loaders`: few based on popular image loading libraries (Picasso, Glide) and the one that is currently used in the Markwon. Anyway, this is the plan for the future. Meanwhile you can use the solution that I had posted and see if it fits your needs

**Comment by SmileHub** [comment]
Almost works, but something is missing for the images to be displayed.  Using your code for testing. Just added an extra output line:
`System.out.println("Img: res="+res + ", id="+ Integer.toString(resId));//testing`

```
public static void showDialogWithImages(Context context, String text, String okButtonText, String title){
        Markwon markwon = Markwon.builder(context)
                //.usePlugin(CorePlugin.create())
                .usePlugin(ImagesPlugin.create(context))
                .usePlugin(new AbstractMarkwonPlugin() {
                    @Override
                    public void configureImages(@NonNull AsyncDrawableLoader.Builder builder) {
                        // pseudo content-type for the drawable
                        final String contentType = "android/drawable";

                        builder
                                // scheme handler for `drawable://res-id` urls
                                .addSchemeHandler("drawable", new SchemeHandler() {
                                    @Override
                                    public ImageItem handle(@NonNull String raw, @NonNull Uri uri) {
                                        return new ImageItem(
                                                contentType,
                                                // this is weird part -> convert to InputStream, as
                                                // MediaDecoder expects InputStream...
                                                new ByteArrayInputStream(raw.substring("drawable://".length()).getBytes()));
                                    }
                                })
                                .addMediaDecoder(contentType, new MediaDecoder() {
                                    @Nullable
                                    @Override
                                    public Drawable decode(@NonNull InputStream inputStream) {
                                        // use scanner to read the stream fully, can be non-optimal for large input,
                                        // and actually used here for demo purposes only,
                                        // consider using something more robust
                                        final Scanner scanner = new Scanner(inputStream, "UTF-8")
                                                .useDelimiter("\\A");

                                        // read the resource identifier
                                        final String res = scanner.hasNext()
                                                ? scanner.next()
                                                : null;

                                        // if it's not found -> return null
                                        if (res == null) {
                                            return null;
                                        }

                                        // now, obtain actual resource id
                                        final int resId = context.getResources().getIdentifier(
                                                res,
                                                "drawable",
                                                context.getPackageName());

                                        System.out.println("Img: res="+res + ", id="+ Integer.toString(resId));//testing

                                        if (resId != 0) {
                                            // or ContextCompat.getDrawable
                                            // also, we can additionally process the drawable here: apply bounds or color, etc
                                            return context.getResources().getDrawable(resId);
                                        }

                                        return null;
                                    }
                                });
                    }
                })
                .build();
        TextView textView = new TextView(context);
        markwon.setMarkdown(textView, text);
       showDialog(context, textView, okButtonText, title);
    }
```

show dialog takes the TextView and displays it with ok/cancel buttons:
```
 public static void showDialog(Context context, View documentView, String okText, String title){
        AlertDialog.Builder dlgAlert  = new AlertDialog.Builder(context);
        if (title != null)
        dlgAlert.setTitle(title);
        dlgAlert.setPositiveButton(okText, (dialog, which) -> {
                    //dismiss the dialog
                })
                .setView(documentView)
                .setCancelable(true)
                .create().show();
    }
```

Testing showDialogWithImages() on this string:
```
"![alt text](drawable://ic_info \"Test\") - 1\n" +
"![alt text](drawable://ic_info) - 2\n" +
"![alt](drawable://ic_info) - 3\n"
```

And do get output, but no images displayed in the TextView, just alternative text is visible. Output:
> ...  I/System.out: Img: res=ic_info, id=2131165501
> ...  I/System.out: Img: res=ic_info, id=2131165501
> ...  I/System.out: Img: res=ic_info, id=2131165501

Am I missing something?

**Comment by noties** [comment]
Hello @SmileHub !

First, I would ask you to try this on a _regular plain_ view. Because dialogs are special kids when it comes to layouts. Secondly, I would ask you to try different resources. In the sample input you used the same resource. And the thing is - default image loader stores a background task in a Map identified by it's URL (in order to cancel it). So.. only one request will be _delivered_ for a given markdown input. It's super weird and I'm going to think of how to fix that. Should be an easy fix though.

PS, ah, also my implementation of drawable-loader missed the important part - bounds:
```java
if (resId != 0) {
    // or ContextCompat.getDrawable
    // also, we can additionally process the drawable here: apply bounds or color, etc
    final Drawable drawable = context.getResources().getDrawable(resId);
    DrawableUtils.applyIntrinsicBounds(drawable);
    return drawable;
}
```

**Comment by noties** [comment]
Hello @SmileHub !

I've uploaded the `3.1.0-SNAPSHOT` version with changes that I had mentioned. Please try it and tell me if it's working for you.

PS, [instructions how to use snapshot version](https://noties.io/Markwon/docs/v3/install.html)

**Comment by SmileHub** [comment]
You were right, the only part missing was
`DrawableUtils.applyIntrinsicBounds(drawable);`

Now images are displayed in the dialog, even though it may act somewhat differently as you've mentioned (testing time).

As for multiple same drawable usage:
it was just for testing purpose and yes, the first ones were canceled and only the final one was displayed. At the moment going to skip the snapshot as there is no need for multiple same image display for me, but definitely the use case of displaying them  should be in the Markwon.

Gonna try and see:
1) if it's possible to properly format the text there with images, or it does put everything into a one line.
2) Optimise the scanner part a bit and share it here to this issue and the the issue can be closed imho.

Thank you for your assitance and keep going with a nice project!

See your on the network in future! :)

**Comment by SmileHub** [comment]
Unnoticible final things i've noticed:
1. will keep scanner instead of buffered reader (less code lines and i'm using defined length strings which are okey to fully read. The only change i made  was ensuring the same charset is read as passed:
`final Scanner scanner = new Scanner(inputStream, Charset.defaultCharset().name()) //"UTF-8"`

2. not sure if it's due to .useDelimiter("\\A"); part and what \A in regex means, but new line symbols of formated string are trimmed and had to use double to have new lines, for example:
```
 "    ![test0](drawable://t0) - t0;\n\n" +
                        "    ![test1](drawable://t1) - t1;\n\n" +
                        "    ![test2](drawable://t2) - t2;\n\n" +
                        "\nExtra new line 1\n\n"+
                        "\nExtra new line 2\n\n"
```

3. it seems that although i manage to load the following drawable in the ImageView, as "app:srcCompat", i can't load it into the Markwon (it works with the rest of the images without extra gradient format):
```
<vector android:autoMirrored="true" android:height="24dp"
    android:viewportHeight="24.0" android:viewportWidth="24.0"
    android:width="24dp" xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt">
    <path android:pathData="M21,3L3,3c-1.1,0 -2,0.9 -2,2v14c0,1.1 0.9,2 2,2h18c1.1,0 2,-0.9 2,-2L23,5c0,-1.1 -0.9,-2 -2,-2z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:endX="24"
                android:endY="1"
                android:startX="1"
                android:startY="1"
                android:type="linear">
                <item
                    android:color="#000000"
                    android:offset="0.0"/>
                <item
                    android:color="#000000"
                    android:offset="0.5"/>
                <item
                    android:color="#00ffffff"
                    android:offset="1"/>
            </gradient>
        </aapt:attr>
    </path>
</vector>

```

**Comment by noties** [comment]
Hello @SmileHub !

1. Charset is definitely a good addition
2. This is commonmark thing, as it treats a single new-line character as a `softbreak`. You can use 2 new-lines (or more) to create a `hardbreak` or modify the visitor:
```java
final Markwon markwon = Markwon.builder(context)
        .usePlugin(CorePlugin.create())
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configureVisitor(@NonNull MarkwonVisitor.Builder builder) {
                builder.on(SoftLineBreak.class, new MarkwonVisitor.NodeVisitor<SoftLineBreak>() {
                    @Override
                    public void visit(@NonNull MarkwonVisitor visitor, @NonNull SoftLineBreak softLineBreak) {
                        visitor.ensureNewLine();
                    }
                });
            }
        })
```
3. I think the issue here is actual vector drawable. Most likely you are using compat edition (right?), so you won't be able to retrieve it by simply calling `resources.getDrawable`, instead you would need to use the _compat_ way: `ContextCompat.getDrawable`
4. Interesting... if you add four spaces before a line, this line will be considered an `indented-code-block`, so you should see actual `![test0](drawable://t0) - t0;` text inside a code-block (code-blocks don't have image-loading nor other markdown capabilities)

**Comment by SmileHub** [comment]
1. Hey! :)
2. Thanks for keywords and example (shall dig deeper on differences between soft & hard)
3. using `ContextCompat.getDrawable` gives same unloadable image
4. Other markdown capabilities work, example:` "    1. **Bold**"` - idented, numbered and bold

Cheers!

**Comment by Jsx9989** [comment]
Markwon version: 4.5.0
Isn't find configureImages function in AbstractMarkwonPlugin class 
Which dependency library is it in
Please tell me,Thank you
