### ISSUE TITLE
Embedded urls are not clickable if android:autoLink="web|email" is added to textView

### ISSUE THREAD

**Issue by Junaid-Ahmed-Qureshi** [noties/Markwon#125]
* **Markwon version**: 2.0.2

In my messaging app I want to show default urls along with embedded ones. 

**Actual behavior**
if I add `android:autoLink="web|email"` to `textView` to support default urls then embedded urls are no more clickable.

**Expected behavior**
The embedded links should be clickable.

**Steps to reproduce**
1. Use `Markwon.setMarkdown(textView, spannableConfiguration, text);` to set text.
2. Add `android:autoLink="web|email"` to `textView` 

It will make the default Urls `www.google.com` clickable but embedded Urls `[Google](www.google.com)` are no more clickable.

**Comment by Junaid-Ahmed-Qureshi** [comment]
@notie

**Comment by noties** [comment]
Hello @Junaid-Ahmed-Qureshi !

I can confirm this be behavior. The thing is - using _built-in_ autolink won't work with markdown links, here is a javadoc from autolink method:

```java
/**
 * Scans the text of the provided Spannable and turns all occurrences
 * of the link types indicated in the mask into clickable links.
 * If the mask is nonzero, it also removes any existing URLSpans
 * attached to the Spannable, to avoid problems if you call it
 * repeatedly on the same text.
 */
```

In short - it will remove existing links first. So all existing links will be removed. This happens in both cases:
* when you specify `autolink="web|email"` in your XML
* and when you call `Linkify.addLinks(textView, Linkify.WEB_URLS | Linkify.EMAIL_ADDRESSES);` programmatically

In order to keep both you can use `commonmark-java` `autolink` extension:

```groovy
implementation 'com.atlassian.commonmark:commonmark-ext-autolink:0.12.1'
```

and then specify it when creating `Parser`, for `2.x.x` version:

```java
// wow, that's old...

// create parser (these are default extensions that Markwon is using
// plus `AutolinkExtension`)
final Parser parser = new Parser.Builder()
        .extensions(Arrays.asList(
                StrikethroughExtension.create(),
                TablesExtension.create(),
                TaskListExtension.create(),
                AutolinkExtension.create()
        ))
        .build();

// obtain your configuration
final SpannableConfiguration configuration = /* your configuration */

// parse
final Node node = parser.parse(markdown);
final SpannableRenderer renderer = new SpannableRenderer();

// render
final CharSequence cs = renderer.render(configuration, node);

// apply
Markwon.setText(textView, cs);
```

for `3.x.x` version:

```java
final Markwon markwon = Markwon.builder(context)
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configureParser(@NonNull Parser.Builder builder) {
                builder.extensions(Collections.singletonList(AutolinkExtension.create()));
            }
        })
        // your other plugins
        .build();

markwon.setMarkdown(textView, markdown);
```

**Comment by Junaid-Ahmed-Qureshi** [comment]
Hi @noties 

I have tried your suggestion but it gives the same behavior. I have even tried enabling the autolink in XML but didn't work. Here is the code for reference:

```
Parser parser = new Parser.Builder()
                .extensions(Arrays.asList(
                        StrikethroughExtension.create(),
                        TablesExtension.create(),
                        TaskListExtension.create(),
                        AutolinkExtension.create()
                ))
                .build();

SpannableTheme theme = SpannableTheme.builderWithDefaults(textView.getContext())
                .linkColor(textView.getTextColors().getDefaultColor())
                .build();

SpannableConfiguration spannableConfiguration = SpannableConfiguration.builder(textView.getContext())
                .theme(theme)
                .linkResolver(new LinkSpan.Resolver() {
                    @Override
                    public void resolve(View view, @NonNull String link) {
                        KUSUtils.openUrl(view.getContext(), link);
                    }
                })
                .build();

final Node node = parser.parse(text);
final SpannableRenderer renderer = new SpannableRenderer();

final CharSequence cs = renderer.render(spannableConfiguration, node);

Markwon.setText(textView, cs);
```

**Comment by Junaid-Ahmed-Qureshi** [comment]
Just checked again. Seems like it does work but only for URLs with Schemes like `http://` or 'https://'. Verified it from the documentation [here](https://github.com/robinst/autolink-java) as well. 

Is there any other possible work around to support URLs without scheme as well? like `www.google.com` and `google.com`?

**Comment by noties** [comment]
Well, `www` links are supported by `autolink-java`. Unfortunately commonmark autolink extension doesn't give you such a configuration option. But you can inspect the source code of [AutolinkPostProcessor](https://github.com/atlassian/commonmark-java/blob/master/commonmark-ext-autolink/src/main/java/org/commonmark/ext/autolink/internal/AutolinkPostProcessor.java) and adjust it to your needs to include whatever link-types you require

**Comment by Junaid-Ahmed-Qureshi** [comment]
Thanks for your help @noties . It didn't seem the best solution to change the `commonmark-java` since there is still limitations for links without `www`. I have preferred to write my own regex that detects and converts simple urls into embedded one's. 

I hope `commonmark-java` & `auto-link` both support all types of urls some day. Thanks!

**Comment by noties** [comment]
Glad I could help @Junaid-Ahmed-Qureshi 🙌
