### ISSUE TITLE
How to set hightlight to a markdown

### ISSUE THREAD

**Issue by maphongba008** [noties/Markwon#126]
* **Markwon version**:2.0.2
Hello, I have an markdown and want to apply syntax hightlight for it but don't know how to do. The document only shows me how to create an instance of SyntaxHightlight, but does not mention how to apply it to Markwon. Here's my code:
```
TextView tv = findViewById(R.id.textView);
        Markwon.setMarkdown(tv, md);
        final SyntaxHighlight highlight =
                Prism4jSyntaxHighlight.create(
                       new Prism4j(new MyGrammarLocator()), 
                       Prism4jThemeDarkula.create());
```
Thanks

**Comment by noties** [comment]
Hello @maphongba008 !

First, you have to configure the [prism4j](https://github.com/noties/Prism4j) in your project. Then you have to update `SpannableConfiguration` to use `Prism4jSyntaxHighlight`:

```java
final SpannableConfiguration configuration = SpannableConfiguration.builder(context)
        // init syntax-hightlight
        .syntaxHighlight(Prism4jSyntaxHighlight.create(prism4j, prism4jTheme))
        .build();
```

Anyway, you can inspect source code for [2.x.x sample app](https://github.com/noties/Markwon/blob/ece7e73b21c57af0eef9ade41bae57659dcacd20/app/src/main/java/ru/noties/markwon/MarkdownRenderer.java#L93), it has syntax-highlight configured

**Comment by maphongba008** [comment]
thank you so much, it works
