### ISSUE TITLE
Cinopsys: Movies and Shows

### ISSUE THREAD

**Issue by Kashish-Sharma** [noties/Markwon#128]
* Cinopsys: Movies and Shows
* [App link](https://play.google.com/store/apps/details?id=com.cinopsys.movieshows&hl=en_IN)
* [Brand Image](https://drive.google.com/open?id=1rD0HLd8tDUCe8QcVEG_iGvsJbFyozRhC)

**Comment by Kashish-Sharma** [comment]
Can you please this app along with the other apps on website?

**Comment by noties** [comment]
Of cause I can, I will do it with the next documentation update (this is why this issue is still open) 🙌

**Comment by Kashish-Sharma** [comment]
Thanks a lot!
And also for the library!!

**Comment by noties** [comment]
Done! https://noties.io/Markwon/#awesome-markwon
