### ISSUE TITLE
Proposal: allow ServiceLoader for loading plugins

### ISSUE THREAD

**Issue by ZacSweers** [noties/Markwon#130]
Normally this would come with a runtime reflection cost, but R8 (now enabled by default in Android) will soon optimize this during its optimization pass to avoid runtime reflection costs. This would allow for plugins to be automatically registered just by being on the classpath. This could be optional though, and still leave the ability to manually instantiate and add plugins.

**Comment by noties** [comment]
Hello @ZacSweers !

I think it would be a good thing to do. I was thinking about similar functionality but in terms of annotation-processor and a generated _locator_. Back then I decided not to pursue this functionality because most of the parts/plugins required configuration (explicitly passed to constructor/factory-method). But now as plugins are configurable in post-construction state it might be a good addition. I will investigate the ServiceLocator and meanwhile put a temporary `4.0.0` milestone 🙌

**Comment by ZacSweers** [comment]
I could try a PR if you want as well

**Comment by noties** [comment]
I would like if we discuss things first 😄 . First, let's evaluate what we have. It would be really good if we could use some _native_ android way... 

We have annotation processors. The good solution would be if annotation-processor could process annotations from libraries (needs to be checked). If it could we would annotate a Plugin and them _collect_ them. This still has a problem with plugins having different required arguments to be instantiated...

We could use a ContentProvider in each module. This technique is currently used by some libraries to _automagically_ receive Context. And it seems like a good option. The downside here is I'm not sure if this would have a performance penalty...

Downsides of ServiceLoader:
* reflection
* ~~all plugins will have to have a common method to init self (to be initialized via reflection)~~ The thing is: `ServiceLoader` will instantiate classes via `class.newInstance()` which requires an empty constructor. Now a lot of plugins require additional parameters, so this would be a major change in how plugins are operating...

Anyway, if you have any ideas, let's make this issue also a discussion (before jumping to PRs 😉 )

**Comment by ZacSweers** [comment]
As mentioned in my prior comment - R8 will remove the reflection cost by inlining instantiation directly (it won't _actually_ do reflective service loading at runtime), so I don't think an annotation processor would be needed. I don't think you want this automatically initialized in a contentprovider either (especially since Markwon seems to defer to the given context for theming, user would likely want to control that with scoping).

I forgot about the configuration aspect of different plugins though. That's enough for me to think this probably isn't worthwhile right now then :)
