### ISSUE TITLE
Feature request: Base64 support for image tags

### ISSUE THREAD

**Issue by preprux** [noties/Markwon#133]
* **Markwon version**: 3.0.1

This library currently does not support base64 content in image tags
<img src="data:image/png;base64,iVBORw0KGgoAAAA..." 

Will it be possible to render images in base64? Thanks!

**Comment by noties** [comment]
Hello @preprux !

It is supported, you just have to make sure to include `DataUriSchemeHandler` (and obviously `HtmlPlugin`):

```java
final Markwon markwon = Markwon.builder(context)
        .usePlugin(CorePlugin.create())
        .usePlugin(HtmlPlugin.create())
        .usePlugin(ImagesPlugin.createWithAssets(context))
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configureImages(@NonNull AsyncDrawableLoader.Builder builder) {
                builder.addSchemeHandler(DataUriSchemeHandler.SCHEME, DataUriSchemeHandler.create());
            }
        })
        .build();
```

**Comment by preprux** [comment]
It works! Another question: Are iframes supported?

**Comment by noties** [comment]
No, iframes are not supported

**Comment by preprux** [comment]
Got it. Thanks for the help!
