### ISSUE TITLE
Change bullet character to "-"

### ISSUE THREAD

**Issue by NicoEkino** [noties/Markwon#135]
* **Markwon version**:3.0.0

Hi and thank you for this lifesaver library!

So far, I've been able to customize rendering, but I'm struggling to customize bullet rendering.
I'd like to have a dash ("-") instead of the bullet character.

I'm not sure if I have to use the SpanFactory or the visitor to implement this.

Do you have any idea how to do this ?

**Comment by noties** [comment]
Hello @NicoEkino !

Well, I have few ideas, the first one would be using `SpanFactory`:

```java
.usePlugin(new AbstractMarkwonPlugin() {
    @Override
    public void configureSpansFactory(@NonNull MarkwonSpansFactory.Builder builder) {
        
        // current list-item factory (will take care of ordered lists)
        final SpanFactory origin = builder.requireFactory(ListItem.class);
        
        builder.setFactory(ListItem.class, new SpanFactory() {
            @Nullable
            @Override
            public Object getSpans(
                    @NonNull MarkwonConfiguration configuration,
                    @NonNull RenderProps props) {

                // detect with which list item we are dealing with
                if (CoreProps.LIST_ITEM_TYPE.require(props) != CoreProps.ListItemType.BULLET) {
                    return origin.getSpans(configuration, props);
                }
                
                // it's bullet list item
                // you can return your span here, see BulletListItemSpan for a reference
            }
        });
    }
})
```

This will require a custom span that will draw the `-` character before text on a canvas. You can inspect `BulletListItemSpan` for a reference. There is another option of using `Visitor`, but it will be lengthy and you will have to replicate all the logic behind ordered-lists... I would recommend going for a custom span and `SpanFactory`.

**Comment by NicoEkino** [comment]
Hi @noties,
thanks a lot for your quick answer!
I hacked `OrderedListItemSpan` to display a "-" and it seems to work : 
```kotlin
           builder.setFactory(ListItem::class.java, object :
                SpanFactory {
                override fun getSpans(configuration: MarkwonConfiguration, props: RenderProps): Any? {
                    if (CoreProps.LIST_ITEM_TYPE.require(props) != CoreProps.ListItemType.BULLET) {
                        originListItem.getSpans(configuration, props)
                    }
                    return arrayOf(
                        OrderedListItemSpan(configuration.theme(), "-")
                    )
                }
            })
```


Using this I just discovered a strange bug with this source data: 
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit,
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
1. Sed ut perspiciatis unde omnis iste natus error
2. sit voluptatem accusantium doloremque laudantium,
3. Organisation d'eco-marches hebdomadaires, pour decouvrir et proteger l’environnement Naturel du village
4. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur
```

This text renders with a "Ghost" dash on number 3 and I couldn't understand why. (doesn't happen with other markdown renderer I tried)

![Screenshot_20190619-171136](https://user-images.githubusercontent.com/24221189/59778152-3f95dd00-92b6-11e9-9042-336fa3fd9195.png)

**Comment by noties** [comment]
Hello @NicoEkino !

You've found an interesting way of doing it 😄 !

About the _ghost_ one... I've just tried and it's working for me. Just a wild guess, can you try with `android:hyphenationFrequency="none"` on your TextView?

**Comment by NicoEkino** [comment]
You're right, it's gone with this. 
Thank you so much for your quick and accurate support, consider this topic resolved!
