### ISSUE TITLE
Multiple identical images

### ISSUE THREAD

**Issue by nielsz** [noties/Markwon#145]
When using a Markdown file that contains multiple identical images, only one of the images is resolved, instead of all of them.

* **Markwon version**: 3.0.2

`![abc1](https://my.image/icon-size-32.png) ![abc2](https://my.image/icon-size-32.png)  ![abc3](https://my.image/icon-size-32.png)`

**Comment by noties** [comment]
Hello @nielsz !

I'm aware of this issue. And it's fixed in upcoming `4.0.0` release (`4.0.0-SNAPSHOT`) and `3.1.0-SNAPSHOT` version. Can you try one of them and tell me if issue persists?

**Comment by nielsz** [comment]
Yup, it is Fixed on 4.0.0-SNAPSHOT! (I used Picasso in this case.)  :thumbsup:

**Comment by noties** [comment]
The fix is released in both `4.0.0` and `3.1.0` versions
