### ISSUE TITLE
[Question] 4.0.0 Latex plugin

### ISSUE THREAD

**Issue by ringosham** [noties/Markwon#147]
Just tried out the newest version of the Latex plugin (4.0.0). I can't figure out how to get the formulas rendered.

According to the doc, I don't need ImagesPlugin anymore.

The Markwon initializer becomes the following.
```Markwon.builder(getContext()).usePlugin(JLatexMathPlugin.create(18)).build();```
However, no matter what formulas I set as the markdown content, it refuses to render the formulas.

Adding jlatexmath-android does nothing as well.

**Comment by noties** [comment]
Hello @ringosham !

You are right. Can confirm. There is a bug in latest version involving `background-provider`. As a quick fix, specify any non-null `background-provider` when building `JLatexMathPlugin` (as it requires `non-null` drawable you can use `ColorDrawable(0)`)

**Comment by noties** [comment]
Fixed in latest `4.0.1` release
