### ISSUE TITLE
Accessibility TalkBack

### ISSUE THREAD

**Issue by DanielNogueiraAndroid** [noties/Markwon#151]
* **Markwon version**: _{4.0.0}_

Setup
Run the sample app (the current version of master)
Turn TalkBack on https://support.google.com/accessibility/android/answer/6007100?hl=en
(If you are not familiar with talkback I suggest to do the Talkback tutorial just after the enable it)
Open the app navigate to the first sample "Core"

Expected behaviour
1-the navigation by swipe can select the link "markdown"
2-the link "markdown" can be activated (the same thing that a click does)

Actual behaviour
1- It is not possible to select the  select the link "markdown"
2-It is not possible to click on the link (double-tap to activate does not work)

Note it is very standard for Android apps to work fine with TalkBack (the main tool for blind people to use Android)

**Comment by noties** [comment]
Hello @DanielNogueiraAndroid !

Unfortunately there is no problem with Markwon here. Markwon uses native TextView and spans for styling. Inability to navigate by swipe to a link in a TextView and double click on a link in a TextView is a TalkBack problem. You can easily validate it this code:

```java
// movement method is required for links to be clickable (at least in regular touch mode)
textView.setMovementMethod(LinkMovementMethod.getInstance());

final SpannableStringBuilder builder = new SpannableStringBuilder();
builder.append("hello ");
final int start = builder.length();
builder.append("world");

// set link span
builder.setSpan(
        new URLSpan("https://www.com"),
        start,
        builder.length(),
        Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);

textView.setText(builder);
```

I wish I could do something here, but it seems that TalkBack is missing a feature to work with spans inside a TextView

**Comment by noties** [comment]
I found a thread on [stackoverflow](https://stackoverflow.com/q/42206928/6745174) maybe it can help you

**Comment by DanielNogueiraAndroid** [comment]
Do you guys know any other accessibility tool on Android that works with spans? If spans never worked with TalkBack or any accessibility tool maybe was no the best choice of Android component to put all the markdown content. There is any way to customize the factories to not use spans or to use a group of spans inside a viewGroup to make the library accessible.

**Comment by noties** [comment]
<ins>Library is as accessible as Android is</ins>. If stackoverflow thread that I had posted didn't help, then I'm sorry - you have to look for other options.

P.S., please don't try to put spans in a ViewGroup
