### ISSUE TITLE
Loading android resources into markdown

### ISSUE THREAD

**Issue by enyciaa** [noties/Markwon#153]
* **Markwon version**: 4.0.2

expected: Android resource is shown in markdown
actual: the image uri is displayed as text and SchemeHandler.handle method is never called

Sorry this may just be a simple set up issue! But I've dug through all the docs and github issues and can't figure out a fix!

In 2.x.x version of the library I used to use a custom node setup to display images from android resources, whilst upgrading to 4.x.x I've tried using the Image plugin.

Here's the code I use (in Kotlin) - mostly copied from the docs.
```
val markwon = Markwon.builder(context)
                .usePlugin(ImagesPlugin.create(object : ImagesPlugin.ImagesConfigure {
                    override fun configureImages(plugin: ImagesPlugin) {
                        plugin.addSchemeHandler(object : SchemeHandler() {
                            override fun handle(
                                    raw: String,
                                    uri: Uri
                            ): ImageItem {
                                // will handle URLs like `drawable://ic_account_24dp_white`
                                val resourceId = context.resources.getIdentifier(
                                        raw.substring("drawable://".length),
                                        "drawable",
                                        context.packageName
                                )
                                val drawable = context.getDrawableCompat(resourceId)
                                return ImageItem.withResult(drawable)
                            }

                            override fun supportedSchemes(): MutableCollection<String> {
                                return Collections.singleton("drawable")
                            }

                        })
                    }})).build()

markwon.setMarkdown(textView, "drawable://ic_tdtraining1_color_24dp")
```

supportedSchemes seems to be called fine, but handle is never called. Even if the scheme is switched to one of the default scheme handlers (like data:) - the handle on DataUriSchemeHandler is never called.

Is there something simple I'm missing?

**Comment by noties** [comment]
Hello @enyciaa !

You are missing one _minor_ detail - you are not using markdown syntax 😄 . Change your input to:

```markdown
![image alt](drawable://ic_tdtraining1_color_24dp)
```

**Comment by enyciaa** [comment]
Ha! Thanks! 😄
