### ISSUE TITLE
linkify onclick listener

### ISSUE THREAD

**Issue by GHChrisSu** [noties/Markwon#156]
* **Markwon version**: 4.1.0

LinkifyPlugin.create() made the phone web_url can be clicked but if I want to do something at my click action was happened, no method to setup a clicklistener, could you add this feature?

Common issue like analyze user's action, did click the phone but didn't call out

**Comment by noties** [comment]
Hello @GHChrisSu !

This can be done with the [LinkResolver](https://noties.io/Markwon/docs/v4/core/configuration.html#linkresolver). You can use `LinkResolverDef` to have a default implementation that opens other screens/activities:

```java
builder.linkResolver(new LinkResolverDef() {
    @Override
    public void resolve(@NonNull View view, @NonNull String link) {
        // do something with the link here
        // and then call super to start appropriate Activity
        super.resolve(view, link);
    }
});
```

**Comment by GHChrisSu** [comment]
Is LinkResolver for markdown? LinkifyPlugin was resolving the phone web_urls and e_mail, sorry for I didn't clear with source code, I just thought phone web_urls and e_mail will not resolve by LinkResolverDef

**Comment by noties** [comment]
So, the issue is resolved then? 😄

**Comment by noties** [comment]
Please feel free to re-open if you have any more questions on the subject
