### ISSUE TITLE
Intermittent IndexOutOfBoundsException on render

### ISSUE THREAD

**Issue by damianw** [noties/Markwon#157]
* **Markwon version**: _4.0.2_

I'm not really sure how to reproduce the issue, but am seeing occasional crash reports from Crashlytics like this:
```
Caused by java.lang.IndexOutOfBoundsException: setSpan (4007 ... 4043) ends beyond length 4007
       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1327)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:688)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:680)
       at io.noties.markwon.SpannableBuilder.spannableStringBuilder(SpannableBuilder.java:323)
       at io.noties.markwon.MarkwonImpl.render(MarkwonImpl.java:61)
      // ...
```

I've not been able to reproduce the problem, nor does it seem specific to any device/API level/manufacturer. Perhaps some kind of race condition?

**Comment by noties** [comment]
Hello @damianw !

Can you please share the configuration that you use for Markwon (plugins) and approximate markdown that is used? I haven't seen such crashes myself, but from the stacktrace it _seems_ that underlying text and spans-list are out of sync (text is removed but spans are present, or spans are set but text that is never added). But we need more info to pin-point the issue

**Comment by noties** [comment]
Hello @damianw !

After looking at [this](https://stackoverflow.com/a/48401970/6745174), I wanted to ask if your markdown is _lengthy_ (like over 9000 characters in length), or does your widget has a text limit set? And which one do you use: `TextView`, `EditText` or something else?

**Comment by noties** [comment]
Hello @damianw !

You are bringing attention to an important issue actually. Why exactly a (mutable) Visitor is reused for a `Markwon` instance... It's kind of _legacy_ and I think there must be no performance-wise downsides if visitor won't be reused (thus making `Markwon` thread-safe). I'm going to take a look

**Comment by noties** [comment]
Pushed new `4.1.1-SNAPSHOT` version with working implementation

**Comment by damianw** [comment]
Thanks!
