### ISSUE TITLE
Padding space between tables

### ISSUE THREAD

**Issue by ringosham** [noties/Markwon#159]
* Markwon version: 4.1.0
* Markwon table extension: 4.1.0

After looking through the documentation, I can't seem to find anything about vertical paddings between tables. When you create two tables after another, the two tables just stick to each other.

**Comment by noties** [comment]
Hello @ringosham !

Yes, it seems that table blocks do not have proper line breaks. This is due to the fact that `TablesPlugin` uses `TableBody` to detect next node (instead of `TableBlock`) and this fails

**Comment by noties** [comment]
Pushed `4.1.1-SNAPSHOT` version with the fix
