### ISSUE TITLE
How to implement custom markdown spec

### ISSUE THREAD

**Issue by wax911** [noties/Markwon#161]
* **Markwon version**: _4.1.0_

First off I'd like to say thank you for this for the hard work, I've been trying to think of the best way to implement some custom Markdown spec features e.g. 
> `img###(https://media.giphy.com/media/IcJ6n6VJNjRNS/giphy.gif)` 

I would create a standard markdown/html image tag from this using a simple regex patter like: 
> (img)(.*?)(\([^)]+\)) 

The above would allow me to extract the size, and url

### Current Implementation Behaviour

I've tried using the `AbstractMarkwonPlugin.processMarkdown()` function but I'm sure this is not the best way to go about this.

```kotlin
class CustomImagePlugin private constructor(): IMarkdownPlugin, AbstractMarkwonPlugin() {

    /**
     * Regular expression that should be used for the implementing class
     */
    @VisibleForTesting(otherwise = Modifier.PRIVATE)
    override val regex = Regex(
        pattern = PATTERN_IMAGE,
        option = RegexOption.IGNORE_CASE
    )

    override fun processMarkdown(markdown: String): String {
        var buffer: String = markdown
        val matchers = regex.findAll(markdown)
        for (match in matchers) {
            val groups = match.groups
            val target = groups[GROUP_ORIGINAL_MATCH]?.value
            // ... impl replacing all custom markdown spec with standarad html/mardown
        }
        return buffer
    }

    companion object {

        @VisibleForTesting(otherwise = Modifier.PRIVATE)
        const val PATTERN_IMAGE = "(img)(.*?)(\\([^)]+\\))"

        private const val GROUP_ORIGINAL_MATCH = 0
        private const val GROUP_IMAGE_SIZE = 2
        private const val GROUP_IMAGE_SRC = 3

        fun create() = ImagePlugin()
    }
}
```

Could you please advise on how to go about this?

### Alternative Implementation Behaviour

What I also tried was making use of `AbstractMarkwonPlugin.beforeRender` but this is documented to be:
> This method will be called before rendering will occur thus making possible to post-process parsed node (make changes for example).

Thus getting an image span to pick  it up at this point might not work?

```kotlin
class CustomImagePlugin private constructor(): IMarkdownPlugin, AbstractMarkwonPlugin() {

    /**
     * Regular expression that should be used for the implementing class
     */
    @VisibleForTesting(otherwise = Modifier.PRIVATE)
    override val regex = Regex(
        pattern = PATTERN_IMAGE,
        option = RegexOption.IGNORE_CASE
    )


    override fun beforeRender(node: Node) {
        node.accept(ImageVisitor())
    }

    inner class ImageVisitor : AbstractVisitor() {

       private fun replaceLiteral(node: String): String {
            var buffer: String = node
            val matchers = regex.findAll(node)
            for (match in matchers) {
                val groups = match.groups
                val target = groups[GROUP_ORIGINAL_MATCH]?.value
                // ... impl replacing all custom markdown spec with standarad html/mardown
            }
            return buffer
        }

        override fun visit(text: Text?) {
            val literal = text?.literal.orEmpty()
            if (literal.contains(regex))
                text?.literal = replaceLiteral(literal)
        }
    }

    companion object {

        @VisibleForTesting(otherwise = Modifier.PRIVATE)
        const val PATTERN_IMAGE = "(img)(.*?)(\\([^)]+\\))"

        private const val GROUP_ORIGINAL_MATCH = 0
        private const val GROUP_IMAGE_SIZE = 2
        private const val GROUP_IMAGE_SRC = 3

        fun create() = ImagePlugin()
    }
}
```

**Comment by noties** [comment]
Hello @wax911 !

I think the the `alternative` approach is the best one at the moment. It is actually advised by `commonmark` creator and used by [commonmark-ext-autolink](https://github.com/atlassian/commonmark-java/blob/master/commonmark-ext-autolink/src/main/java/org/commonmark/ext/autolink/internal/AutolinkPostProcessor.java) artifact (although it uses `commonmark` post-processor, but it's a minor difference).

The _absolute_ best solution would be to write a custom inline-parser, but unfortunately it's still not possible ([#113](https://github.com/atlassian/commonmark-java/issues/113)).

**Comment by wax911** [comment]
Thank you so much for the advice and suggestions, I'll give this a go!! :clap:

**Comment by noties** [comment]
You are welcome! Feel free to re-open if you will have more questions 🙌

**Comment by ubuntudroid** [comment]
@noties sorry for digging this up after such a long time. I've implemented a special tag for an expanded image using the solution outlined in https://github.com/noties/Markwon/issues/161#issuecomment-524819033

```kotlin
ImageProps.IMAGE_SIZE.set(visitor.renderProps(), ImageSize(
    ImageSize.Dimension(100f, "%"),
    null
))
```

It works perfectly fine, but the result is much more pixelated than when using HTML:

```
<img src="https://picsum.photos/id/237/1024/800" width="100%" height="auto"></img>
```

Any idea why that's the case? I would have expected it to be the other way around. 🤔

**Comment by noties** [comment]
Hello @ubuntudroid ,

both images (native and HTML defined) should be displayed the same - because rendering logic is the same. I've created a [sample](https://noties.io/Markwon/app/sample/20200803115847) and cannot tell the difference between images. Maybe you are using different URLs or there is some other configuration steps?

**Comment by ubuntudroid** [comment]
Your sample works perfectly fine and actually I like your approach (just use full-width as sensible default) much more. Thanks @noties ! ❤️
