### ISSUE TITLE
SvgSupport for svg without a width and height info

### ISSUE THREAD

**Issue by 3dmg** [noties/Markwon#165]
* **Markwon version**: 4.1.1

First of all, thank you for your great work!

When I want to load a SVG without a `width & height` set in the file, I get this exception:
```
MARKWON-IMAGE: Error loading image: https://upload.wikimedia.org/wikipedia/commons/d/d7/Android_robot.svg
    java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1033)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1000)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:950)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:911)
        at io.noties.markwon.image.svg.SvgMediaDecoder.decode(SvgMediaDecoder.java:70)
        at io.noties.markwon.image.AsyncDrawableLoaderImpl$1.run(AsyncDrawableLoaderImpl.java:123)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764) 
```

Most of the SVGs, I found online, were without these size information.

Is it possible to fallback to a default size for this case or is there another solution?

One example of an affected SVG: https://upload.wikimedia.org/wikipedia/commons/d/d7/Android_robot.svg

**Comment by noties** [comment]
Hello @3dmg !

It's an interesting case and I haven't seen SVG without width/height so far. It seems that absent width/height just says `100%` of whatever dimension is missing... and it's fine in HTML (element can be given an explicit size), but for us it's a bit of a problem. Currently we scale received SVG _up_ by device density, which makes SVG _responsive_, but without width/height it seems to be impossible. 

We can try rendering such SVGs without scaling, can you try this and see if it solves your problem?

```java
public class SvgPictureMediaDecoder extends MediaDecoder {

    public static final String CONTENT_TYPE = "image/svg+xml";

    @NonNull
    public static SvgPictureMediaDecoder create() {
        return new SvgPictureMediaDecoder();
    }

    @NonNull
    @Override
    public Drawable decode(@Nullable String contentType, @NonNull InputStream inputStream) {

        final SVG svg;
        try {
            svg = SVG.getFromInputStream(inputStream);
        } catch (SVGParseException e) {
            throw new IllegalStateException("Exception decoding SVG", e);
        }

        final Picture picture = svg.renderToPicture();
        return new PictureDrawable(picture);
    }

    @NonNull
    @Override
    public Collection<String> supportedTypes() {
        return Collections.singleton(CONTENT_TYPE);
    }
}
```

And usage (this will replace default SvgMediaDecoder):

```java
final Markwon markwon = Markwon.builder(context)
        .usePlugin(ImagesPlugin.create(configure -> {
            configure.addMediaDecoder(SvgPictureMediaDecoder.create());
        }))
        .build();
```

**Comment by 3dmg** [comment]
Yes, this is working. Thank you!

When you need it, here you find a big list of different SVGs, with and without the size info: https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/

**Comment by noties** [comment]
Thanks, I'm going to take a look at it and see if some generic solution can be implemented 👍

**Comment by noties** [comment]
I have added `SvgPictureMediaDecoder` into `4.2.0` release
