### ISSUE TITLE
Feature request: Support Coil image loader

### ISSUE THREAD

**Issue by ZacSweers** [noties/Markwon#166]
[Coil](https://github.com/coil-kt/coil) is a new and popular image loading library for android. It would be great if Markwon offered a first party artifact, though it may be more difficult since Coil is a Kotlin-first API

**Comment by noties** [comment]
Hello @ZacSweers !

I didn't have plans to extend a list of supported image loaders. After all there is a really cool `markwon-image` module 😉 ! But if anyone wants to implement an image loader based on Coil, I would gladly review pull request or add this artifact in the [awesome section](https://noties.io/Markwon/#awesome-markwon) (in case of independent project)

**Comment by noties** [comment]
Shipping with `4.2.0` release, thanks @tylerbwong  🙌
