### ISSUE TITLE
Crash when text is rendered

### ISSUE THREAD

**Issue by tbirn** [noties/Markwon#167]
* **Markwon version**: 3.0.0

We are experiencing a crash on Samsung Galaxy S7 devices, running Android 8 in Japanese language.

- Only this configuration seems to trigger it
- Setting the text w/o using markwon does not result in the crash.

We are trying to parse a listing like:
`* **First** line`
`* ** Second** line`

As soon as Android is trying to render the text, it crashes:
`06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: FATAL EXCEPTION: main
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: Process: [packagename], PID: 15324
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: java.lang.IndexOutOfBoundsException
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.graphics.Paint.getTextBounds(Paint.java:2975)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.text.DynamicLayout.contentMayProtrudeFromLineTopOrBottom(DynamicLayout.java:404)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.text.DynamicLayout.reflow(DynamicLayout.java:373)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.text.DynamicLayout.<init>(DynamicLayout.java:181)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.widget.TextView.makeSingleLayout(TextView.java:9164)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.widget.TextView.makeNewLayout(TextView.java:9007)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.widget.TextView.onMeasure(TextView.java:9444)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at androidx.appcompat.widget.AppCompatTextView.onMeasure(AppCompatTextView.java:501)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1619)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at androidx.constraintlayout.widget.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1212)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1552)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1502)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:556)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:733)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:95)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1556)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:803)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:733)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:805)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:899)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2881)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1911)
06-14 12:12:58.202 10300 15324 15324 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2166)
06-14 12:12:58.203 10300 15324 15324 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
06-14 12:12:58.203 10300 15324 15324 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)
06-14 12:12:58.203 10300 15324 15324 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
06-14 12:12:58.203 10300 15324 15324 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
06-14 12:12:58.203 10300 15324 15324 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:658)
06-14 12:12:58.203 10300 15324 15324 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
06-14 12:12:58.203 10300 15324 15324 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
06-14 12:12:58.203 10300 15324 15324 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
06-14 12:12:58.203 10300 15324 15324 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
06-14 12:12:58.203 10300 15324 15324 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
06-14 12:12:58.203 10300 15324 15324 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-14 12:12:58.203 10300 15324 15324 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
06-14 12:12:58.203 10300 15324 15324 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

Did you see something similar before?

**Comment by noties** [comment]
Hello @tbirn !

No, I haven't seen anything like that before. Quick search gave me 2 lonely questions without responses ([one](https://community.appybuilder.com/t/app-closes-on-android-devices-8-and-8-1/27606) and [two](https://developer.samsung.com/forum/thread/-paintgettextbounds-thows-indexoutofboundsexception-on-samsung-android-o-80/201/349467)). From them I think it's safe to assume that this is indeed a Samsung Android 8 bug. As you can see there is no mention of your application package nor Markwon's, so our hands tight. If you have such a device it might've been  easier to debug, but without such a device I'm afraid there is nothing we can do 😕 .

Just to clarify: do you use Japanese characters in your markdown? Do you use custom Typeface?

**Comment by tbirn** [comment]
Hi @noties,

it seems to be a Samsung issue, yes. And probably already solved. But there are still a lot of S7 on the market.

The markdown is in english, we are not using a custom Typeface

**Comment by noties** [comment]
Hello @tbirn !

Yeah, it's tough, but as I said, without this device (Samsung S7) on hands there is no way to fix anything. Because a fix eventually must be validated, and without the device validation is impossible.

If you 100% sure that this happens only with Japanese locale, then maybe _forcing_ English locale on that specific `TextView` with markdown can help you. But, again, without the device it is impossible to tell.
