### ISSUE TITLE
Newline breaks

### ISSUE THREAD

**Issue by adrian09h** [noties/Markwon#168]
* **Markwon version**: _4.1.0_

While setting text that has newline(s) via Markwon to EditText, I have found some issues atm.

- A single newline doesn’t show up.
```java
Markwon markwon = Markwon.builder(context)
                    .usePlugin(CorePlugin.create())
                    .usePlugin(LinkifyPlugin.create())
                    .build();
markwon.setMarkdown(myEditText, "Test\ntest");
```

![image](https://user-images.githubusercontent.com/11132956/66500551-05995280-eac2-11e9-8e9c-ffe76c18d7c0.png)

- newlines work and more than 2 newlines is ignored)
```java
markwon.setMarkdown(myEditText, "Test\n\n\n\n\ntest");
```

![image](https://user-images.githubusercontent.com/11132956/66500906-adaf1b80-eac2-11e9-88bf-5beef16f7e17.png)

If setText the strings without markwon, no issues.

It would be great to resolve the issue asap.

Thank you.

**Comment by adrian09h** [comment]
I have found a way of linebreak.

text.replaceAll("\n", "<br/>  <br/>  \n");

Thank you.

**Comment by gbhaumikkumar14** [comment]
I am also facing same issue. Any updates in this @noties ? @adrian09h  solution is hack that's last option for me.

**Comment by noties** [comment]
@Hello @gbhaumikkumar14,

this works as expected according to the commonmark spec. There are 2 kinds of line breaks - soft and hard. A soft break is a single new line character. By default it is rendered as a space. If you wish to render a new line instead of the space - use `SoftBreakAddsNewLinePlugin`:

```java
final Markwon markwon = Markwon.builder(this)
        .usePlugin(SoftBreakAddsNewLinePlugin.create())
        .build();
```

**Comment by gbhaumikkumar14** [comment]
@noties thanks for immediate response. So no need to add `Snapshot` right ?

**Comment by gbhaumikkumar14** [comment]
> @hello @gbhaumikkumar14,
> 
> this works as expected according to the commonmark spec. There are 2 kinds of line breaks - soft and hard. A soft break is a single new line character. By default it is rendered as a space. If you wish to render a new line instead of the space - use `SoftBreakAddsNewLinePlugin`:
> 
> ```java
> final Markwon markwon = Markwon.builder(this)
>         .usePlugin(SoftBreakAddsNewLinePlugin.create())
>         .build();
> ```

Works like a charm @noties  thanks Your library is making life easier.
