### ISSUE TITLE
Is there a way to get the plaintext version of a textView?

### ISSUE THREAD

**Issue by cullub** [noties/Markwon#177]
* **Markwon version**:4.2.0

I know that, given markdown, Markwon can make a textview display the formatted text (with styles, etc).  However, I'd like also to be able to take a resource in markdown and convert it to plain text, basically ignoring any formatting.  Is this possible?

**Comment by noties** [comment]
Hello @cullub !

It is possible. As Markwon uses text spans for formatting, all you have to do is remove them from rendering result:

```java
final String md = "**bold** _em_";
final Markwon markwon = Markwon.create(this);

// this has formatting
final Spanned spanned = markwon.toMarkdown(md);

// this will yield to `bold em`, as String does not hold any formatting info
final String noMd = spanned.toString();
```
