### ISSUE TITLE
Problems with Strike-through (--) and Thematic break (---)

### ISSUE THREAD

**Issue by Grimald** [noties/Markwon#178]
* **Markwon version**: _{4.2.0}_

Hi!
In the screenshots (https://noties.io/Markwon/#screenshots) and in the description I found that the library supports **Strike-through** (--) and **Thematic break** (---). 
But they work neither in my project nor in the demo.

![image](https://user-images.githubusercontent.com/14296594/69950759-028c7280-1505-11ea-9725-8984eeeba4d9.png)

I use such plugins:
![image](https://user-images.githubusercontent.com/14296594/69950119-dfad8e80-1503-11ea-9015-ea9cf090844f.png)

and artifacts:
![image](https://user-images.githubusercontent.com/14296594/69950066-be4ca280-1503-11ea-928d-74b339f13425.png)

**Comment by noties** [comment]
Hello @Grimald !

Syntax to define strike-through is `~~` and not `--`, so: `~~hello~~` will work.

A line of text with thematic break may not contain other characters. It is described in the [commonmark spec](https://spec.commonmark.org/0.29/#example-25). So, add a new line after your thematic break definition:

```
---
Hello!
```

**Comment by Grimald** [comment]
Oh, sorry. In a small screenshot I mixed up `~~` with a `--`.
Thanks for the quick response and the link to the specification. It will be possible to talk substantively with the manager :)

**Comment by Grimald** [comment]
But an online editor can do this (https://dillinger.io/):
![image](https://user-images.githubusercontent.com/14296594/69953417-3f0e9d00-150a-11ea-9bb7-c285125164ec.png)

**Comment by noties** [comment]
Well, there are a lot of different markdown implementations, so it's not a surprise. But from your screenshot I see that dillinger simply replaces `--` and `---` and `&mdash;`(&mdash;) and has nothing to do with strikethrough or thematic break 😄

**Comment by Grimald** [comment]
Yes, I agree with you. Need to understand what the customer wants and inform the manager what can be done. 
Thanks a lot!
