### ISSUE TITLE
How to use this ##Sentence

### ISSUE THREAD

**Issue by OguzhanAydin61** [noties/Markwon#179]
I want to eliminate the obligation to put a space between symbols and sentence.  ##blabla or #blabla

**Comment by noties** [comment]
Hello @OguzhanAydin61 !

There is no easy way to do it, but in specific case of a heading you can write own heading block parser, take a look at `HeadingParser` from `org.commonmark.internal` package

**Comment by Glurt** [comment]
How would we integrate a custom HeadingParser into Markwon?

**Comment by noties** [comment]
Hello @Glurt ,

You need to disable builtin heading parser in commonmark-java parser and provide your own, for example:

```kotlin
val markwon = Markwon.builder(context)
  .usePlugin(object : AbstractMarkwonPlugin() {
    override fun configureParser(builder: Parser.Builder) {
      val enabled = CorePlugin.enabledBlockTypes()
        .filter { it != Heading::class.java }
        .toSet()
      builder.enabledBlockTypes(enabled)
      builder.customBlockParserFactory(/*your block parser factory*/)
    }
  })
  .build()
```
