### ISSUE TITLE
HELP: Syntax Highlighting

### ISSUE THREAD

**Issue by preetkam** [noties/Markwon#18]
How can I automatic syntax highlighting. I checked the docs but I'm not able to figure it out, can you gimme a working example? Thanks

**Comment by noties** [comment]
Hello @preetkam ! 

There is no <em>auto</em>matic syntax highlight unfortunately. Library provides a way to plugin your own solution, but not bundled with working implementation. 

I have a plan on implementing it in future, but right now I cannot say when I will start working on it.

**Comment by preetkam** [comment]
Hey @noties !

Thanks for the quick response. I'm just asking if I can make use of a library within the syntax highlight function. Or if there's any work-around which I can use to make it work with basic syntax highlighting?

**Comment by noties** [comment]
Hey @preetkam !

There is a small document about syntaxt highlight: https://github.com/noties/Markwon/blob/master/docs/SyntaxHighlight.md

In short, you can use any existing parser/highligher, but it should return result as an Android Spannable (or you should convert a result to it)

**Comment by pramodshri** [comment]
So, it is still not clear how to use the `SyntaxHighlight` plugin. 

What I am trying to do is implement a Syntax Highlighting solution like [this](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) for python, javascript.

In the documentation site, you say :

```
Generally obtaining a Prism4j instance is pretty easy:

final Prism4j prism4j = new Prism4j(new GrammarLocatorDef());

Where GrammarLocatorDef is a generated grammar locator (if you use prism4j-bundler annotation processor)
```

I have included the annotation processor library but it is unclear how to make use of it.

Would be great if you could share an example on that.

**Comment by pramodshri** [comment]
So, I read the Prism4j documentation and added a class like below :

```
@PrismBundle(
    includeAll = true,
    grammarLocatorClassName = ".TestGrammarLocator"
)
class MyGrammarLocator {}
```

The class `TestGrammarLocator` isn't getting generated at all. Is there a way to force create the class somehow?

I am using Kotlin. I tried that on both Kotlin & Java with no luck.

**Comment by pramodshri** [comment]
So, I got this to work by changing `annotationProcessor` to `kapt`

For more details https://kotlinlang.org/docs/kapt.html
