### ISSUE TITLE
Ellipsize is not showing at the end of the text after rendering MarkDown text

### ISSUE THREAD

**Issue by mtariquekhan** [noties/Markwon#180]
* **Markwon version**: 4.2.0

I have to render markdown text into TextView but want to show ellipsis at the end If the text is more than max lines set for TextView.
I have set ellipsize="end" attribute inside TextView but it is not showing three dots at the end of the TextView after rendering the Markdown text.

Is there any workaround to do this?

**Comment by noties** [comment]
Hello @mtariquekhan !

There are few stackoverflow threads on this topic ([1](https://stackoverflow.com/questions/2160619/android-ellipsize-multiline-textview), [2](https://stackoverflow.com/questions/14691511/textview-using-spannable-ellipsize-doesnt-work)) and from them it doesn't seem that there is a definite answer. Still, you can try something like this:

```java
textView.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
    @Override
    public void onGlobalLayout() {
        textView.getViewTreeObserver().removeOnGlobalLayoutListener(this);
        final int max = textView.getMaxLines();
        final Layout layout = textView.getLayout();
        if (layout.getLineCount() > max) {
            final int end = layout.getLineEnd(max - 1);
            textView.setText(textView.getText().subSequence(0, end - 3), TextView.BufferType.SPANNABLE);
            textView.append("...");
        }
    }
});

final String text = "**Hello** there man, hello there man, hello there man, hello there man, hello there man, hello **there man**, hello there man, hello there man, hello there man, hello there man, hello there man, hello there man, hello there man";
final Markwon markwon = Markwon.create(this);
markwon.setMarkdown(textView, text);
```

**Comment by mtariquekhan** [comment]
@noties thanks for your response. It worked for me.

**Comment by noties** [comment]
You are welcome @mtariquekhan 🙌

**Comment by mtariquekhan** [comment]
@noties the above code worked for me but I am facing one issue with that code.
When the ellipsis has given to TextView inside the RecyclerView then it doesn't work properly.
When the user scrolls the list then the three dots("...") gets disappeared.

**Comment by noties** [comment]
Hello @mtariquekhan !

Unfortunately I was not able to reproduce this issue. Would you mind sharing the code that is used to bind markdown to a `TextView` in a `RecycleView.Adapter`?

**Comment by mtariquekhan** [comment]
`MarkDownParser.Builder builder = new MarkDownParser.Builder(context);
        builder.useHtmlPlugin();
        builder.useStrikeThroughPlugin();
        builder.useAbstractPlugin();
        builder.setLinkClickListener(null);
        MarkDownParser parser = builder.build();
        if (parser != null) {
            Spanned spannedMarkDown = parser.getSpannedMarkDown(markDownText);
            if (spannedMarkDown != null) {
                parser.renderMarkDown(textView, spannedMarkDown);
                textView.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
                    @Override
                    public void onGlobalLayout() {
                        textView.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                        final int max = textView.getMaxLines();
                        final Layout layout = textView.getLayout();
                        if (layout != null && layout.getLineCount() > max) {
                            final int end = layout.getLineEnd(max - 1);
                            textView.setText(textView.getText().subSequence(0, end - 3), TextView.BufferType.SPANNABLE);
                            textView.append("...");
                        }
                    }
                });
            }
        }`

Here MarkdownParser is my class which handles the Markwon instance and its functionality.

**Comment by mtariquekhan** [comment]
Hello @noties 

I think the issue is with textView.getViewTreeObserver() because getViewTreeObserver doesn't work properly inside RecyclerView. I was facing the same issue while using "https://github.com/bravoborja/ReadMoreTextView" to show "show more/show less" at the end of the TextView(If use trimMode=Lines) inside the RecyclerView.

**Comment by mtariquekhan** [comment]
MarkDownParser.Builder builder = new MarkDownParser.Builder(context);
        builder.useHtmlPlugin();
        builder.useStrikeThroughPlugin();
        builder.useAbstractPlugin();
        builder.setLinkClickListener(null);
        MarkDownParser parser = builder.build();
        if (parser != null) {
            Spanned spannedMarkDown = parser.getSpannedMarkDown(markDownText);
            if (spannedMarkDown != null) {
                parser.renderMarkDown(textView, spannedMarkDown);
                textView.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
                    @Override
                    public void onGlobalLayout() {
                        textView.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                        final int max = textView.getMaxLines();
                        final Layout layout = textView.getLayout();
                        if (layout != null && layout.getLineCount() > max) {
                            final int end = layout.getLineEnd(max - 1);
                            textView.setText(textView.getText().subSequence(0, end - 3), TextView.BufferType.SPANNABLE);
                            textView.append("...");
                        }
                    }
                });
            }
        }

**Comment by mtariquekhan** [comment]
Hello @noties

I am still facing the same issue for RecyclerView's item.
Do you have any workaround for the same?
Please see the question asked in StackOverflow ==> https://stackoverflow.com/questions/33159492/recyclerview-itemview-ongloballayoutlistener-doesnt-fire-for-all-itemviews

**Comment by noties** [comment]
Hello @mtariquekhan !

It _might be_ that setting `onGlobalLayoutListener` in `ViewHolder`'s contructor won't work because `itemView` (due to _recycling_) is attached and detached multiple times. You can apply `onAttachStateListener` for example in constructor of `ViewHolder` to register your `OnGlobalLayoutListener` on view attached and unregister it on view detached.

But. My initial answer implied that you apply `OnGlobalLayoutListener` once **directly before** setting markdown on your TextView. In `RecyclerView` context it would be - in `onBindViewHolder` method. 

* You apply `OnGlobalLayoutListener`
* You apply your markdown which triggers global layout change event
* Your `OnGlobalLayoutListener` is invoked, it does its job and it **unsubscribes** itself from receiving further layout events
