### ISSUE TITLE
Error when getting subsequence inside blockquote

### ISSUE THREAD

**Issue by Adonai** [noties/Markwon#183]
Narrowed it down to this line:

https://github.com/noties/Markwon/blob/b844f4db6c5404fd34bc2e078a584f14eb44fa00/markwon-core/src/main/java/io/noties/markwon/SpannableBuilder.java#L190

I'm pretty sure it should be `Math.min` there, can you take a look?

**Comment by noties** [comment]
Hello @Adonai !

Yes, it has caught my attention also, I had fixed that already in latest [4.2.1 snapshot](https://github.com/noties/Markwon/blob/develop/markwon-core/src/main/java/io/noties/markwon/SpannableBuilder.java#L190)

**Comment by Adonai** [comment]
Thank you
