### ISSUE TITLE
About Image custom SchemeHandler

### ISSUE THREAD

**Issue by binzhong** [noties/Markwon#185]
* **Markwon version**: _{4.2.0}_

**Hi! First of all, thank you for your work on this project! It help me a lot!**

And then I want to process the uri of image like "/path/to/image.png" and other uri not like "scheme:path", So I code my custom SchemeHandler. But unfortunately it can't work.
After debug, I found any url not like "scheme:path" won't call handler method. Source code:
```
//code file:image/AsyncDrawableLoaderImpl.java
//line:90
final String destination = asyncDrawable.getDestination();

final Uri uri = Uri.parse(destination);

Drawable drawable = null;

String scheme = uri.getScheme();
if (scheme == null
        || scheme.length() == 0) {
    throw new IllegalStateException("No scheme is found: " + destination);
}

// obtain scheme handler
final SchemeHandler schemeHandler = schemeHandlers.get(scheme);
```
Because of the reason on above, library can't surpport the uris not like "scheme:path" even custom SchemeHandler.

So, I want to suggest define a default scheme for all uri not like "scheme:path", and then custom SchemeHandler can provide the custom-handler to process any uri.
Or provide other mechanism to resolve this problem, anyway user should be able to process any uri.

If I misunderstand something, please tell me.
Thank you!

**Comment by noties** [comment]
Hello @binzhong !

Well, image module uses schemes as there is little that it can do to the images (and other resources) without proper scheme information. Most likely, when you have such images (without scheme) you are dealing with some kind of local resources (like from `assets` folder). For this case you can use the `UrlProcessorAndroidAssets` (which will turn all links and images without scheme info point to assets, for example: `/images/1.png` would become `file:///android_assets/images/1.png`)

```java
final Markwon markwon = Markwon.builder(context)
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configureConfiguration(@NonNull MarkwonConfiguration.Builder builder) {
                builder.urlProcessor(new UrlProcessorAndroidAssets());
            }
        })
        .build();
```

In general, you can introduce own `UrlProcessor` that suits you and _mock_ a scheme, which then can be handled by `SchemeHandler` (this is how `latex` extension operated before), for example:

```java
class MyUrlProcessor implements UrlProcessor {

    @NonNull
    @Override
    public String process(@NonNull String destination) {
        final Uri uri = Uri.parse(destination);
        final String scheme = uri.getScheme();
        if (TextUtils.isEmpty(scheme)) {
            return "mocked://" + destination;
        }
        return destination;
    }
}

class MySchemeHandler extends SchemeHandler {

    @NonNull
    @Override
    public ImageItem handle(@NonNull String raw, @NonNull Uri uri) {
        // handle the mocked scheme
        // you can return Drawable here with `ImageItem.withResult()`
        // or an input stream that should be further processed by a MediaDecoder
        //  with `ImageItem.withDecodingNeeded()`
        TODO()
    }

    @NonNull
    @Override
    public Collection<String> supportedSchemes() {
        return Collections.singleton("mocked");
    }
}

final Markwon markwon = Markwon.builder(context)
        .usePlugin(ImagesPlugin.create(new ImagesPlugin.ImagesConfigure() {
            @Override
            public void configureImages(@NonNull ImagesPlugin plugin) {
                plugin.addSchemeHandler(new MySchemeHandler());
            }
        }))
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configureConfiguration(@NonNull MarkwonConfiguration.Builder builder) {
                builder.urlProcessor(new MyUrlProcessor());
            }
        })
        .build();
```

The only downside that I see right now is that `UrlProcessor` processes all the URLs (both links and images). So, maybe adding a scheme fallback option would be a good addition to the `image` module after all

**Comment by binzhong** [comment]
I get it. Thank you for your help!
