### ISSUE TITLE
How to remove underline for url link

### ISSUE THREAD

**Issue by crossle** [noties/Markwon#193]
* **Markwon version**:  4.2.1

The link style always have underline, how to remove the underline for the link?

**Comment by noties** [comment]
Hello @crossle !

There are at least 2 options:
* override current styling (keep original link span)
* provide own implementation of span for links

Anyway you start by creating a new plugin:
```java
final Markwon markwon = Markwon.builder(context)
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configureSpansFactory(@NonNull MarkwonSpansFactory.Builder builder) {
                final SpanFactory original = builder.getFactory(Link.class);
                if (original != null) {
                    builder.setFactory(Link.class, (configuration, props) -> {
                        // reversed order
                        return new Object[] {
                                new RemoveUnderlineSpan(),
                                original.getSpans(configuration, props)
                        };
                    });
                }

                // or, you can provide own implementation for LinkSpan by calling:
//                builder.setFactory(Link.class, new SpanFactory() {
//                    @Nullable
//                    @Override
//                    public Object getSpans(@NonNull MarkwonConfiguration configuration, @NonNull RenderProps props) {
//                        TODO()
//                    }
//                });
            }
        })
        .build();
```

Please note that the first option needs to return spans in reversed order (added first will be processed last)

**Comment by crossle** [comment]
Coool, got it. Thanks

**Comment by noties** [comment]
UPD: in `4.2.2-SNAPSHOT` version (which should be soon available), there will be 2 new methods in `MarkwonSpansFactory`:

* `appendFactory`
* `prependFactory`

So, taking into consideration this additions, code could be rewritten as:

```java
builder.appendFactory(Link.class, (configuration, props) -> new RemoveUnderlineSpan());
```

**Comment by crossle** [comment]
@noties  BTW, RecyclerView does not support GitHub task list format ?

**Comment by noties** [comment]
@crossle Markwon supports task lists via `ext-tasklist` plugin. `RecyclerView` does not require any special handling for them to be displayed

**Comment by crossle** [comment]
@noties  OK, thanks.

**Comment by crossle** [comment]
@noties Other question, How to support text selection in RecyclerView? I add markdown item TextView add ` android:textIsSelectable` true, but it's conflict with the markdown url link.

**Comment by noties** [comment]
@crossle can you please explain the `conflict`, how is text selection conflicts with links?

**Comment by crossle** [comment]
![IMG_202016_1738_428743478](https://user-images.githubusercontent.com/1675131/74585666-09158b00-501a-11ea-8371-2ce3c4a55c21.jpeg)
I set `  android:textIsSelectable="true" `, but the url link does not click, it's just selected.

**Comment by noties** [comment]
@crossle the problem might be with the `MovementMethod`. `Markwon` will automatically apply one if it's missing _after_ markdown is applied to a TextView. And this works in most cases. Until you have text selection enabled. So here you can try setting `MovementMethod` _before_ markdown is applied:

```java
// for example in `onCreateHolder`, so this is done once per `TextView`
holder.textView.setMovementMethod(LinkMovementMethod.getInstance());

// then in `onBind` apply your markdown as usual:
markwon.setMarkdown(holder.textView, markdown);
```

**Comment by crossle** [comment]
How to set on recyclerview?

**Comment by noties** [comment]
You don't set it on RecyclerView, you set it on the TextView with markdown content inside RecyclerView
