### ISSUE TITLE
Picture display problems in mixed arrangement of pictures and texts

### ISSUE THREAD

**Issue by lhholylight** [noties/Markwon#195]
If the text content in front of the picture is too long and there is a line break, the picture will not be displayed in a new line, but will follow the text directly
![图像 1](https://user-images.githubusercontent.com/9457431/74702079-cf27cd00-5243-11ea-9e82-ea540bb91564.png)

the code:
```
        String markdown = "#### 杭州天气\n" +
                "9度，西北风1级，空气良89，相对温度73% 9度，西北风1级，空气良89，相对温度\n" +
                "![image](http://a3.att.hudong.com/68/61/300000839764127060614318218_950.jpg)\n"  +
                "##### 10点20分发布 [天气](http://www.seniverse.com/) \n";
        final Markwon markwon = Markwon.builder(this)
                .usePlugin(ImagesPlugin.create())
                .build();
        markwon.setMarkdown(textView, markdown);
```

**Comment by noties** [comment]
Hello @lhholylight !

It is working as expected according to the [commonmark markdown specification](https://spec.commonmark.org/0.29/). Here you can do:

* Use 2 new line characters (`\n\n`) before image - making it a _hardbreak_
* Make all _softbreaks_ insert a new line (#142 )

**Comment by noties** [comment]
Feel free to reopen if issue is not solved
