### ISSUE TITLE
How to toggle checkboxes in preview mode?

### ISSUE THREAD

**Issue by stefan-niedermann** [noties/Markwon#196]
Hello,
i need to toggle checkboxes in preview mode.

Is there anything i missed, like a clickhandler that returns the toggled line? Or any recommended practice?

Thank you in advance

**Comment by noties** [comment]
Hello @stefan-niedermann !

I assume you are talking about the task-list items? If so, it is possible - take a look at the [documentation](https://noties.io/Markwon/docs/v4/ext-tasklist/#task-list-mutation). Then, you'll need to modify the `ClickableSpan`:

```java
class TaskListToggleSpan extends ClickableSpan {

    private final TaskListSpan span;

    TaskListToggleSpan(@NonNull TaskListSpan span) {
        this.span = span;
    }

    @Override
    public void onClick(@NonNull View widget) {
        // toggle span (this is a mere visual change)
        span.setDone(!span.isDone());
        // request visual update
        widget.invalidate();

        // it must be a TextView
        final TextView textView = (TextView) widget;
        // it must be spanned
        final Spanned spanned = (Spanned) textView.getText();

        // actual text of the span (this can be used along with the  `span`)
        final CharSequence task = spanned.subSequence(
                spanned.getSpanStart(this),
                spanned.getSpanEnd(this)
        );

        Debug.i("task done: %s, '%s'", span.isDone(), task);
    }

    @Override
    public void updateDrawState(@NonNull TextPaint ds) {
        // no op, so text is not rendered as a link
    }
}
```

Please note that toggled line will be returned from the **rendered** markdown and not original source. So, for example given the input:

```markdown
- [ ] Not done here!
- [x] and done
- [X] and again!
* [ ] **and** syntax _included_ `code`
```

the last line would report the `and syntax included  code ` as toggled line

**Comment by stefan-niedermann** [comment]
Thank you very much. This will help a lot 🙂

**Comment by stefan-niedermann** [comment]
@noties I have some trouble with this approach and nested task items, like
```markdown
- [ ] outer
  - [ ] inner
```

When clicking on the `inner` item, then 

```java
final CharSequence task = spanned.subSequence(
    spanned.getSpanStart(this), // This seems to be always the start of the most outer item (expected to be the start of the clicked item)
    spanned.getSpanEnd(this) // This also seems to relate always to the complete "tree" - the end is *after* all nested task items of the outer task item
);
```

Maybe you can give me another hint about how to detect the actual clicked task item in a nested scenario?

**Comment by noties** [comment]
Hello @stefan-niedermann ,

this happens because nested task list is included in parent, so a parent clickable span is suppressing children. A workaround would include a _limited_ clickable span for a task list (that expands until first nested block). Most likely a custom task list visitor would be required

**Comment by noties** [comment]
Here is a [sample](https://github.com/noties/Markwon/blob/master/app-sample/src/main/java/io/noties/markwon/app/samples/tasklist/TaskListMutateNestedSample.kt) that deals with nested task lists

**Comment by stefan-niedermann** [comment]
Awesome! After porting the kotlin code to java, it works nearly out of the box :). I will provide a link to my code here once i merged it into the `master` branch.
