### ISSUE TITLE
Latex inside of markdown blockquote

### ISSUE THREAD

**Issue by adrian09h** [noties/Markwon#197]
* **Markwon version**: _{REQUIRED}_

How can I show the latex inside of blockquote?
Here is a sample string:

>$$W=W_1+W_2=F_1X_1-F_2X_2$$.

**Comment by noties** [comment]
Hello @adrian09h !

Can you please specify markwon version used and what you want to achieve exactly? What is _LaTeX inner blockquote_?

**Comment by adrian09h** [comment]
I am using Markwon latest version.
What is the LaTex inner block quote?
I will add one screenshot for that.
![IMG_7757](https://user-images.githubusercontent.com/11132956/75333198-fefb5400-5885-11ea-96c8-1a51a6881954.jpeg)

**Comment by noties** [comment]
It is not _inner block quote_, quite the opposite - outer 😄 . So you want to use LaTeX inside a markdown blockquote. Unfortunately it is not possible, as LaTeX is rendered via markdown blocks only now. But I'm working on LaTeX inlines and it is scheduled for the `4.3.0` version

**Comment by adrian09h** [comment]
Thanks
When could you release new version?

**Comment by misuti** [comment]
@adrian09h May I know how did you make the latex part dark themed?
Since I came across some difficulties in #207

**Comment by noties** [comment]
What kind of issue are you having @misuti ?

**Comment by misuti** [comment]
Trying to make black latex white

**Comment by noties** [comment]
@misuti can you show me your code? The screenshot above is not taken from Markwon, as at the time of posting there were no such functionality :) 

Additionally, you can look at [sample](https://github.com/noties/Markwon/blob/master/sample/src/main/java/io/noties/markwon/sample/latex/LatexActivity.java#L213) for the reference

**Comment by misuti** [comment]
Code to create markwon instance
```java
markwon = Markwon.builder(this)
                .usePlugin(new LineBreakPlugin())
                .usePlugin(StrikethroughPlugin.create())
                .usePlugin(SyntaxHighlightPlugin.create(new Prism4j(new MarkdownGrammarLocator()), (getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK) == Configuration.UI_MODE_NIGHT_YES ? Prism4jThemeDarkula.create() : Prism4jThemeDefault.create()))
                .usePlugin(GlideImagesPlugin.create(Glide.with(this)))
                .usePlugin(LinkifyPlugin.create(Linkify.EMAIL_ADDRESSES | Linkify.PHONE_NUMBERS | Linkify.WEB_URLS))
                .usePlugin(JLatexMathPlugin.create(JLatexMathPlugin.builder(getResources().getDimensionPixelSize(R.dimen.default_text_body_size)).align(JLatexMathDrawable.ALIGN_LEFT).build()))
                .usePlugin(new AbstractMarkwonPlugin() {
                    public void configureConfiguration(@NonNull MarkwonConfiguration.Builder builder) {
                        builder.linkResolver((view, link) -> {
                            Log.i(l, "Link clicked! link = " + link);
                            Intent browserIntent = new Intent(Intent.ACTION_VIEW, Uri.parse(link));
                            startActivity(browserIntent);
                        });
                    }
                })
                .build();
```

**Comment by noties** [comment]
@misuti the code seems to be OK. What exact issue you are experiencing?

**Comment by misuti** [comment]
It’s the dark theme of latex introduced in 4.3, hence its not really an issue now anymore 😅
