### ISSUE TITLE
Code inline background with radius corner

### ISSUE THREAD

**Issue by adrian09h** [noties/Markwon#198]
* **Markwon version**: _{REQUIRED}_

How can I make the radius corner in code line span?

**Comment by noties** [comment]
Hello @adrian09h !

It is possible, but not out-of-box. Take a look at [MarkwonCodeEx repository](https://github.com/kingideayou/MarkwonCodeEx). Please note that `MarkwonCodeEx` uses old Markwon version and unfortunately you won't be able to use it directly with the current version without modification
