### ISSUE TITLE
Lists with links are interpreted incorrectly

### ISSUE THREAD

**Issue by stefan-niedermann** [noties/Markwon#199]
* **Markwon version**:  4.2.1

```
- [ ] [A checkbox with a link](https://www.google.de)
```

is interpreted incorrectly in an `EditText`.

For the sample implemenation code you can have a look at https://github.com/stefan-niedermann/nextcloud-notes/blob/markwon/app/src/main/java/it/niedermann/owncloud/notes/android/fragment/NoteEditFragment.java#L183

![sample](https://user-images.githubusercontent.com/4741199/75279665-3c230000-580c-11ea-9432-d59b1e51b2ac.png)

**Comment by noties** [comment]
Hello @stefan-niedermann !

I've looked into the issue and found the answer - problem lies in the `LinkEditHandler` that was used in the sample application. If you look at its the source code, you will see that it checks only for the first character to be `[`. If it's not then link styling is applied from the start of the span. This can be _mitigated_ with different implementation of LinkEditHandler, for example:

```java
@Override
public void handleMarkdownSpan(
        @NonNull PersistedSpans persistedSpans,
        @NonNull Editable editable,
        @NonNull String input,
        @NonNull LinkSpan span,
        int spanStart,
        int spanTextLength) {

    final EditLinkSpan editLinkSpan = persistedSpans.get(EditLinkSpan.class);
    editLinkSpan.link = span.getLink();

    // First first __letter__ to find link content (scheme start in URL, receiver in email address)
    // NB! do not use phone number auto-link (via LinkifyPlugin) as we cannot guarantee proper link
    //  display. For example, we _could_ also look for a digit, but:
    //  * if phone number start with special symbol, we won't have it (`+`, `(`)
    //  * it might interfere with an ordered-list
    int start = -1;

    for (int i = spanStart, length = input.length(); i < length; i++) {
        if (Character.isLetter(input.charAt(i))) {
            start = i;
            break;
        }
    }

    if (start > -1) {
        editable.setSpan(
                editLinkSpan,
                start,
                start + spanTextLength,
                Spanned.SPAN_EXCLUSIVE_EXCLUSIVE
        );
    }
}
```

Beware though, that you should disable _autolinking_ of phone numbers when editing for this to work

**Comment by stefan-niedermann** [comment]
Thank you!

Sorry for the many stupid questions, but i think i will migrate the Nextcloud Notes app to this library and i am pretty new to Markwon, so i might ask some other stupid questions 😁

**Comment by noties** [comment]
It is absolutely fine and you are welcome!
