### ISSUE TITLE
Todo items

### ISSUE THREAD

**Issue by zTrap** [noties/Markwon#2]
Спасибо за великолепную библиотеку!

Вопрос вот в чём: будет ли введена поддержка `todo`-итемов?
```
 - [ ] пустой чекбокс
 - [x] заполненный чекбокс
```
  - [ ] пустой чекбокс
- [x] заполненный чекбокс

**Comment by noties** [comment]
Здравствуйте! Дело в том, что это библиотека использует [commonmark-java](https://github.com/atlassian/commonmark-java) для создания промежуточного AST дерева. На сколько я понимаю, на данный момент поддержки todo items в commonmark-java нет. Но это, в принципе, можно исправить с помощью собственного extension (как например, tables и strikethrough). Так что, поддержка, возможно, будет :)

**Comment by noties** [comment]
@zTrap можно проверить `develop`, там добавлена поддержка task lists

**Comment by zTrap** [comment]
Да, выглядит очень хорошо, спасибо :)
