### ISSUE TITLE
Use LinkifyCompat instead of Linkify

### ISSUE THREAD

**Issue by drakeet** [noties/Markwon#201]
* **Markwon version**: _4.2.2_

Hi, I am using this awesome library in my app [Pure Writer](https://play.google.com/store/apps/details?id=com.drakeet.purewriter), it works great, many thanks!

Not long ago, my app collected an ANR event, which was related to `Linkify`. And I see there is a `LinkifyCompat` provided by Google can provide better performance and support. So I would like to suggest that we switch to `LinkifyCompat` directly or provide a user configuration that can be changed to `LinkifyCompat`?

```java
/**
 * LinkifyCompat brings in {@code Linkify} improvements for URLs and email addresses to older API
 * levels.
 */
public final class LinkifyCompat {
...
```

If OK, I would be happy to create a PR for this.

**Comment by noties** [comment]
Hello @drakeet !

Sure, I think that giving an option which one to use is good idea. It can be easily added into existing `LinkifyPlugin` (with `compileOnly` dependency on `androidx.core:core` (or whichever contains the `LinkifyCompat`). If you are willing to do the PR you are very much welcome 🙌 

BTW, you have very nice looking app 😍 ! Would you mind being added to the [awesome section](https://noties.io/Markwon/#awesome-markwon) 😄 ?

**Comment by drakeet** [comment]
@noties Nice! I will send the PR, and OK & thanks for adding Pure Writer to the list.

**Comment by drakeet** [comment]
BTW, I am sending you a Google Play Redeem Code for Pure Writer Pro, so that you can try its Markdown Quick Preview feature which is powered by Markwon :p
