### ISSUE TITLE
Latex error handling

### ISSUE THREAD

**Issue by Sebastiaan-Alvarez-Rodriguez** [noties/Markwon#204]
## Problem
* **Markwon version**: _{4.2.1}_

Good day to you,

I was trying to get a listener/callback to get Latex errors back to my UI code.
This is useful, because then I can display error messages to users in the event of wrong latex code.  
The errors are caught here:
https://github.com/noties/Markwon/blob/8d3f0e908db36d4cc4517aee1d76169ec5f9593f/markwon-ext-latex/src/main/java/io/noties/markwon/ext/latex/JLatexMathPlugin.java#L278-L285
and I see there is no way to plug in an error listener. Not even by creating a child of this JLatexMathPlugin.java which overrides this part of code, as the code is annoyingly package-private/private.

You can trigger referenced code by rendering some latex like:
```
\sum_{i=0}^\infty x \cdot 0 \rightarrow \iMightNotExist{0}
```

## My question
Is there any way to get latex errors I am not yet aware of?
If so, perhaps you could update the documentation to show how.  
If not, perhaps this is a good enhancement for a future implementation?
It really is easy enough to add it to the source code for JLatexMathPlugin.java.

**Comment by noties** [comment]
Hello @Sebastiaan-Alvarez-Rodriguez !

You are right, `latex` module currently lacks error handling. I'm thinking of similar error handler to the `images` module:

```java
public interface ErrorHandler {
    @Nullable
    Drawable handleError(@NonNull String latex, @NonNull Throwable throwable);
}
```

**Comment by noties** [comment]
Latest `4.3.0-SNAPSHOT` version has it

**Comment by Sebastiaan-Alvarez-Rodriguez** [comment]
Hi, 
thanks for the quick response and code enhancement! 
I will try to use 4.3.0 and use this new feature.
