### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by adrian09h** [noties/Markwon#206]
* **Markwon version**: 4.2.2
Hi How are you?
I think it is wonderful library for markdown in Android side.
BTW, I have one question.
Does this library support the localization feature?(For example, Russian)

**Comment by noties** [comment]
Hello @adrian09h !

I'm good, how are you? `Markwon` does not make any assumptions about language used in your markup, so you should have full localization support out of box (including, but not thoughtfully tested, RTL languages)

**Comment by adrian09h** [comment]
Thanks
