### ISSUE TITLE
Click on the image. Using standard syntax, clicking does not work

### ISSUE THREAD

**Issue by lanhuaguizha** [noties/Markwon#208]
Click on the image. Using standard syntax, clicking does not work.
Like this link:
`[![markdown](https://www.mdeditor.com/images/logos/markdown.png "markdown")](https://www.mdeditor.com/images/logos/markdown.png)`

**Comment by noties** [comment]
Hello @lanhuaguizha !

Most likely the reason is `MovementMethod`. `Markwon` applies one if it is missing, but sometimes it is not enough. Can you please try setting `MovementMethod` explicitly, like this (before applying markdown):

```java
textView.setMovementMethod(LinkMovementMethod.getInstance());

final String md = "[![markdown](https://www.mdeditor.com/images/logos/markdown.png \"markdown\")](https://www.mdeditor.com/images/logos/markdown.png)";
final Markwon markwon = Markwon.builder(this)
        .usePlugin(ImagesPlugin.create())
        .build();
markwon.setMarkdown(textView, md);
```

**Comment by lanhuaguizha** [comment]
Thank you very much. It worked
