### ISSUE TITLE
A way to not add a `forceNewLine()`

### ISSUE THREAD

**Issue by c-b-h** [noties/Markwon#209]
* **Markwon version**: _4.2.2_

First of all, good job for authoring and maintaining this excellent library.
I am currently working on a library that "re-introduces" `MarkwonView` with support for providing style params in XML. I started back in version 1.x.x but haven't had the time or the need for finishing it until now. One of the things I want to achieve is to for instance parse `android:lineHeight` and apply spans based on its value but I have stumbled on an issue with dealing with `Heading`s that forcibly include line-break (not ensure but rather `forceNewLine()`). I haven't figured out how to disable this behaviour in the 4.X.X version of the library.

**Comment by noties** [comment]
Hello @c-b-h !

Long time no see 😉 !

Well, currently it is not supported with a configuration option. You _kinda_ can do it if you create own visitors for all markdown nodes, but this clearly is a not a very good option. A similar thing has been asked recently (#205) and I think it would be a good thing to be able to customize this behavior.

What I see is this:

```java
public class BlockHandlerDef implements MarkwonVisitor.BlockHandler {
    @Override
    public void blockStart(@NonNull MarkwonVisitor visitor, @NonNull Node node) {
        visitor.ensureNewLine();
    }

    @Override
    public void blockEnd(@NonNull MarkwonVisitor visitor, @NonNull Node node) {
        if (visitor.hasNext(node)) {
            visitor.ensureNewLine();
            visitor.forceNewLine();
        }
    }
}
```

**Comment by noties** [comment]
Done in `4.3.0` via `MarkwonVisitor.BlockHandler`

**Comment by c-b-h** [comment]
👍 Great, thx!
