### ISSUE TITLE
Setting text on RemoteViews doesn't work.

### ISSUE THREAD

**Issue by beatbrot** [noties/Markwon#210]
**Markwon version**: 4.2.1

I want to use markwon in conjunction with a widget. Therefore, I have to use RemoteViews and call

```java
widget.setTextViewText(R.id.widget_textview, markwon.toMarkdown(content));
```

I'd expect to get a stylized text in the widget. Instead, it is just the plaintext minus all markdown syntax elements.

This is how I configure my markwon instance:

```java
markwon = Markwon.builder(context)
            .usePlugin(StrikethroughPlugin.create())
            .usePlugin(TablePlugin.create(context))
            .usePlugin(TaskListPlugin.create(context))
            .usePlugin(HtmlPlugin.create())
            .usePlugin(ImagesPlugin.create())
            .usePlugin(LinkifyPlugin.create())
            .usePlugin(SyntaxHighlightPlugin.create(new Prism4j(new GrammarLocatorDef()), Prism4jThemeDefault.create()))
            .build();
```

**Comment by noties** [comment]
Hello @beatbrot !

Unfortunately this is true. Android supports styling `RemoteViews` with **system spans only**. As `Markwon` does not use any system spans - the result is just plat text (all styling from `Markwon` is removed). 

You _could_ use system spans instead, but they are pretty limited. For example, you will have to say goodbye to images, tables, task lists and most of the HTML. You can take a look at the [sample](https://github.com/noties/Markwon/blob/develop/sample/src/main/java/io/noties/markwon/sample/notification/NotificationActivity.java) activity with some of my investigations for a reference
