### ISSUE TITLE
How to support link #xxx in RecyclerView

### ISSUE THREAD

**Issue by crossle** [noties/Markwon#211]
* **Markwon version**: v4.2.2
How to support #xx link in markdown file
like this file
https://github.com/KristopherGBaker/TexturedMaaku/blob/master/TexturedMaakuDemo/TexturedMaakuDemo/syntax.md#overview

**Comment by noties** [comment]
Hello @crossle !

I'm sorry I do not see any `#xxx` or `#xx` links in the attached [document](https://github.com/KristopherGBaker/TexturedMaaku/blob/master/TexturedMaakuDemo/TexturedMaakuDemo/syntax.md#overview). Can you provide me with a more obvious example of those?

**Comment by crossle** [comment]
This 

Markdown: Syntax
================

*   [Overview](#overview)
*   [Philosophy](#philosophy)
*   [Automatic Escaping for Special Characters](#Automatic+Escaping+for+Special+Characters)
*   [Block Elements](#block+elements)
*   [Paragraphs and Line Breaks](#Paragraphs+and+Line+Breaks)
*   [Headers](#Headers)
*   [Blockquotes](#Blockquotes)
*   [Lists](#lists)
*   [Code Blocks](#Code+Blocks)
*   [Horizontal Rules](#Horizontal+Rules)
*   [Span Elements](#Span+Elements)
*   [Links](#links)
*   [Emphasis](#Emphasis)
*   [Code](#code)
*   [Images](#Images)
*   [Miscellaneous](#Miscellaneous)
*   [Backslash Escapes](#Backslash+Escapes)
*   [Automatic Links](#Automatic+Links)

* * *

## Overview

### Philosophy

Markdown is intended to be as easy-to-read and easy-to-write as is feasible.

**Comment by noties** [comment]
Do you mean the anchor links that allows to scroll to some content inside one document?

**Comment by crossle** [comment]
Yes

**Comment by noties** [comment]
What have you tried?

**Comment by crossle** [comment]
No any action in recyclerview markdown

**Comment by noties** [comment]
Please take a look at the [sample implementation](https://github.com/noties/Markwon/blob/master/sample/src/main/java/io/noties/markwon/sample/basicplugins/BasicPluginsActivity.java#L466)
