### ISSUE TITLE
Images does not show in the tables

### ISSUE THREAD

**Issue by IlyaGulya** [noties/Markwon#213]
* **Markwon version**: 4.2.2

1. Here's what expected:
![image](https://user-images.githubusercontent.com/668727/76698958-6e13dd80-66b9-11ea-9a76-72931368fd85.png)
Here's what I see in the app:
![image](https://user-images.githubusercontent.com/668727/76698962-766c1880-66b9-11ea-81a7-5fe47c0bc9ea.png)
2. Here's markdown (with some HTML):
```
| Before | After |
| ------ | ------ |
| <img src="/uploads/8d067fcb96c570eec856c842f830afd1/Screenshot_GitFox_20181022-234639.png" width="300"> | <img src="/uploads/694cdbb32ce80764cc51607044bb2621/Screenshot_GitFox_20181023-002910.png" width="300"> |
```
Here's how I'm creating Markwon:
```
Markwon.builder(context).apply {
    usePlugins(
        listOf(
            object : AbstractMarkwonPlugin() {
                override fun configureTheme(builder: MarkwonTheme.Builder) {
                    builder
                        .codeBackgroundColor(context.color(R.color.beige))
                }

                override fun configureConfiguration(builder: MarkwonConfiguration.Builder) {
                    builder
                        .urlProcessor(urlProcessor)
                }

            },
            GlideImagesPlugin.create(context),
            HtmlPlugin.create(),
            StrikethroughPlugin.create(),
            TablePlugin.create(context),
            TaskListPlugin.create(context),
            SimplePlugin(nodeVisitors)
        )
    )

}.build()
```

I'm trying to render this merge request https://gitlab.com/terrakok/gitlab-client/-/merge_requests/105 using this application, If you want to test it yourself (branch is mandatory): https://gitlab.com/terrakok/gitlab-client/-/tree/support/extend_markdown_support-upgrade-markwon

**Comment by IlyaGulya** [comment]
I'm trying to render this issue in the mobile app: https://gitlab.com/terrakok/gitlab-client/-/merge_requests/105

**Comment by noties** [comment]
Hello @IlyaGulya !

Please refer to the #68 issue of your own authorship.
