### ISSUE TITLE
Markwon shows images twice

### ISSUE THREAD

**Issue by IlyaGulya** [noties/Markwon#214]
* **Markwon version**: 4.2.2

1. Here's what I'm expecting to see:
![image](https://user-images.githubusercontent.com/668727/76699188-f8f5d780-66bb-11ea-8a6f-e42984dd962f.png)
But Markwon shows images twice:
![image](https://user-images.githubusercontent.com/668727/76699190-090db700-66bc-11ea-8acc-98c7ae334391.png)

2. Here's markdown:
```
An example RxJava exception: 

![test](/uploads/353e70d9828e2271502fc64de9b073e8/image.png)

The same exception with Traceur enabled:

![test](/uploads/eacdd079683411e9776a2eee40925548/image.png)
```

Here's how I'm creating Markwon:
```
Markwon
    .builder(context)
    .usePlugin(object : AbstractMarkwonPlugin() {
        override fun configureConfiguration(builder: MarkwonConfiguration.Builder) {
            val serverPath =
                Toothpick
                    .openScopes(DI.SERVER_SCOPE, "MarkdownTextView_${hashCode()}")
                    .getInstance(String::class.java, ServerPath::class.java.canonicalName)
            builder
                .urlProcessor(UrlProcessorRelativeToAbsolute(serverPath))
        }
    })
    .usePlugin(GlideImagesPlugin.create(context))
    .build()
```

I'm trying to render this merge request https://gitlab.com/terrakok/gitlab-client/-/merge_requests/254 using this application, If you want to test it yourself (branch is mandatory): https://gitlab.com/terrakok/gitlab-client/-/tree/support/extend_markdown_support-upgrade-markwon

**Comment by noties** [comment]
Hello @IlyaGulya !

This can happen when padding is used on a TextView which is used to display markdown. Try changing padding to margins or _move_ padding to parent widget (you can disable clipping on parent widget to achieve initial padding effect)

**Comment by IlyaGulya** [comment]
@noties Hi!
Thanks, that's helped!
