### ISSUE TITLE
Support for hot-pluging a plugin?

### ISSUE THREAD

**Issue by c-b-h** [noties/Markwon#217]
* **Markwon version**: _4.3.0_

I am working on a [plugin](https://github.com/c-b-h/MarkdownView/blob/master/library/src/main/java/se/ingenuity/markdownview/util/MarkdownViewPlugin.java) that allows support for parsing attributes from XML and produce spans based on the outcome. My current solution requires a new instance of `Markwon` for every `TextView` and I am wondering if there is a way of re-using a Markwon-instance for several `TextView`s by plugging in my library (which may be unique for each `TextView` instance) _before_ `setText` and pluging it out once `setText` has finished.

**Comment by noties** [comment]
Hello @c-b-h !

I see what you are trying to achieve. I now it feels like an overkill to have an individual instance of `Markwon` for each TextView when you only need to customize the `MarkwonTheme`. But I think that immutable `Markwon` is a good thing which allows the reuse of `Markwon` between multiple threads. After all I don't think there are even performance considerations to have a single `Markwon` dedicated to a TextView. Do you experience one?

**Comment by c-b-h** [comment]
Hi @noties, 
Maybe my idea is premature optimization (as I haven't experienced performance issues yet). I just find it waste of memory and possibly CPU flops to have an instance of `Markwon` per `TextView`. Obviously I could also nullify the instance after `setText` is called and possibly recreate it anew if a new call to `setText` is made later.

I have been thinking of a way of tackling this matter and might propose a PR at some point although I agree that my concerns are premature.

Thanks for reaching out.
