### ISSUE TITLE
PrecomputedTextSetterCompat makes layout jumps in RecyclerView

### ISSUE THREAD

**Issue by KirkBushman** [noties/Markwon#218]
Markwon version 4.3.0,

As someone who has a lot of TextViews on a RecyclerView, it would be nice to compute complex layout async, and so I went on to try PrecomputedTextSetterCompat, which is provided.
When doing so I noticed that my cards were jumping while scrolling fast.

Looking at the implementation you are using an Executor to do the work in the background and then setting text on a Runnable.
I imagine that when you scroll fast on a list if the time of the card appearing on the screen, is smaller than the treads returning the result to the TextView, you'll see the layout resizing.

You should use Future<>: 

    textView.setTextFuture(PrecomputedTextCompat.getTextFuture(
        commentBody, textView.textMetricsParamsCompat, null
    ))

I can help you out with a PR, if you want. 
Do you want to make another class (like PrecomputedFutureTextSetterCompat) or do you want to edit the current one?

Let me know.

PS:
You might need to bump some versions to do this, like androidx.core, I don't know if this was added at that time. Also, you could bump sdk version to 29, since you are at it.

Thanks in advance.

**Comment by noties** [comment]
Hello @KirkBushman !

Yes, currently `PrecomputedTextCompat` does not identify a `TextView` on which it operates and starts a new _precompute_ task for each call (without disposing any currently running/computing tasks). This is why text might jump or even be displayed incorrectly when used in a `RecyclerView`.

`setTextFuture` and `getTextFuture` seem to be new additions to the `androidx.core` which were not available at the moment of `PrecomputedTextCompat` implementation. Unfortunately the `setTextFuture` is a method on the `AppCompatTextView` and I cannot seem to find its counterpart in the regular `TextView`. So, it seems like an individual item like `PrecomputedFutureTextSetterCompat` is preferable. If you are willing to make a PR you very much welcome 😄

**Comment by KirkBushman** [comment]
Ok incoming :+1: 

AppCompatTextView is the base class in androidx, which all the functions in those packages referres instead of the standard framework TextView.
Maybe all views should be moved to those targeted by androidx, to make them uniform? also all Material Design Components are derived from those (es MaterialTextView > AppCompatTextView).

**Comment by noties** [comment]
You mean like changing imports in `Markwon` to use `AppCompatTextView` instead of a `TextView`? I understand that it must be the most common case nowadays. Still, I would very much prefer to have ability to use this library without `androidx.*` artifacts with notable exception of the `androidx.annotation`

**Comment by KirkBushman** [comment]
Yes, I understand, I would as well for the moment.

Keep in mind that since the bases are diverging and androidx is gaining so many features, at some points you'll kinda have to move over, so not to have a half-and-half.

**Comment by noties** [comment]
While `AppCompatTextView` is still a subclass of `TextView` I think we are fine 😄

**Comment by KirkBushman** [comment]
There ya go, boy! Take a look.
