### ISSUE TITLE
io.noties.markwon.recycler.SimpleEntry support LinkMovmentMethod

### ISSUE THREAD

**Issue by crossle** [noties/Markwon#219]
* **Markwon version**: 4.2.1

Markdown on recyclerview table have link, please SimpleEntry support click link

this.textView.setMovementMethod(LinkMovementMethod.getInstance());

**Comment by noties** [comment]
Hello @crossle !

If you look at the `SimpleEntry` source code, you will see that it is really simple implementation of `MarkwonAdapter.Entry`. And you are actually encouraged to create own subclasses to fit your needs fully
