### ISSUE TITLE
Show Markdown Text as Pure Text

### ISSUE THREAD

**Issue by misuti** [noties/Markwon#220]
* **Markwon version**: 4.3.0

### Is there a way to display markdown text as pure text instead?

For example, with this source markdown text
```markdown
**This text would be bold**,  while this text would not.
```
would usually be displayed as:
> **This text would be bold**,  while this text would not.

Let's say I don't want the text to be formatted into markdown text, but at the same time do not want to have any of the markdown syntax (** etc)

If I simply set the textview's text to the markdown text, it would be displayed as
> \*\*This text would be bold\*\*,  while this text would not.

Which is not what I want to achieve, instead, it should be
> This text would be bold,  while this text would not.

Using regex seems dirty, is there a way such as custom generated spans that don't do any markdown styling?

**Comment by noties** [comment]
Hello @misuti !

The quickest way to do so (if you are using `Markwon` anyway) is do this:

```java
final Spanned spanned = markwon.toMarkdown("**this is bold** and this is not");
// `toString` will remove all the markdown styling
textView.setText(spanned.toString());
```

Note that markdown is still parsed and rendered. But the `toString` just discards the result. If you would like to be more effective, I would advice constructing commonmark-java `Parser` and writing own `Visitor` which would bypass `Markwon` rendering altogether
