### ISSUE TITLE
Show OrderedList ListItems children letter-ordered

### ISSUE THREAD

**Issue by pintalubaf** [noties/Markwon#222]
* **Markwon version**: 4.2.2

I would like to know how can I set the children of an OrderedList as letter-ordered instead of Bullets.

Is there a way?

Thank you in advance.

**Comment by pintalubaf** [comment]
Hardest part is I need them just when they are level >1 and children of OrderedList, and not children of BulletList.

**Comment by noties** [comment]
Hello @pintalubaf !

It will be mouthful, but certainly doable. Please take a look at the [sample plugin](https://github.com/noties/Markwon/blob/develop/sample/src/main/java/io/noties/markwon/sample/basicplugins/BulletListIsOrderedWithLettersWhenNestedPlugin.java) that does just that
