### ISSUE TITLE
[Question] Header in Editor

### ISSUE THREAD

**Issue by korostenskyiHub** [noties/Markwon#223]
* **Markwon version**: _4.2.1_

Hello! I have question. 
There is an example for handling the **Bold** span inside the `EditText` in [Editor](https://noties.io/Markwon/docs/v4/editor/) docs.
How can we handle Headers?

**Comment by noties** [comment]
Hello @korostenskyiHub !

I think that headings do not need any special handling except that each heading level should have own cached span (in editor context). It would've been much more helpful though if you would explain difficulties/issues you have having headings in editor?

**Comment by korostenskyiHub** [comment]
@noties , I configure the lib like this:

```
val markwon = Markwon.builder(context)
                    .usePlugin(StrikethroughPlugin.create())
                    .build()
            val editor = MarkwonEditor.builder(markwon)
                    .useEditHandler(EmphasisEditHandler())
                    .useEditHandler(StrikeThroughHandler())
                    .useEditHandler(BlockQuoteHandler())
                    .useEditHandler(CodeHandler())
                    .useEditHandler(BoldHandler())
                    .build()
            editText.addTextChangedListener(
                    MarkwonEditorTextWatcher.withPreRender(
                            editor,
                            Executors.newSingleThreadExecutor(),
                            editText
                    )
            )
```

But, when I try to enter the h1 header `# My header` into `EditText`, its' style is not displayed.
Take a look on the screenshot.
![screenshot](https://user-images.githubusercontent.com/23141597/77630362-8f938580-6f53-11ea-8e6f-dee0e2a29425.jpg)

**Comment by noties** [comment]
Yeah, but you are not using any EditHandler that handles headings 😃

**Comment by korostenskyiHub** [comment]
Based on other handlers, I've came up with something like this:
```
class HeaderHandler(private val context: Context) : AbstractEditHandler<HeadingSpan>() {

    override fun configurePersistedSpans(builder: PersistedSpans.Builder) {
        builder.persistSpan(HeadingSpan::class.java) {
            HeadingSpan(MarkwonTheme.create(context), 1)
        }
    }

    override fun handleMarkdownSpan(
        persistedSpans: PersistedSpans,
        editable: Editable,
        input: String,
        span: HeadingSpan,
        spanStart: Int,
        spanTextLength: Int
    ) {
        MarkwonEditorUtils.findDelimited(input, spanStart, "# ")?.let { match ->
            editable.apply {
                setSpan(
                    persistedSpans.get(HeadingSpan::class.java),
                    match.start(),
                    match.end(),
                    Spanned.SPAN_EXCLUSIVE_EXCLUSIVE
                )
            }
        }
    }

    override fun markdownSpanType() = HeadingSpan::class.java
}
```

But it handles it only when we surround text with `#`. For example: `# My header #`

**Comment by noties** [comment]
That's correct, `MarkwonEditorUtils.findDelimited` works like this, it helps to find _delimited_ text which is normally represented as markdown inlines. To support heading you need a bit different approach. You can look at the [sample](https://github.com/noties/Markwon/blob/develop/sample/src/main/java/io/noties/markwon/sample/editor/HeadingEditHandler.java) for reference (mind you, it supports only 2 heading levels, but adding other should not be a problem)

**Comment by korostenskyiHub** [comment]
It works! Thank you!
