### ISSUE TITLE
Catch LaTeX Parse Exceptions

### ISSUE THREAD

**Issue by misuti** [noties/Markwon#225]
* **Markwon version**: 4.3.0

When a invalid latex is provided, the program logs this error in Logcat:
```
E/JLatexMathPlugin: Error displaying latex: `...`
    java.lang.RuntimeException: TODO
        at ru.noties.jlatexmath.awt.Font.<init>(Font.java:35)
        ..
```

From the stack trace I can't find out how to handle the error.

How do I do so?

**Comment by noties** [comment]
Hello @misuti !

I've created the issue in [jlatexmath-android#2](https://github.com/noties/jlatexmath-android/issues/2) repository to track the progress

**Comment by noties** [comment]
Hello @misuti !

Can you please share exact latex that causes the crash?

**Comment by misuti** [comment]
The LaTeX I got was
```latex
$$小明 abc$$
```
Basically there was some chinese characters in there.

**Comment by noties** [comment]
Hello @misuti !

I can reproduce this. I'm investigating the issue

**Comment by noties** [comment]
The fix is on the way, you can manually update `jlatexmath-android` dependency when it will be synced in maven central in your project:

```
implementation 'ru.noties:jlatexmath-android:0.1.2'
```
