### ISSUE TITLE
Text Node Visitor Rendering Blank

### ISSUE THREAD

**Issue by AvlWx2014** [noties/Markwon#227]
**Markwon Version: 4.3.1**

I'm attempting to use the Visitor pattern to look for text nodes after parsing that match a certain string -- `Last Updated: ` -- because the next text node is a timestamp in milliseconds, which I'd like to convert to a [DateTime](https://www.joda.org/joda-time/apidocs/index.html) for printing.

1. **Expected behavior: **

Given the Markdown:
\*Last Updated:\* 1584102783000

Render after `DateTime` conversion:
_Last Updated:_ 2020-03-13T08:33.03-4:00

**Actual Behavior:**
Nothing is rendered.

2.
Here is my `NodeVisitor` implementation:
```java
private final MarkwonVisitor.NodeVisitor<Text> visitor = new MarkwonVisitor.NodeVisitor<Text>() {
        private boolean convertFlag = false;

        @Override
        public void visit(@NonNull MarkwonVisitor visitor, @NonNull Text text) {
            String literal = text.getLiteral();
            literal = literal.trim();
            if (literal.toLowerCase().contains("last update")) {
                Log.d(TAG, "Last Update node encountered. Setting flag...");
                convertFlag = true;
            } else if (convertFlag) {
                try {
                    long millis = Long.parseLong(literal);
                    DateTime dt = new DateTime(millis, DateTimeZone.getDefault());
                    text.setLiteral(dt.toString());
                } catch (NumberFormatException nfe) {
                    String msg = String.format("%s could not be parsed in to a long", literal);
                    Log.w(TAG, msg);
                } finally {
                    convertFlag = false;
                }
            }
        }
    };
```

My Plugin impl:
```java
private final AbstractMarkwonPlugin lastUpdatedPlugin = new AbstractMarkwonPlugin() {
        @Override
        public void configureVisitor(@NonNull MarkwonVisitor.Builder builder) {
            builder.on(Text.class, visitor);
        }
    };
```

And how I build my Markwon instance:
```java
Markwon markwon = Markwon.builder(context)
                .usePlugin(prePrcoessor)
                .usePlugins(Arrays.asList(tp, sp, lastUpdatedPlugin))
                .build();
```

where `tp` is an instance of `TablePlugin`, and `sp` is an instance of `StrikethroughPlugin`.

`preProcessor` is another `AbstractMarkwonPlugin` used to sanitize newline characters.

~~I am labeling this as question, because I believe it's something I'm missing in my implementation, rather than a bug with the library.~~
I suppose I can't add labels myself, oops.

When I remove `lastUpdatedPlugin`, the text renders as expected, but with the timestamp in tact since it does not get converted by my Visitor.

**Comment by noties** [comment]
Hello @AvlWx2014 !

`NodeVisitor` is responsible to create text content based on a node received (in your case `Text`). So, instead of `text.setLiteral(dt.toString());` you should call `visitor.builder().append(literal);`

**Comment by AvlWx2014** [comment]
Awesome, thank you for the feedback! That worked. I found also that since my Text visitor touches _a lot_ of nodes I need to be sure to call `visitor.builder().append(node.getLiteral())` for every node I'm not interested in or their rendered text won't make it to the output.

**Comment by noties** [comment]
Yep, that's correct
