### ISSUE TITLE
[Question] Default Text Color + Other Theme Options

### ISSUE THREAD

**Issue by gerryfletch** [noties/Markwon#228]
* **Markwon version**: 4.3.1 // Latest as of issue creation

Is it possible to change the default colour of the rendered text?
This is my main issue, but in general I would like to update all of the theme values to be as closely aligned with say, GitHubs markdown render. That includes for example the spacing between heading text and the corresponding break.

**1. Expected Behaviour**
Able to modify default text colour as part of abstract plugin
**2. Please specify conditions/steps to reproduce**
I am customising the theme via an `AbstractMarkwonPlugin`.

Thank you for the library - it is very useful.

**Comment by noties** [comment]
Hello @gerryfletch !

There is no notion of default text color in the `MarkwonTheme` because this is configured by the `TextView` in which markdown is displayed. If you want to change text color in a plugin you can override the `beforeSetText`:

```java
final Markwon markwon = Markwon.builder(this)
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configureTheme(@NonNull MarkwonTheme.Builder builder) {
                /// customize theme
            }

            @Override
            public void beforeSetText(@NonNull TextView textView, @NonNull Spanned markdown) {
                textView.setTextColor(Color.RED);
            }
        })
        .build();
```

**Comment by gerryfletch** [comment]
Ah! That makes a lot of sense. Apologies, thank you very much!
