### ISSUE TITLE
Parent view's click event getting blocked

### ISSUE THREAD

**Issue by gbhaumikkumar14** [noties/Markwon#233]
* **Markwon version**: _4.3.1_

When i set any text using below code, **parent recyclerview item view click is not working**.

```
Markwon markwon = Markwon.builder(aViewHolder.mContext)
                    .usePlugin(StrikethroughPlugin.create())
                    .usePlugin(new AbstractMarkwonPlugin() {
                        @Override
                        public void configureParser(@NonNull Parser.Builder builder) {
                            builder.inlineParserFactory(inlineParserFactory);
                        }
                    })
                    .build();

final TextView lTextview = findViewById(R.id.textview);
markwon.setMarkdown(lTextview, aMessage);

final ConstraintLayout parent = findViewById(R.id.parent);
parent.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toast.makeText(getApplicationContext(), "Clicked on TextView", Toast.LENGTH_SHORT).show();
            }
        });
```

**Toast is not coming.**
But when i set **individual** click listener on textview than it's working normal.

**Comment by noties** [comment]
Hello @gbhaumikkumar14 !

Markwon is not applying any touch/click listeners. How do you initialize click listener for the `parent recyclerview item view`?

**Comment by gbhaumikkumar14** [comment]
I have updated the comment you can check on any parent view if you set click listener and touch textview it's not working.

**Comment by gbhaumikkumar14** [comment]
> Hello @gbhaumikkumar14 !
> 
> Markwon is not applying any touch/click listeners. How do you initialize click listener for the `parent recyclerview item view`?

I have done like this.
```
lViewHolder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toast.makeText(getApplicationContext(), "Clicked on TextView", Toast.LENGTH_SHORT).show();
            }
        });
```

**Comment by noties** [comment]
Can you confirm that it is `Markwon` issue by **not** using it? Instead apply your raw text on the `TextView` and see if it is be clickable?

**Comment by gbhaumikkumar14** [comment]
> Can you confirm that it is `Markwon` issue by **not** using it? Instead apply your raw text on the `TextView` and see if it is be clickable?

Yes i confirmed, after applying markdown only that is happening. If i remove `setMarkdown` and simple use `setText` than it's working.

**Comment by noties** [comment]
Can you try calling:

```java
textView.setMovementMethod(LinkMovementMethod.getInstance());
```

before applying markdown?

**Comment by gbhaumikkumar14** [comment]
> Can you try calling:
> 
> ```java
> textView.setMovementMethod(LinkMovementMethod.getInstance());
> ```
> 
> before applying markdown?

No Change in behavior. Still blocking click event.

**Comment by noties** [comment]
There is some weirdness around it. There are similar reports ([this](https://stackoverflow.com/questions/52081377/recyclerview-click-event-not-working) for example). And for me it doesn't work even if raw text is set (not markdown). I suggest you set your click listener on the `TextView` directly, especially if you are planning to have _parts_ of that `TextView` clickable (links)

**Comment by gbhaumikkumar14** [comment]
Can you try without **recyclerview** ?
Just create one `ConstraintLayout` and put `textview` under `ConstraintLayout`.
Now set **Click listener** on `ConstraintLayout` and put `Toast` in it..
Run and check weather you are **getting toast or not ?**

**Comment by noties** [comment]
I'm really on a tight schedule right now 😅 . But if you wish to have click listener for both parent (it has some other views) and TextView - you can apply the same listener for both of them

**Comment by gbhaumikkumar14** [comment]
> I'm really on a tight schedule right now 😅 . But if you wish to have click listener for both parent (it has some other views) and TextView - you can apply the same listener for both of them

Yeah that's last option. I have put some workaround it.

**Comment by berendn** [comment]
I'm experiencing the same issue.

**Comment by noties** [comment]
Unfortunately I do not know what can be done on our side, it seems to be a RecyclerView issue

**Comment by gbhaumikkumar14** [comment]
No, i have checked it's not`recyclerview` problem. Because when i use normal `setText` that time everything seems normal. But when i put `markwon.setMarkdown`, problem is coming.

**Comment by noties** [comment]
I guess you would be surprised to know that internally `Markwon` is also _just_ calling `textView.setText` ? 😉

**Comment by Kashish-Sharma** [comment]
Same issue here also, without `Markwon`, it works perfectly but with it, clicks are getting blocked!

**Comment by yeduRaghav** [comment]
I face the same issue

**Comment by abalta** [comment]
I have same issue. See the following code.

`    inner class ViewHolder(private val binding: ItemFastingBinding) :
            RecyclerView.ViewHolder(binding.root) {

        private val markwon = Markwon.builder(binding.root.context).usePlugin(SoftBreakAddsNewLinePlugin.create()).build()

        fun bindView(item: Protocol) {
            binding.apply {
                markwon.setMarkdown(titleFasting, item.explanation?.en?.title?.breakLine().orEmpty())
                descFasting.text = item.explanation?.en?.desc?.breakLine().orEmpty()
                setDifficulty(item.difficulty)
                itemView.click {
                    fastingItemClick(item, binding)
                }
            }
        }`

When I touch "titleFasting" view click method not trigger. But, I toucg "descFasting" view click method is trigger normally.

**Comment by berendn** [comment]
Maybe Markwon creates a clickable span or link span that consumes the click on the textview?

**Comment by Kashish-Sharma** [comment]
In my case, click event does work but the ripple animations etc, don't.

**Comment by noties** [comment]
@berendn, `Markwon` won't add link spans if there are no links in markdown, but it will apply the `LinkMovementMethod` if it is missing. Which actually **is** stealing parent touch events. So, if we **do not have links** in our markdown (@abalta), we can safely remove the movement method and everything will be ok:

```kotlin
markwon.setMarkdown(titleFasting, item.explanation?.en?.title?.breakLine().orEmpty())
titleFasting.movementMethod = null
```

This might be not optimal solution as modifying movement method rebuilds TextView display cache. I find it an oversight from `Markwon` to always apply `LinkMovementMethod`, so starting with the next version this can be controlled by using:

* configure `CorePlugin#hasExplicitMovementMethodPlugin` method (set `true` to disable implicit movement method)
* use plugin `MovementMethodPlugin#none()` factory method (which internally does the same as the first point)

---

This is all **if** your markdown doesn't have links. If you have -  it seems that you will need to additionally apply click listener on the `TextView` itself (the same listener can be used for both `itemView` and `textView`). @Kashish-Sharma I believe this is what you are doing. But there is an issue with a touch feedback (ripple animation, etc). This also could be addressed by _manually_ triggering parents background update. I've added [TriggerParentHotspot](https://github.com/noties/Markwon/blob/develop/sample/src/main/java/io/noties/markwon/sample/recycler/TriggerParentHotspot.java) in the sample application (develop branch) you can take a look. 

Using this approach would allow both widgets to be clickable (TextView can also have links) and visual feedback will still be present and consistent. It can be used like this:

```java
final View.OnClickListener listener = new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        // clicked! 
    }
};

holder.itemView.setOnClickListener(listener);
holder.textView.setOnClickListener(listener);

// this would require for parent to have background
TriggerParentHotspot.init(holder.itemView, holder.textView);
```

**Comment by premacck** [comment]
I was also facing the same issue, but I wasn't using any clickables in the text, just other forms of formatting, so I just passed the touch events from the textView to the parent like this:

```
text_view.setOnTouchListener { _, event -> parent_view.onTouchEvent(event) }
```

This way it is also giving the ripple effect from the parent click

**Comment by Shunaylov** [comment]
@premacck if I use your way I cannot handle url clicks inside TextView anymore. 
@noties I can't find TriggerParentHotspot anymore, the url is not available now

**Comment by noties** [comment]
Hello @Shunaylov ,

it was lost during sample migration, but you still can find it in [history](https://github.com/noties/Markwon/blob/94aef9934e2691e1a668dc0e7b881b520bb4030e/sample/src/main/java/io/noties/markwon/sample/recycler/TriggerParentHotspot.java)

**Comment by TamasRusvai** [comment]
How to get these information from a textView

TextView widget, Spannable buffer,
                                MotionEvent event) {
