### ISSUE TITLE
How to add click event when any markdown word clicked.

### ISSUE THREAD

**Issue by gbhaumikkumar14** [noties/Markwon#234]
* **Markwon version**: _4.3.1_

I am using library to add mentions and highlight them in messages. 
For that i have create custom plugin, custom extension, custom delimiter processor and custom node.
I am able to highlight mention in message using foreground span. 

**Example:-**

**Message**: Hello @Bhaumik1406@, How are you ?
**After Setting markdown** : Hello **@Bhaumik1406** , How are you?

Now i want to have **click listener on that highlighted mention.**

**Comment by noties** [comment]
Hello @gbhaumikkumar14 !

Well, add a `LinkSpan` with special URL that you can identify and provide own `LinkResolver`:

```java
final Markwon markwon = Markwon.builder(this)
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configureConfiguration(@NonNull MarkwonConfiguration.Builder builder) {
                builder.linkResolver(new LinkResolverDef() {
                    @Override
                    public void resolve(@NonNull View view, @NonNull String link) {
                        if (/*my link*/) {
                            // handle you link
                            return;
                        }
                        // else pass to default implementation
                        super.resolve(view, link);
                    }
                });
            }
        })
        .build();
```
