### ISSUE TITLE
How to use image loading within ListView?

### ISSUE THREAD

**Issue by iillyyaa2033** [noties/Markwon#237]
* **Markwon version**: 4.3.1
* **Glide version**: 4.11.0

I have a ListView which items are markwon-powered TextViews. (In fact, items are a bit more complex but it is not the case)

So, it looks like this -- two items for two lines of text:
![image](https://user-images.githubusercontent.com/17745136/79964468-7539c280-8493-11ea-872d-8943cbf94003.png)

ListView's attribute `transcriptMode` is set to `normal`, so "The list will automatically scroll to the bottom when a data set change notification is received and only if the last item is already visible on screen" as said in [docs](https://developer.android.com/reference/android/widget/AbsListView.html#attr_android:transcriptMode).

Let's check. 
 Initial status | When new item added | When keyboard shown
----- | ---- | ---- 
![image](https://user-images.githubusercontent.com/17745136/79965171-5e47a000-8494-11ea-8f26-bc9087a72919.png) | ![image](https://user-images.githubusercontent.com/17745136/79965256-78817e00-8494-11ea-9891-e1ce2e3c740c.png) | ![image](https://user-images.githubusercontent.com/17745136/79965299-859e6d00-8494-11ea-9c70-ed608e006c60.png)

Everything is fine -- ListView stays at its bottom.

But when text contains small square picture(s) (something like emoji) strange things occur. 

 Initial status | When new item added | When keyboard shown 
----- | ---- | ---- 
![image](https://user-images.githubusercontent.com/17745136/79965771-1ffeb080-8495-11ea-9beb-d59078c5925a.png) | ![image](https://user-images.githubusercontent.com/17745136/79966058-88e62880-8495-11ea-94b7-d526433f69c1.png) | ![image](https://user-images.githubusercontent.com/17745136/79966088-94395400-8495-11ea-881f-e18e1d4fcc99.png)

As you can see, ListView is somehow "unpinned" from its bottom position and stopped autoscroll.

I suppose it is somehow related to dimensions of loaded image because "emoji" blinks (dissapears and reappears in a single moment) when new item is added to list.

As for code, I use `GlideImagesPlugin` in that way:
```java
Markwon.Builder b = Markwon.builder(context)
.usePlugin(MovementMethodPlugin.create(ScrollingMovementMethod.getInstance()));

b.usePlugin(GlideImagesPlugin.create(new GlideImagesPlugin.GlideStore() {

    @NonNull
    @Override
    public RequestBuilder<Drawable> load(@NonNull AsyncDrawable drawable) {
        return Glide.with(context)
                .load(drawable.getDestination())
                .placeholder(emojiPlaceholder)
                .error(emojiPlaceholder)
                .fallback(emojiPlaceholder)
                .override(emojiSide, emojiSide)
                .centerCrop();
    }

    @Override
    public void cancel(@NonNull Target<?> target) {
        Glide.with(context).clear(target);
    }

}));

markwon = b.build();
```

and when it comes to `getView()` I just call markwon:
```
markwon.setMarkdown(message, text);
```

Expected behavior: listview should stay at its bottom.

**Comment by noties** [comment]
Hello @iillyyaa2033 !

I've been looking at your screenshots thinking about weird popup that you have there and how do you position it, but then I understood that it is an image 🤦 

Anyway, `ListView`. That's a thing I haven't heard of in a while. And I honestly don't think I knew that it had `transcriptMode`. So, still looking at your screenshots, I think that `transcriptMode` has nothing to do with the keyboard. Just to clarify: are you referring to the state that when `ListView` scrolled to the bottom **and then** keyboard is shown then `ListView` does no preserve it's _scrolled to bottom_ state?

**Comment by iillyyaa2033** [comment]
On the first screenshot in both cases `ListView` is in `scrolled to bottom` state. But on the second screenshot of second case (when new item is added to bottom of list) `ListView` becomes unpinned, so it wont show us latest item if we call keyboard.

But I've noticed same behavior for the items with only `ImageView` within so it might be problem somethere in my code, in glide or even in listview itself.

So I'll close this issue and reopen it only if problem surely caused by markwon itself.

**Comment by iillyyaa2033** [comment]
For anyone else facing same problem: I've set wrong emoji placeholder size. Changing placeholder's dimensions to proper ones fixed the problem.

**Comment by ubuntudroid** [comment]
@iillyyaa2033 could you elaborate? What do you mean by wrong/proper placeholder sizes?

**Comment by iillyyaa2033** [comment]
@ubuntudroid 
wrong size: placeholder height is bigger/smaller than size of actual image;
proper size: placeholder is exact tall as loaded image;

How it works: when using wrong placeholder, item changes its height after actual image been loaded that forces listview to "unpin" list from bottom of the screen.
