### ISSUE TITLE
html tags disappear

### ISSUE THREAD

**Issue by supertiger1234** [noties/Markwon#238]
* **Markwon version**: 4.3.1

1. Please specify expected/actual behavior
I want the output of 
`<owo>Hello!</owo> <strong>ok</strong>`
to be unchanged but what actually happens is the html tags get removed:
`Hello!  ok`
2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)
```
private val markwon: Markwon = Markwon.builder(applicationContext).build()
markwon.setMarkdown(messageArea, "<owo>Hello!</owo> <whatever>ok</whatever>")
```
I'm trying to make a chat app so I dont want people typing in html code.
Thanks!

**Comment by noties** [comment]
Hello @supertiger1234 !

It happens because `commonmark` _consumes_ HTML content (even without `HtmlPlugin` added to the `Markwon` instance). From security point of view - it is completely safe as all HTML content is just ignored (there is no way to execute or inject code because there is no javascript processing involved). But still it can be confusing so you have at least 2 options:

* manually pre-process user input and sanitize it (turn each `<` into `&lt;`, `>` into `&gt;`, etc)
* use an _experimental_ Markwon inline parser extension and disable parsing of HTML content all together:

```java
final Markwon markwon = Markwon.builder(this)
        .usePlugin(MarkwonInlineParserPlugin.create())
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configure(@NonNull Registry registry) {
                registry.require(MarkwonInlineParserPlugin.class, plugin -> {
                    plugin.factoryBuilder()
                            .excludeInlineProcessor(HtmlInlineProcessor.class);
                });
            }
        })
        .build();
```

**Comment by supertiger1234** [comment]
Ah, since experimental scares me, could you show me an example to do it manually? 

Also i noticed that im using this code to turn off certain im guessing "visitors" they are called? like this:
```
builder.on(Link::class.java, null);
```
but doing this converts `[Test](google.com)` into `Test` but i just want it to return `[Test](google.com) ` since i turned it off.

Thanks a lot!

**Comment by noties** [comment]
You can sanitize input before it is persisted (save in database, sent to server) or before rendering. For example here is how to do it before rendering:

```java
final Markwon markwon = Markwon.builder(this)
        .usePlugin(new AbstractMarkwonPlugin() {
            @NonNull
            @Override
            public String processMarkdown(@NonNull String markdown) {
                return markdown
                        .replaceAll("<", "&lt;")
                        .replaceAll(">", "&gt;");
            }
        })
        .build();
```

If you wish to disable links then you will have to use experimental inline parser. It is _experimental_ because it uses some internal classes from `commonmark-java` but it still passes the whole commonmark test spec, so I would say it is pretty stable

```java
final Markwon markwon = Markwon.builder(this)
        .usePlugin(MarkwonInlineParserPlugin.create())
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configure(@NonNull Registry registry) {
                registry.require(MarkwonInlineParserPlugin.class, plugin -> {
                    plugin.factoryBuilder()
                            .excludeInlineProcessor(HtmlInlineProcessor.class)
                            .excludeInlineProcessor(OpenBracketInlineProcessor.class);
                });
            }
        })
        .build();
````

**Comment by supertiger1234** [comment]
Thanks a lot! By the way, do I need to install the experimental build since It doesnt seem to find `MarkwonInlineParserPlugin`? I tried installing the snapshot but it errors out:
`ERROR: Failed to resolve: io.noties.markwon:core:4.3.1-SNAPSHOT`
```implementation "io.noties.markwon:core:4.3.1-SNAPSHOT"```

**Comment by noties** [comment]
`inline-parser` is a standalone module, you can find out how to install it [here](https://noties.io/Markwon/docs/v4/install.html) (check the `Inline Parser`)

**Comment by supertiger1234** [comment]
Ah, thanks a lot, it's working apart from a small bug. `<test></test>` works perfectly but `<test>` outputs nothing. This may be because its looking for an end tag but it cant, hmm. Would there be any way to fix this?

Thanks a lot!

**Comment by noties** [comment]
Now, this is not a bug, it is a ~~feature~~ commonmark spec. There 2 HTML in commonmark:
* inline
* block

We have disabled inline, but forgot about blocks. You still can combine _both_ approaches that I'd suggested (sanitize input and disable inline). Or disable HTML block parsing:

```java
final Markwon markwon = Markwon.builder(this)
        .usePlugin(MarkwonInlineParserPlugin.create())
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configure(@NonNull Registry registry) {
                registry.require(MarkwonInlineParserPlugin.class, plugin -> {
                    plugin.factoryBuilder()
                            .excludeInlineProcessor(HtmlInlineProcessor.class);
                });
            }

            @Override
            public void configureParser(@NonNull Parser.Builder builder) {
                builder.enabledBlockTypes(new HashSet<>(Arrays.asList(
                        Heading.class,
//                        HtmlBlock.class,
                        ThematicBreak.class,
                        FencedCodeBlock.class,
                        IndentedCodeBlock.class,
                        BlockQuote.class,
                        ListBlock.class
                )));
            }
        })
        .build();
```

**Comment by supertiger1234** [comment]
Thanks a lot! its working like a charm.

1 last question though
```.excludeInlineProcessor(OpenBracketInlineProcessor.class);```
while this code works only for link, how would i fix other disabled stuff such as `Emphasis` or `Image`?

**Comment by noties** [comment]
What do you mean by _fix_? You want to disable images and emphasis also?

**Comment by supertiger1234** [comment]
Yes, sorry that's what I meant

**Comment by noties** [comment]
Are you planning to keep _anything_ of markdown? 😄 

```java
final Markwon markwon = Markwon.builder(this)
        .usePlugin(MarkwonInlineParserPlugin.create())
        .usePlugin(MarkwonInlineParserPlugin.create())
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configure(@NonNull Registry registry) {
                // NB! `AsteriskDelimiterProcessor` and `UnderscoreDelimiterProcessor` 
                //  handles both emphasis and strong-emphasis nodes
                registry.require(MarkwonInlineParserPlugin.class, plugin -> {
                    plugin.factoryBuilder()
                            .excludeInlineProcessor(HtmlInlineProcessor.class)
                            .excludeInlineProcessor(BangInlineProcessor.class)
                            .excludeInlineProcessor(OpenBracketInlineProcessor.class)
                            .excludeDelimiterProcessor(AsteriskDelimiterProcessor.class)
                            .excludeDelimiterProcessor(UnderscoreDelimiterProcessor.class);
                });
            }

            @Override
            public void configureParser(@NonNull Parser.Builder builder) {
                builder.enabledBlockTypes(new HashSet<>(Arrays.asList(
                        Heading.class,
//                        HtmlBlock.class,
                        ThematicBreak.class,
                        FencedCodeBlock.class,
                        IndentedCodeBlock.class,
                        BlockQuote.class,
                        ListBlock.class
                )));
            }
        })
        .build();
```

**Comment by supertiger1234** [comment]
Thanks!
Emphasis was an example because I want to disable some of the other stuff. Later I'm going to add my own, such as `<:name:274757>` should convert to an emoji with the URL of `https://example.com/274757` I hope this will be possible. Thanks a lot for your help! I'll report back when I test your code above later on.

**Comment by noties** [comment]
You are welcome 🙌
