### ISSUE TITLE
Images are not being rendered

### ISSUE THREAD

**Issue by SaikrishnaRajaraman** [noties/Markwon#239]
* **Markwon version**: _4.3.1_

```
Markwon.builder(context).usePlugin(ImagesPlugin.create()).usePlugin(new AbstractMarkwonPlugin() {
                   
                    @Override
                    public void configure(@NonNull Registry registry) {
                        registry.require(ImagesPlugin.class, imagesPlugin -> imagesPlugin.addSchemeHandler(FileSchemeHandler.create()));
                    }
                })
                .build();
```

Images not being rendered

Image syntax : `![Image](file:///storage/emulated/0/Download/earth.jpg)`

**Comment by noties** [comment]
Hello @SaikrishnaRajaraman ,

your application must have required permissions to read a file from storage, do you have it?

**Comment by SaikrishnaRajaraman** [comment]
@noties It does have the required permissions.

**Comment by noties** [comment]
Good to know. I'm closing it until you provide more substantial information about this issue
