### ISSUE TITLE
Using custom fonts

### ISSUE THREAD

**Issue by Arkuda** [noties/Markwon#24]
Is it possible to use custom fonts painlessly? SpannableTheme does not represent such an opportunity. You can use the custom font, but only for blocks of code.

**Comment by noties** [comment]
Hey!

Of cause it's possible! You can change font as usual (applying it for a TextView directly)

**Comment by Arkuda** [comment]
@noties hey. What i do wrong ? 
I create TextView, render markdown to it ` Markwon.setMarkdown(textView,markdownStr);`, 
create typeface from asset `Typeface typeface = Typeface.createFromAsset(context.getAssets(), "myfont.ttf");` and apply it `textView.setTypeface(typeface);`, but typeface don't changes.

**Comment by noties** [comment]
Most likely there is some issue with loading your custom typeface.

* make sure that your custom typeface file is located in root of assets (not `raw`) folder (it can be in a nested folder, but then you have to specify it like: `Typeface.createFromAsset(getAssets(), "fonts/myfont.ttf"`)
* make sure that you have specified file name correctly
* make sure that it's valid typeface (maybe it's corrupted or something)

I have just checked setting custom typeface in the sample application and it works as expected (`Noto Serif`):
![screenshot_1515677324](https://user-images.githubusercontent.com/7278986/34827892-b5a26f8e-f6ec-11e7-84bd-74f3149644fd.png)

**Comment by Arkuda** [comment]
@noties can you show the code of sample ? Because `Typeface.createFromAsset(context.getAssets(), "myfont.ttf");` works normal and return work typeface, i use him in config `SpannableTheme.builder().codeTypeface(typeface)` to `MarkwonView`, and in `MarkwonView` some parts of text renders with this font. But only some parts.

**Comment by Arkuda** [comment]
Oh... this is problem in my code. Typeface is not setting in TextView. Sorry, its my problem. Thx, super library.

**Comment by delacrixmorgan** [comment]
Is it possible to add different custom fonts depending on which type you are?
For example.

Header - Use Font Gelica
Regular - Use Font Helvetica

**Comment by delacrixmorgan** [comment]
Alright, I've figure it out. It's actually using `AbstractMarkwonPlugin.configureTheme` to set the `headingTypeface`.
Then, I just use the conventional `TextField.style` from Android SDK to set it for the rest.

Not ideal, but workable.
```kotlin
val markwon = Markwon.builder(requireContext())
      .usePlugin(object : AbstractMarkwonPlugin() {
          override fun configureTheme(builder: MarkwonTheme.Builder) {
              val gelicaTypeface = ResourcesCompat.getFont(requireContext(), R.font.gelica_regular)
              val maisonTypeface = ResourcesCompat.getFont(requireContext(), R.font.maison_neue)
            
              builder.headingTypeface(gelicaTypeface)
          }
      }).build()
```
