### ISSUE TITLE
Animated images not resumed after scrolling

### ISSUE THREAD

**Issue by KivApple** [noties/Markwon#241]
Steps to reproduce:
1. Use Markwon RecyclerView adapter to render your Markdown document
2. Load large (to enable scrolling) Markdown document with animated images (e. g. gif)
3. Ensure that your animations are playing
3. Scroll your RecyclerView so that your animated images disappear
4. Scroll your RecyclerView back to your animated images
5. Your animated images frozen and will never play again

Expected behavior:
Animations start when they visible to a user

Reason:
setCallback2 implementation calls stop() method of Animatable instance when provided callback is null, but never calls start()

Solution:
Call start() method of Animatable instance inside setCallback2 method if provided callback is not null (may be it will be good to call start() only if callback was null before this setCallback2 method call). You also may save isRunning value of the Animatable before call stop() and call start() only if it was true if you want to support paused animations.

**Comment by noties** [comment]
Hello @KivApple ,

what image loader do you use?

**Comment by KivApple** [comment]
> Hello @KivApple ,
> 
> what image loader do you use?

I use pl.droidsonroids.gif:android-gif-drawable and OkHttpNetworkSchemeHandler

**Comment by KivApple** [comment]
UPD: There is one another problem. It is possible that RecyclerView ViewHolder will be detached from ViewGroup, but binded to Markdown node (RecyclerView creates and binds ViewHolder for one next and one previous items which is not visible on screen yet so they are not attached to ViewGroup). So when it finally attached to layout onBindViewHolder will not be called, so setCallback2 of AsyncDrawable will not be called too, just draw() will be called. I don't know good solution, but I have implemented dirty hack in my project:

I created my own plugin which handles afterSetText() and finds every AsyncDrawableSpan, than it set WeakReference to TextView on each of such Span (of coarse I created my own AsyncDrawable implementation which inherits your AsyncDrawable, but calls Animatable.start() inside setCallback2() if provided callback is not null to fix the first part of this bug). Then inside method draw() of my AsyncDrawable I check if callback is null and if it is, I call AsyncDrawableScheduler.schedule() using saved TextView weak reference. It is very dirty hack, because it is not good to call AsyncDrawableScheduler.schedule inside draw() method of the Drawable, but I don't know enough your code so it is the faster solution to implement. I hope you will fix it in more elegant way.

This is my code in Kotlin which completely fixes the bug:

```
class AnimatedAsyncDrawable(
	destination: String,
	loader: AsyncDrawableLoader,
	imageSizeResolver: ImageSizeResolver,
	imageSize: ImageSize?
): AsyncDrawable(destination, loader, imageSizeResolver, imageSize) {
	private var wasRunning: Boolean = false
	internal var textView: WeakReference<TextView>? = null
	
	override fun setCallback2(cb: Callback?) {
		if (cb == null && callback != null) {
			wasRunning = (result as? Animatable)?.isRunning == true
		}
		super.setCallback2(cb)
		if (cb != null && wasRunning) {
			(result as? Animatable)?.start()
		}
	}
	
	override fun draw(canvas: Canvas) {
		if (callback == null) {
			textView?.get()?.let {
				AsyncDrawableScheduler.schedule(it)
			}
		}
		super.draw(canvas)
	}
}

class AnimatedImageSpanFactory: ImageSpanFactory() {
	override fun getSpans(configuration: MarkwonConfiguration, props: RenderProps): Any? {
		return AsyncDrawableSpan(
			configuration.theme(),
			AnimatedAsyncDrawable(
				ImageProps.DESTINATION.require(props),
				configuration.asyncDrawableLoader(),
				configuration.imageSizeResolver(),
				ImageProps.IMAGE_SIZE[props]
			),
			AsyncDrawableSpan.ALIGN_BOTTOM,
			ImageProps.REPLACEMENT_TEXT_IS_LINK[props, false]
		)
	}
}

class AnimatedImagePlugin: AbstractMarkwonPlugin() {
	override fun configureSpansFactory(builder: MarkwonSpansFactory.Builder) {
		builder.setFactory(Image::class.java, AnimatedImageSpanFactory())
	}
	
	override fun afterSetText(textView: TextView) {
		(textView.text as? Spannable)?.getSpans(
			0, textView.text.length, AsyncDrawableSpan::class.java
		)?.forEach {
			(it.drawable as? AnimatedAsyncDrawable)?.textView = WeakReference(textView)
		}
	}
	
	companion object {
		fun create() = AnimatedImagePlugin()
	}
}
```

**Comment by noties** [comment]
Hello @KivApple ,

thank you for the detailed report. For me a GIF inside a RecyclerView is actually keeps playing, but with each _recycling_ step it seems to download the GIF resource again and start it from the start (instead of continuing from the last `pause` event). 

A view inside RecyclerView will go through attach/detach events. So, a view is detached when it is _recycled_. And before it is going to be displayed it will go through attach and then the `onBindViewHolder`. So, if you call `markwon.setMarkdown` or (better) `markwon.setParsedMarkdown` inside `onBindViewHolder` (like you should) then all `AsyncDrawables` will receive `setCallback2`. But they will start loading the thing again. And this is what happened to me. And frankly this is what you should see also 😄 

If you are interested you can look at `AsyncDrawableScheduler` which listens to attach/detach events of a `TextView` and schedules and un-schedules `AsyncDrawable`s according to event received. And while this works for _regular_ views this obviously is broken for a RecyclerView... Because some `Spanned` content might have already loaded resources and force loading these resources again is not a very good solution. If not for GIF and your report I might not even notice this behavior. 

Thanks again and let me see what can be done to fix this

**Comment by KivApple** [comment]
I understand you. I also thought that `onBindViewHolder` must be called on the already attached ViewHolder. However, I could confuse something, but the fact remains. Sometimes a situation arises when `setCallback2(null)` is called for `AsyncDrawable`, and after a while it becomes visible (the `draw()` method of `AsyncDrawable` is called) without calling `setCallback2` with a non-null argument. Perhaps this depends on the version and build of Android, but my behavior is repeated both on the real device and on the emulator. If not for this, I would not have to write all the code that I quoted above so that the animations do not stop. This is not just restarting the animation, it is just stopping it without restarting it.

So:
- `setCallback2` does not know how to start a stopped animation. It calls stop if callback is null, but never calls start. This is an obvious mistake that needs to be fixed.
- Sometimes `setCalback2` is not called with a non-null argument (in all cases, this is not its first call, and earlier it was already called first with a non-null argument, and then with null), although the TextView becomes visible (`draw()` is called on `AsyncDrawable`). I don’t know why this is happening.
