### ISSUE TITLE
Issue when delimiter's only inserted as text

### ISSUE THREAD

**Issue by gbhaumikkumar14** [noties/Markwon#242]
* **Markwon version**: _4.3.1_
See below things i am getting null when inserted # or * only in the text

input '#'      -> this should come as output `#`        -> What i am getting is   `   `  blank
input '##'    -> this should come as output `##`     -> What i am getting is   `   ` blank
input '###'  -> this should come as output `###`   -> What i am getting is   `   ` blank
input '*'       -> this should come as output `*`        -> What i am getting is   `   ` blank
input '1.'       -> this should come as output `1.`        -> What i am getting is   `   ` blank
input '>'       -> this should come as output `>`        -> What i am getting is   `   ` blank

This cases coming when user wants to just add * into text he doesn't want to do bullet.
Same thing for heading span. 

**is there any way i can handle this cases ?**

**Comment by noties** [comment]
Hello @gbhaumikkumar14 ,

I have no idea what you are talking about. There this text is inserted and what it has to do with the library?

**Comment by gbhaumikkumar14** [comment]
I have added this library into **messaging** app. Where user is sending message with only **one character '*'.** So when i show this message in chat activity message box is coming as blank. Likewise it's coming **Blank** for all above delimiters.

**Comment by noties** [comment]
Well, unfortunately this is _works-as-inteded_ kind of thing. This library is based on [commonmark specification](https://commonmark.org) with [commonmark-java](https://github.com/atlassian/commonmark-java) as parser implementation. And while I think that non-finished markdown sentences must not be turned into half-parsed results (which you see). This is how it is.

There was an issue here which I cannot find now. We have addressed this by checking if parsed markdown **is empty** and if it is -> raw markdown was used:

```java
final String input = /*markdown input*/;
final Spanned spanned = markwon.toMarkdown(input);
// or maybe `TextUtils.getTrimmedLength(spanned) == 0` in your case
if (TextUtils.isEmpty(spanned)) {
    textView.setText(input);
} else {
    markwon.setParsedMarkdown(textView, spanned);
}
```

**Comment by gbhaumikkumar14** [comment]
Yes, Now it's working.
**Enhancement**
Why can't we put this as a **setting** in library when **builder** is getting initiated. Like we can specify this as a argument or boolean so that internally when set text happen it can set correct text.
```
markwon = Markwon.builder(lContext)
                    .usePlugin(StrikethroughPlugin.create())
                    .showHalfParsed(true)
                    .build();
```

**Comment by noties** [comment]
This would be a bit problematic due to the stateless nature of parsing/rendering (and you have to memorize original markdown input). This seems like a reasonable default though, so maybe adding another `setMarkdown` method (with explicit `fallbackToRawIfEmpty` method argument) would be a better option
