### ISSUE TITLE
If TextView has padding left or right, the table is not displayed correctly

### ISSUE THREAD

**Issue by zhouzhuo810** [noties/Markwon#243]
* **Markwon version**: 4.3.1
1. Please specify expected/actual behavior

If TextView has padding left or right, the table is not displayed correctly

2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)

```xml
            <androidx.appcompat.widget.AppCompatTextView
                android:id="@+id/tv_markdown"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:lineSpacingExtra="6dp"
                android:padding="16dp"
                tools:text="yo\nman"
                android:textSize="18dp" />

```

**Comment by noties** [comment]
Hello @zhouzhuo810 ,

this is known behavior and I advised to use `margins` (or padding on parent view) before. The good news is in latest `4.4.0-SNAPSHOT` this has changed and no longer required. Can you try the `4.4.0-SNAPSHOT` version?

**Comment by zhouzhuo810** [comment]
OK, thank you, I'll try it.
