### ISSUE TITLE
Trimming few words after some characters

### ISSUE THREAD

**Issue by NitishGadangi** [noties/Markwon#246]
* **Markwon version**: 4.3.1

### Description
I am trying to set markdown to an Expandable text view using the following code
However in the textview, after 20 characters the next 14 characters replace to (...).

```XML
<com.app.util.widgets.ExpandableTextView
                    android:id="@+id/expView"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="@dimen/margin_large"
                    android:layout_marginTop="@dimen/margin_medium"
                    android:layout_marginEnd="@dimen/margin_large"
                    android:fontFamily="@font/gilroy_medium"
                    android:lineSpacingExtra="4dp"
                    android:textColor="@color/black"
                    android:textSize="16sp"
                    app:trimLength="200" />
```
```kotlin
val markWon = Markwon.builder(this)
   .usePlugin(CorePlugin.create())
   .build()
markWon.setMarkdown(expView, text)
```

### Actual behavior
![81348568-ee642700-90db-11ea-9716-5795fc8c06c3](https://user-images.githubusercontent.com/29014716/81808071-caba3a00-953c-11ea-8304-7d6db1676826.jpg)

### Expected behavior
I don't need those characters to get disappeared. I tested whether it is a fault from the ExpandableTextView class. But it is not.

**Comment by noties** [comment]
Hello @NitishGadangi ,

how exactly did you test that it is not the fault of the `ExpandableTextView`?

**Comment by NitishGadangi** [comment]
I tried setting the text directly to the ExpandableTextView and it worked well

However, when I tried to set the same text using Markwon I am facing this issue

**Comment by noties** [comment]
It seems that `ExpandableTextView` does not treat spans properly (ignores them, uses raw string for text measurements). Without source code of the `ExpandableTextView` it is hard to tell though. You should try using spannable string first to validate that idea:

```java
// the easiest solution would be to use HTML
// markup to mimic your real input
final String content = "<b>bold</b><br><br>not bold";
expandableTextView.setText(Html.fromHtml(content));
```

**Comment by noties** [comment]
@NitishGadangi do you have any update on this?

**Comment by noties** [comment]
A hint: your text content must not be _wrapped_

**Comment by aggarwalpulkit596** [comment]
@noties it was because of setting a global ellipsize attribute in app-theme
Thanks
