### ISSUE TITLE
Why the docs are so confusing? Could someone tell me how to make ~~text~~ work?

### ISSUE THREAD

**Issue by AncientTree** [noties/Markwon#249]
Because `~~text~~` dosen't work in so called Quick One leading:
``` java
// obtain an instance of Markwon
final Markwon markwon = Markwon.create(context);

// set markdown
markwon.setMarkdown(textView, "**Hello there!**");
```
I don't know whether I made a mistake or I don't do enough job in my code. (Since docs never tell out the function of sample codes). I guess I need add next codes in order to make Strikethrough work.
``` java
final Markwon markwon = Markwon.builder(context)
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configureParser(@NonNull Parser.Builder builder) {
                // no need to call `super.configureParser(builder)`
                builder.extensions(Collections.singleton(StrikethroughExtension.create()));
            }
        })
        .build();
```
Anyone tell me what is `StrikethroughExtension` come from??

I follow the link go to [](https://github.com/atlassian/commonmark-java/) and add this lines into my `build.gradle(app)`
``` xml
implementation "com.atlassian.commonmark:commonmark-ext-gfm-strikethrough:0.14.0"
implementation "com.atlassian.commonmark:commonmark:0.14.0"
```
after what `StrikethroughExtension` is still `Cannot Resolve`. This really bring me down. 😭

**Comment by AncientTree** [comment]
Moreover, there are soooo many Classes reported `Cannot resolve symbol 'XXXXXXX'`, Why?
Why this happened?

**Comment by AncientTree** [comment]
`Cannot resolve symbol 'MarkwonInlineParserPlugin'`
`Cannot resolve symbol 'JLatexMathPlugin'`
Where is them come from?

**Comment by AncientTree** [comment]
The docs are really strange.

**Comment by noties** [comment]
Hello @AncientTree ,

the docs are confusing, eh? So, you copy code from documentation and nothing happens 😱? What the hell 🤬 ! This is madness 🤯 !!

**Comment by AncientTree** [comment]
Sorry for bothering.

**Comment by noties** [comment]
Listen, open [getting started](https://noties.io/Markwon/docs/v4/core/getting-started.html#quick-one). The very first thing is the [install section](https://noties.io/Markwon/docs/v4/install.html). Open it. Pick `core` and `strikethrough`. It will even generate build.gradle dependencies section for you. Scroll down a bit if it's not visible right away. Add it to your project. Now, pick [strikethrough extension](https://noties.io/Markwon/docs/v4/ext-strikethrough/) from the sidebar. Follow the very first sample code:

```java
Markwon.builder(context)
    .usePlugin(StrikethroughPlugin.create())
```

Man, how confusing is that? It's basics. Copying unrelated code snippets (even containing some words you are interested in) creates confusion. Please stop doing that

**Comment by AncientTree** [comment]
> Listen, open [getting started](https://noties.io/Markwon/docs/v4/core/getting-started.html#quick-one). The very first thing is the [install section](https://noties.io/Markwon/docs/v4/install.html). Open it. Pick `core` and `strikethrough`. It will even generate build.gradle dependencies section for you. Scroll down a bit if it's not visible right away. Add it to your project. Now, pick [strikethrough extension](https://noties.io/Markwon/docs/v4/ext-strikethrough/) from the sidebar. Follow the very first sample code:
> 
> ```java
> Markwon.builder(context)
>     .usePlugin(StrikethroughPlugin.create())
> ```
> 
> Man, how confusing is that? It's basics. Copying unrelated code snippets (even containing some words you are interested in) creates confusion. Please stop doing that

Thanks you very much! It is very helpful.
Thanks you.

**Comment by zarksalman** [comment]
I have already followed as you describe above but ~~strike~~ is not working, here is my code,
Depandency:    implementation 'io.noties.markwon:ext-strikethrough:4.0.0;'
Code: 
        val markwon = Markwon.create(itemView.context)
        Markwon.builder(itemView.context)
                .usePlugin(StrikethroughPlugin.create())
        markwon.setMarkdown(itemView.group_msg_tv, dataItem.text!!)

**Comment by noties** [comment]
Hello @zarksalman ,

you create 2 `Markwon` instances but discard the second one (which has strike through initialied). Your code should be:

```kotlin
val markwon = Markwon.builder(itemView.context)
  .usePlugin(StrikethroughPlugin.create())
  .build()
markwon.setMarkdown(itemView.group_msg_tv, dataItem.text!!)
```

**Comment by zarksalman** [comment]
Great, thanks for the instant response. It works.
