### ISSUE TITLE
How can i get clicked link title (clicked text) on it's click event.

### ISSUE THREAD

**Issue by gauranggoda** [noties/Markwon#251]
* **Markwon version**: 4.3.1

-I have markdown text in which I have multiple links ex. [Title-1](link-1) [Title-2](link-2) [Title-3](link-3). 
-On the click event, I am only getting the link not the title. Is there a way to get the title on click event?

```
override fun configureConfiguration(builder: MarkwonConfiguration.Builder) {
                        builder.linkResolver { view, link -> 
                       **// want title here**
                           startWeb(link, "")
                        }
                    }
```

**Comment by noties** [comment]
Hello @gauranggoda,

`title`, do you mean the text of the link (in your case `Title-1`) or actual [markdown titles](https://spec.commonmark.org/0.28/#link-title)?

**Comment by noties** [comment]
https://github.com/noties/Markwon/blob/develop/sample/src/main/java/io/noties/markwon/sample/core/CoreActivity.java#L225

**Comment by amar-w** [comment]
Hi @noties, it's an old issue but just wanted to add a comment here - that link isn't working. 

e.g. `[title](link)`

Also, just like @gauranggoda I am also trying to find a way to get the `link + title` of the clicked markdown hyperlink together (at the same time) when it is clicked.

I can get the `link` in resolver and `title` with span but I am not able to get them together at one place.

**Comment by noties** [comment]
Hello @amar-w ,

the sample moved a little - [it is here now](https://github.com/noties/Markwon/blob/master/app-sample/src/main/java/io/noties/markwon/app/samples/LinkTitleSample.java#L28)

Take a look at `ClickSelfSpan`, it achieves what you are looking for. Please note that you need to specify this span for the `Link` markdown node. Then, in `onClick`:

``` java
  @Override
  public void onClick(View widget) {
    final String link = getLink();
    // can be styled, call `.toString` to clear formatting
    final CharSequence title = linkTitle(widget);
    // do something with link and title
  }
```
