### ISSUE TITLE
Embed YouTube

### ISSUE THREAD

**Issue by PXNX** [noties/Markwon#252]
* **Markwon version**: 4.4.0
Not an issue, but a question:
Is it possible to embed YouTube-Videos in some way?
Let's say {yt:VIDEO-ID} or so?

**Comment by noties** [comment]
Hello @PXNX ,

there are multiple options to do so, but no ready solution yet. A possible solution would involve displaying a youtube video thumbnail and handle click on it to start video playback in another widget/screen

**Comment by Adonai** [comment]
```
[![Embedded YouTube video](https://img.youtube.com/vi/${video_id}/0.jpg)](https://www.youtube.com/watch?v=${video_id})
```

**Comment by PXNX** [comment]
@Adonai does that work?

**Comment by Adonai** [comment]
@PXNX yes
