### ISSUE TITLE
Tooltip support or plugin

### ISSUE THREAD

**Issue by Strikerlulu** [noties/Markwon#253]
Could you add a tooltip extensions or something like that which would be more interactive and helpful...

**Comment by noties** [comment]
Hello @Strikerlulu ,

what kind of tooltip you have in mind? Do you have any example?

**Comment by Strikerlulu** [comment]
There many libraries this is one of them...
https://github.com/sephiroth74/android-target-tooltip

**Comment by noties** [comment]
Hello @Strikerlulu ,

and how do you see a tooltip representation in markdown syntax?

**Comment by Strikerlulu** [comment]
I didn't think about it:sweat_smile:...i thought you would chose a perfect one
```
{!tooltip!}(An element of a graphical user interface in the form of a box of text that appears when a cursor is made to hover over an item; normally used to explain the function of the item.) 
```

Use anything that seems better for you and sorry if the syntax is stupid as i don't have much knowledge

**Comment by noties** [comment]
Hello @Strikerlulu ,

I've made a simple showcase for tooltip support that can show you a possible way of action - [here](https://github.com/noties/Markwon/blob/develop/sample/src/main/java/io/noties/markwon/sample/inlineparser/InlineParserActivity.java#L265). 

In short the main problem to solve is to find actual position of text on the screen. When you have it you can show whatever you want with proper anchor
