### ISSUE TITLE
Task list in Markwon's Recycler

### ISSUE THREAD

**Issue by Dai1678** [noties/Markwon#254]
* **Markwon version**: 4.3.1

Hi, thanks for the great library!
I have a question about the task list.

I'm trying to display markdown text using Markwon's Recycler.
https://noties.io/Markwon/docs/v4/recycler/

I was able to display a lot of text correctly, but task list doesn't seem to be displaying well!
When I didn't use Recycler, the task list showed up correctly.

This is also happening in the sample project.
|sample project|Recycler's sample project|
|---|---|
|<img src="https://user-images.githubusercontent.com/19250035/83345017-311ac700-a349-11ea-89a4-fd1491d1c294.png" width=300>|<img src="https://user-images.githubusercontent.com/19250035/83345012-2ceea980-a349-11ea-8b9d-7e5a1ce2bf88.png" width=300>|

Do you have any plans to fix this problem?
I'm sorry for my poor English.
Thank you.

**Comment by noties** [comment]
Hello @Dai1678 ,

task lists are implemented as a standalone plugin. Please navigate to the [install section](https://noties.io/Markwon/docs/v4/install.html) and pick `Task List` which will generate proper `build.gradle` dependencies block. Then you can inspect the [dedicated page](https://noties.io/Markwon/docs/v4/ext-tasklist/) for the task list plugin. Finally, there is a [sample activity](https://github.com/noties/Markwon/blob/master/sample/src/main/java/io/noties/markwon/sample/tasklist/TaskListActivity.java) which demonstrates the usage of the task lists
