### ISSUE TITLE
Hashtag span?

### ISSUE THREAD

**Issue by premacck** [noties/Markwon#256]
* **Markwon version**: _{4.4.0}_

Thanks for this awesome library. My life became so much easier after I wasted 2 days trying to handle bullet points, numbered lists, tables and whatnot manually 😅 

However, earlier in my manual parsing, I was adding hashtag parsing (making text bold with some color) to any word preceded by # (without spaces), like "#someWord"

Is there any way to add these custom spans to the already existing markdown text?
I'm using the following code to set the markdown:

```
var TextView?.markdownText: String?
  @Deprecated(NO_GETTER, level = DeprecationLevel.ERROR) get() = noGetter()
  set(value) {
    this?.let { textView ->
      Markwon.builder(context)
        .usePlugin(StrikethroughPlugin.create())
        .usePlugin(object : AbstractMarkwonPlugin() {

          override fun configureConfiguration(builder: MarkwonConfiguration.Builder) {
            builder.linkResolver { view, link ->  }
          }

          override fun configureTheme(builder: MarkwonTheme.Builder) {
            builder
              .linkColor(Color.parseColor(ACCENT_BLUE_COLOR))
              .bulletWidth(dip(4))
              .bulletListItemStrokeWidth(dip(1))
              .listItemColor(Color.parseColor("#DE2F2F2F"))
              .blockMargin(dip(20))
          }
        })
        .usePlugin(TablePlugin.create {
          it.tableBorderWidth(dip(1))
          it.tableBorderColor(Color.parseColor("#E5E5E5"))
          it.tableCellPadding(dip(4))
        })
        .build().let { markwon ->
          val markdown = markwon.toMarkdown(value.orEmpty())
          markwon.setParsedMarkdown(textView, markdown)
        }
    }
  }
```

And this is my hashtag parsing function:

```
  private fun SpannableStringBuilder.withHashTagHandling(): SpannableStringBuilder = apply {
    if (isEmpty()) return this
    Pattern.compile("""#[A-Za-z0-9!]*""").matcher(this)?.let { matcher ->
      while (matcher.find()) {
        matcher.group(0)?.let { hashTagString ->
          setSpan(StyleSpan(Typeface.BOLD), matcher.start(), matcher.end(), SPAN_EXCLUSIVE_EXCLUSIVE)
          setSpan(ForegroundColorSpan(colorCode), matcher.start(), matcher.end(), SPAN_EXCLUSIVE_EXCLUSIVE)
          setSpan(RelativeSizeSpan(1.1F), matcher.start(), matcher.end(), SPAN_EXCLUSIVE_EXCLUSIVE)
        }
      }
    }
  }
``` 

I search around in the wiki regarding hashtags, but couldn't find anything, can you please guide me if there is a way to add the spans while setting the text?

**Comment by premacck** [comment]
For now I'm using a workaround:
```
Markwon.builder(context)
//...
    .build().let { markwon ->
          val markdown = markwon.toMarkdown(value.orEmpty())
          val span = SpannableStringBuilder.valueOf(markdown)
          span.withHashTagHandling()
          markwon.setParsedMarkdown(textView, span)
     }
```

If there is a better way to approach this, please suggest

**Comment by noties** [comment]
Hello @premacck ,

there are multiple options available:
* [inline parsing](https://github.com/noties/Markwon/blob/master/sample/src/main/java/io/noties/markwon/sample/customextension2/CustomExtensionActivity2.java#L80) which relies on _experimental_ [inline-parser](https://github.com/noties/Markwon/tree/master/markwon-inline-parser) artifact
* [text processing](https://github.com/noties/Markwon/blob/master/sample/src/main/java/io/noties/markwon/sample/customextension2/CustomExtensionActivity2.java#L65) which does not rely on additional artifacts

**Comment by premacck** [comment]
Oh so should I create a separate custom plugin for hashtags?

**Comment by noties** [comment]
You actual parser should be implemented inside your `OnTextAddedListener`, which in turn can be placed inside a plugin for better encapsulation/isolation

**Comment by premacck** [comment]
Okay so this is what I've implemented:

My `HashtagTextAddedListener`:
```
  private class HashtagTextAddedListener : CorePlugin.OnTextAddedListener {

    private val hashtagPattern = Pattern.compile("""#[A-Za-z0-9!]*""")

    override fun onTextAdded(visitor: MarkwonVisitor, text: String, start: Int) {
      hashtagPattern.matcher(text)?.let { matcher ->
        while (matcher.find()) {
          SpannableBuilder.setSpans(
            visitor.builder(), arrayOf(StyleSpan(Typeface.BOLD), ForegroundColorSpan(Color.parseColor(ACCENT_BLUE_COLOR)), RelativeSizeSpan(1.1F)), matcher.start(), matcher.end()
          )
        }
      }
    }
  }
```

And I'm applying this in the `configure` method like this:
```
    override fun configure(registry: MarkwonPlugin.Registry) {
      registry.require(CorePlugin::class.java) {
        it.addOnTextAddedListener(HashtagTextAddedListener())
      }
    }
```

This approach is working, but can it be further improved?

**Comment by noties** [comment]
There is always room for improvement, but I find your implementation pretty solid
