### ISSUE TITLE
ImageSpan with BitmapDrawable

### ISSUE THREAD

**Issue by bastienleonard** [noties/Markwon#258]
* **Markwon version**: _4.4.0_

1. Please specify expected/actual behavior
2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)

In the process of adding support for a custom HTML tag, I saw that `ImageSpan` doesn't seem to work with a bitmap.

Example:

```kotlin
builder.on(HtmlBlock::class.java) { visitor, htmlBlock ->
    val length = visitor.length()
    visitor.visitChildren(htmlBlock)

    // This is needed for some reason
    visitor.builder().append(" ")

    val bitmap = BitmapFactory.decodeResource(context.resources, R.drawable.test)
    val drawable = BitmapDrawable(context.resources, bitmap)
    val span = ImageSpan(drawable)

    // This works fine:
    // val span = ImageSpan(context, R.drawable.test)

    visitor.setSpans(length, span)
}
```
Is there any solution or approach that you would recommend?

My goal is to add support for base64 images embedded in the markdown (that's about the opposite of what Markdown was intended for, I know).

**Comment by noties** [comment]
Hello @bastienleonard ,

I think you need to explicitly set bounds on the `BitmapDrawable`. For example, you can use `DrawableUtils.applyIntrinsicBounds` utility method that comes with `Markwon` before creating `ImageSpan`.

I know you are trying things out, but applying an `ImageSpan` for a `HtmlBlock` will completely replace all HTML block content. If you have a specific HTML tag in mind it is better to use `TagHandler` which comes with `html` artifact. If you want just images that are base64 encoded, you can look at the `image` artifact that comes with support for base64 encoded images (you can look at the [documentation](https://noties.io/Markwon/docs/v4/image/#dataurischemehandler))

**Comment by bastienleonard** [comment]
Thanks, it's great to know base64 decoding is already provided!
