### ISSUE TITLE
GlideImagesPlugin bug

### ISSUE THREAD

**Issue by achenglike** [noties/Markwon#259]
* **Markwon version**: 4.4.0

The markwon-image-glide module -> GlideImagesPlugin.java -> public static GlideImagesPlugin create(@NonNull final Context context) : this method use context to create new RequestManager when called  method (**public void cancel(@NonNull Target<?> target)**)  case by OnAttachStateChangeListener(in AsyncDrawableScheduler.java) called onViewDetachedFromWindow -> unschedule(@NonNull TextView view).

In this condation maybe the Activity allready destroied before **public void cancel(@NonNull Target<?> target)** called, and glide will throw exception "You cannot start a load for a destroyed activity"

**Comment by noties** [comment]
Hello @achenglike ,

is this a confirmed crash or you are just anticipating one?

**Comment by achenglike** [comment]
> Hello @achenglike ,
> 
> is this a confirmed crash or you are just anticipating one?

Yes, a confirmed crash. AppCompatActivity->Fragment->RecycleView->TextView(use Markwon).Accidental appearance. I just change:
```
    @NonNull
    public static GlideImagesPlugin create(@NonNull final Context context) {
        return create(new GlideImagesPlugin.GlideStore() {
            @NonNull
            @Override
            public RequestBuilder<Drawable> load(@NonNull AsyncDrawable drawable) {
                return Glide.with(context)
                        .load(drawable.getDestination());
            }

            @Override
            public void cancel(@NonNull Target<?> target) {
                Glide.with(context)
                        .clear(target);
            }
        });
    }
```

to 

```
    @NonNull
    public static GlideImagesPlugin create(@NonNull final Context context) {
        return create(Glide.with(context));
    }
```

**Comment by noties** [comment]
It seems that calling `Glide.with(context)` in `cancel` method would cause crash here. Meanwhile reusing the instance of `Glide.with(context)` would not
