### ISSUE TITLE
Support for Extending Markdown Syntax

### ISSUE THREAD

**Issue by rachel-church** [noties/Markwon#26]
Is there any support for adding custom markdown rules? Such as adding in logic to understand `@material-icons-home` to mean inserting an icon from material icons? http://google.github.io/material-design-icons/#icons-for-android

A sample repo of doing this for a markdown parser for web is here:
https://github.com/dbtek/showdown-icon

**Comment by noties** [comment]
Hello! 

It's definitely doable and I had started writing _how_ to do it. But an answer became too big and I decided to shape it as something more. I think I will just add a `sample-custom-extension` module to the project in the next few days. Please ping me if I won't hold my word 😄 

(Spoiler alert): yes, a relatively big amount of code is required, including writing parser extension for the [commonmark-java](https://github.com/atlassian/commonmark-java)

**Comment by noties** [comment]
Well, as I have said, now there is a `sample-custom-extension` module that you can use as a reference when applying various customizations to markdown parsing. Please tell me if it's clear enough 🙌

**Comment by classTC** [comment]
@noties hi, thanks Markwon, it's very cool and the code is beautiful! now I have a problem, and I need your help

I had try the `sample-custom-extension` and use it in my project, it works when I use one custom mark, I try to use two custom marks, but the result parsed was repeated，my code is:
```
 private val parser = Parser.Builder()
            .extensions(Arrays.asList<Extension>(
                    StrikethroughExtension.create(),
                    TablesExtension.create(),
                    TaskListExtension.create()
            ))
            .customDelimiterProcessor(AtMemberProcessor.create())// custom mark processor
            .customDelimiterProcessor(AtGroupProcessor.create())// custom mark processor
            .build()

    // suppose input is "@Hello@ Beautiful #World#"
    fun parse(context: Context, gId: String, input: String): CharSequence {
        val config = SpannableConfiguration.create(context)
        val node = parser.parse(prepare(input))
        val builder = SpannableBuilder()
        // builder text is: null
        node.accept(CustomVisitor(config, builder, AtGroupSpanProvider(gId)))
        // builder text is: Hello Beautiful #World#
        node.accept(CustomVisitor(config, builder, AtMemberSpanProvider()))
        // builder text is: Beautiful\n\n Hello Beautiful World  
        return builder.text()
    }
```

I did some refactor from `sample-custom-extension`'s code, extrc the CustomVisitor, so it looks like a little difference, hope you can understand what the code show.

so my question is how to apply various customizations?

**Comment by noties** [comment]
Hello @classTC ! Thanks for your feedback!

The thing here is simple: you traverse the parsed node twice (`node.accept()`), thus duplicating content (the same `SpannableBuilder` is used). To solve it: merge your functionality into one visitor, something like that:

```java
@Override
public void visit(CustomNode customNode) {
    if (!visitAtMemberNode(customNode) && !visitAtGroupNode(customNode)) {
        super.visit(customNode);
    }
}
```

This is due to the fact, that _visiting_ in Markwon is actually used to construct Spannables. So, after the first `accept` call `SpannableBuilder` will contain the whole text (plus `AtGroup`). The second call will append to the `SpannableBuilder` the whole text plus `AtMember`. 

Hope this helps!

**Comment by classTC** [comment]
@noties Thank you very much!  it works!
