### ISSUE TITLE
How to use custom plugin to implement Read more... and Read less... functionality on Text view

### ISSUE THREAD

**Issue by gbhaumikkumar14** [noties/Markwon#260]
* **Markwon version**: _{4.3.1}_

I want to implement **Read more...** and **Read less...** functionality same as **Whatsapp**. I have text view and i am already using markwon to set text inside text view.

I need help on how can i use custom plugin to set **Read more...** text after defined number of lines and when user presses read more... it should add remaining text and **Read less...** at the end.

![Read more](https://user-images.githubusercontent.com/30618885/84006503-7748d980-a98c-11ea-820a-21071930b222.png)

**Comment by noties** [comment]
Hello @gbhaumikkumar14 ,

I do not think that it is possible to implement this feature solely on `Markwon` side (via plugin). This functionality must be included in your text widget directly. And there are multiple options available if you look for them as `ExpandableTextView` or even `ReadMoreTextView`. Have you tried them?

**Comment by gbhaumikkumar14** [comment]
@noties Thank you for answering. I was wondering if it's possible with custom plugin. Because Read More Text View is doing same thing like cutting out lines and adding spanned string with ...Read more text.

**Comment by noties** [comment]
Hello @gbhaumikkumar14 ,

in order for a widget to support `Markwon` all dynamic (images and tables) spans must be available immediately after `setText` call. As I remember your widget is creating short representation of full text immediately, which effectively disables all dynamic content. There are multiple workarounds possible, for example _postpone_ creation of short text until next `draw` layout events, something like this:

```java
@Override
public void setText(CharSequence text, BufferType type) {
    super.setText(text, type);
    getViewTreeObserver().addOnPreDrawListener(new ViewTreeObserver.OnPreDrawListener() {
        @Override
        public boolean onPreDraw() {
            /*init short/full here*/
            // NB! don't fall in recursive loop here, set text with `super.`
            getViewTreeObserver().removeOnPreDrawListener(this);
            return true;
        }
    });
}
```

On the other hand, you can indeed have this functionality provided via plugin. It is all really specific to a application, so adjust to your own needs. You can find it [here](https://github.com/noties/Markwon/blob/develop/sample/src/main/java/io/noties/markwon/sample/basicplugins/ReadMorePlugin.java)

**Comment by gbhaumikkumar14** [comment]
@noties Thanks you so much. I will check this.

> Hello @gbhaumikkumar14 ,
> 
> in order for a widget to support `Markwon` all dynamic (images and tables) spans must be available immediately after `setText` call. As I remember your widget is creating short representation of full text immediately, which effectively disables all dynamic content. There are multiple workarounds possible, for example _postpone_ creation of short text until next `draw` layout events, something like this:
> 
> ```java
> @Override
> public void setText(CharSequence text, BufferType type) {
>     super.setText(text, type);
>     getViewTreeObserver().addOnPreDrawListener(new ViewTreeObserver.OnPreDrawListener() {
>         @Override
>         public boolean onPreDraw() {
>             /*init short/full here*/
>             // NB! don't fall in recursive loop here, set text with `super.`
>             getViewTreeObserver().removeOnPreDrawListener(this);
>             return true;
>         }
>     });
> }
> ```
> 
> On the other hand, you can indeed have this functionality provided via plugin. It is all really specific to a application, so adjust to your own needs. You can find sample implementation [here](https://github.com/noties/Markwon/blob/develop/sample/src/main/java/io/noties/markwon/sample/basicplugins/ReadMorePlugin.java)

**Comment by gbhaumikkumar14** [comment]
Depanding in `addOnPreDrawListener` is not consistent when text view is in RecyclerView item viewHolder. Going by character in [this](https://github.com/noties/Markwon/blob/develop/sample/src/main/java/io/noties/markwon/sample/basicplugins/ReadMorePlugin.java) looks fine.

**Comment by gbhaumikkumar14** [comment]
@noties [ReadMorePlugin](https://github.com/noties/Markwon/blob/develop/sample/src/main/java/io/noties/markwon/sample/basicplugins/ReadMorePlugin.java) works like a charm.

**Comment by noties** [comment]
Glad we had sorted this out 👍
