### ISSUE TITLE
sample LinkEditHandler causing parse/text-color issues

### ISSUE THREAD

**Issue by mr-spod** [noties/Markwon#262]
* **Markwon version**: core:4.4.0, editor:4.4.0

Expected behavior: display link description as it would be in rendered markdown, with the `[` `](www.google.com)` portion highlighted same as the delimiters for bold, italics, etc.

Actual behavior: strange/incorrect delimiter highlighting when text is entered after the link.

screenshots:

![Screenshot_1593022615](https://user-images.githubusercontent.com/22305270/85614513-f3981980-b628-11ea-9768-4babe32f0108.png)

![Screenshot_1593022652](https://user-images.githubusercontent.com/22305270/85614679-1fb39a80-b629-11ea-9784-21f97f61199c.png)

layout:

```
            <EditText
                android:id="@+id/post_content_field"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="10dp"
                android:paddingHorizontal="20dp"
                android:paddingVertical="25dp"
                android:gravity="top"
                android:textSize="16sp"
                android:textColor="@color/darkBlue"
                android:inputType="textMultiLine"
                android:background="@android:color/white"
                android:hint="@string/post_description_field_hint"
                android:importantForAutofill="no"
                app:layout_constraintTop_toBottomOf="@id/post_attachment_container" />
```

markwon setup:

```
        val markwon = Markwon.create(qtn.requireContext())
        val editor = MarkwonEditor.builder(markwon)
            .useEditHandler(EmphasisEditHandler())
            .useEditHandler(StrongEmphasisEditHandler())
            .useEditHandler(LinkEditHandler())
            .build()

        post_content_field.addTextChangedListener(MarkwonEditorTextWatcher.withProcess(editor))
```

LinkEditHandler implementation (mirrored [noties/LinkEditHandler](https://github.com/noties/Markwon/blob/develop/sample/src/main/java/io/noties/markwon/sample/editor/LinkEditHandler.java) in Kotlin):

```
class EditLinkSpanFactory: PersistedSpans.SpanFactory<LinkEditHandler.EditLinkSpan> {
    override fun create(): LinkEditHandler.EditLinkSpan {
        return LinkEditHandler.EditLinkSpan()
    }
}

class LinkEditHandler: AbstractEditHandler<LinkSpan>() {
    override fun configurePersistedSpans(builder: PersistedSpans.Builder) {
        builder.persistSpan(EditLinkSpan::class.java, EditLinkSpanFactory())
    }

    override fun handleMarkdownSpan(
        persistedSpans: PersistedSpans,
        editable: Editable,
        input: String,
        span: LinkSpan,
        spanStart: Int,
        spanTextLength: Int
    ) {
        val editLinkSpan = persistedSpans.get(EditLinkSpan::class.java)
        editLinkSpan.link = span.link

        var start = -1
        for (i in spanStart until input.length step 1) {
            if (Character.isLetter(input.toCharArray()[i])) {
                start = i
                break
            }
        }

        if (start > 1) {
            editable.setSpan(
                editLinkSpan,
                start,
                start + spanTextLength,
                Spanned.SPAN_EXCLUSIVE_EXCLUSIVE
            )
        }
    }

    override fun markdownSpanType(): Class<LinkSpan> {
        return LinkSpan::class.java
    }

    class EditLinkSpan: ClickableSpan() {
        var link: String = ""

        override fun onClick(widget: View) {
            // TODO: alert w option to open link in browser
        }
    }
}
```

**Comment by noties** [comment]
Hello @mr-spod ,

What you see is the result of text diffing. Currently editor functionality is implemented with text diff. Editor takes _rendered_ markdown and raw input and creates a diff result with [diff-patch-match](https://github.com/google/diff-match-patch). What is _deleted_ is considered markdown syntax and highlighted. In your example algorithm sees that `asd` text is present in both rendered and raw inputs, so it marks it as `equal`. Algorithm doesn't know that one is part of the URL and other is just unrelated text. 

Unfortunately there is nothing to be done. But on the side note - what you see is a rare thing. Change your input to something more _real_ and you will see that links are rendered OK. There are even multiple possible steps to make your input work as expected also:
* add any character _before_ `asdasd` -&gt; `tasdasd`
* add a new line before link
* add a new line after the `asdasd` 
* and much more...
