### ISSUE TITLE
custom delimiter for italic

### ISSUE THREAD

**Issue by kumarswamy-repo** [noties/Markwon#263]
* **Markwon version**: _{4.4.0}_

1. I want customize the delimiter used for italic mark down, currently it is working with * and _ only.
2. I have tried the following snippet to override italic behaviour

```
val editor = MarkwonEditor.builder(markwon)
                    .useEditHandler(object : EmphasisEditHandler(){
                        override fun handleMarkdownSpan(persistedSpans: PersistedSpans, editable: Editable, input: String, span: EmphasisSpan, spanStart: Int, spanTextLength: Int) {
                            val match = MarkwonEditorUtils.findDelimited(input, spanStart, "?", "/") // ? and / are custom delimiters tried 
                            if (match != null) {
                                editable.setSpan(
                                        persistedSpans.get(EmphasisSpan::class.java),
                                        match.start(),
                                        match.end(),
                                        Spanned.SPAN_EXCLUSIVE_EXCLUSIVE
                                )
                            }
                        }
                    }).build()

enterMessageEditText.addTextChangedListener(MarkwonEditorTextWatcher.withPreRender(
                    editor, Executors.newSingleThreadExecutor(), edit_text))
```

**Comment by noties** [comment]
Hello @kumarswamy-repo ,

please re-organize the information that you post - include relevant code snippets inside markdown [code blocks](https://spec.commonmark.org/0.29/#fenced-code-blocks). Code also should be properly formatted. Let's value time of people who might look at your issue.

As for your question - editor does not handle any markdown. Your markdown (`Markwon` instance) must know that `?` is an emphasis. I suggest you look at the [simple-ext](https://noties.io/Markwon/docs/v4/simple-ext/) in order to achieve that

**Comment by kumarswamy-repo** [comment]
Hi @noties,

Thanks for your update. I have formatted code as per your suggestion. I will try with **simple-ext**  and update here.

**Comment by kumarswamy-repo** [comment]
HI @noties,
We are able use custom delimiter with simpe-ext. Thanks for the support

**Comment by Shunaylov** [comment]
@noties I'm trying to override default StrongEmphasisSpan with simple-ext but I get an error: 

2020-11-05 19:31:07.931 26103-26103/? E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.IllegalArgumentException: Cannot add two delimiter processors for char '*' and minimum length 1

**Comment by noties** [comment]
Hello @Shunaylov ,

the `*` char is considered to be _core_ by the commonmark-java and you cannot override it by using `simple-ext`. It seems you want to change the styling of `StrongEmphasisSpan` and not parsing, is it right?

**Comment by Shunaylov** [comment]
> Hello @Shunaylov ,
> 
> the `*` char is considered to be _core_ by the commonmark-java and you cannot override it by using `simple-ext`. It seems you want to change the styling of `StrongEmphasisSpan` and not parsing, is it right?

Yes. I want to markup StrongEmphasis with one '*' symbol at the start and at the end, but not with 2 of them.

**Comment by Shunaylov** [comment]
@noties thank you, I used https://noties.io/Markwon/docs/v4/inline-parser/ and it did the job!
