### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by dbof10** [noties/Markwon#267]
I want to embed video or youtube video view, or custom view. It is possible to achieve? Since we can support table with recyclerview. I think it's feasible somehow.

**Comment by noties** [comment]
Hello @dbof10 ,

You haven't specified any specifics, but I think the answer is... _yes_<sup>*</sup>.

Have you looked at #252 ?

<sup>*</sup> &mdash; <em>there are a lot of thing to consider of cause</em>
