### ISSUE TITLE
Remove empty lines before render

### ISSUE THREAD

**Issue by manueldidonna** [noties/Markwon#269]
* **Markwon version**: 4.4.0

I don't want to render text with empty lines, so I would remove them from the parsed markdown. Empty lines are inserted automatically after headers, bullet lists, etc... There's a general way to accomplish that without modifying every visitor?

**Comment by noties** [comment]
Hello @manueldidonna ,

it is possible with a `BlockHandler`:

```java
final Markwon markwon = Markwon.builder(context)
  .usePlugin(new AbstractMarkwonPlugin() {
    @Override
    public void configureVisitor(@NonNull MarkwonVisitor.Builder builder) {
      builder.blockHandler(new BlockHandlerNoAdditionalNewLines());
    }
  })
  .build();
```

```java
class BlockHandlerNoAdditionalNewLines implements MarkwonVisitor.BlockHandler {

  @Override
  public void blockStart(@NonNull MarkwonVisitor visitor, @NonNull Node node) {
    // ensure that content rendered on a new line
    visitor.ensureNewLine();
  }

  @Override
  public void blockEnd(@NonNull MarkwonVisitor visitor, @NonNull Node node) {
    if (visitor.hasNext(node)) {
      visitor.ensureNewLine();
      // by default markwon here also has:
      //  visitor.forceNewLine();
    }
  }
}
```

---

You can preview the solution in the [sample app](https://github.com/noties/Markwon/raw/sample-store/markwon-debug.apk) [markwon://sample/202007211090524](markwon://sample/202007211090524)

**Comment by noties** [comment]
[https://noties.io/Markwon/app/sample/202007211090524](https://noties.io/Markwon/app/sample/202007211090524)

**Comment by manueldidonna** [comment]
Thanks @noties !
