### ISSUE TITLE
OrderedListItem number alignment

### ISSUE THREAD

**Issue by BaloghTamas** [noties/Markwon#271]
* **Markwon version**: _4.4.0_

When rendering ordered lists, the numbers are always aligned to the right, which is a bit unusual, as most markdown engines display them aligned to the left. To reproduce it render any ordered list that has more than one item. Like this:

```
1. First 
2. Second
3. Third
```

As far as I see there is no way of supporting that with the theme, but it would be great to have that, probably it would make sense to make it the default behavior.

**Comment by noties** [comment]
Hello @BaloghTamas ,

the right alignment comes directly from the HTML as markdown has no special rules for rendering. Instead it relies on how browser would render HTML (which markdown rendered list would be converted to):

```html
<ol>
    <li value="1">hello!</li>
    <li value="10">hello!</li>
    <li value="100">hello!</li>
    <li value="1000">hello!</li>
</ol>
```
-&gt;

<ol>
    <li value="1">hello!</li>
    <li value="10">hello!</li>
    <li value="100">hello!</li>
    <li value="1000">hello!</li>
</ol>

In my opinion right alignment makes more sense and is better in terms of UX. This is why I made it the default in the `Markwon`. What other markdown engines you are referring to?

**Comment by noties** [comment]
Closing for now, feel free to comment to reopen this issue
