### ISSUE TITLE
Node start/end positions

### ISSUE THREAD

**Issue by zhukovme** [noties/Markwon#273]
* **Markwon version**: 4.4.0

Hello!
Is it possible to calculate the positions of each node?
I want to split the raw text into parts with saving the markdown, for this it would be convenient to know the positions of each node. Or maybe with this library it can be done in another way?

**Comment by zhukovme** [comment]
It seems it cannot be done with this lib. I forked commonmark to do this

**Comment by noties** [comment]
Hello @zhukovme ,

yeah, there is no easy way to add source positions to nodes. I would be very interested to know how you achieved adding that to commonmark? It was not trivial thing when I investigated having such a feature. Did you fork the [commonmark-java](https://github.com/atlassian/commonmark-java)?

There is a fork of commonmark-java - [flexmark-java](https://github.com/vsch/flexmark-java) that have this feature, but there is no easy (or any actually) way to use it with `Markwon`
