### ISSUE TITLE
image-coil depends on io.coil-kt:coil instead of io.coil-kt:coil-base

### ISSUE THREAD

**Issue by ubuntudroid** [noties/Markwon#274]
* **Markwon version**: 4.4.0

According to the [coil documentation](https://coil-kt.github.io/coil/getting_started/#artifacts) libraries (and projects using dagger) should depend on `io.coil-kt:coil-base` instead of `io.coil-kt:coil`. Any reason `image-coil` uses the latter?

**Comment by noties** [comment]
Hello @ubuntudroid ,

no, no specific reason. Thanks for pointing this out 🙌

**Comment by noties** [comment]
The change is in `4.5.1`
