### ISSUE TITLE
How to change "Thematic break" top margin and bottom margin.

### ISSUE THREAD

**Issue by csgajcr** [noties/Markwon#278]
* **4.5.0**: _{REQUIRED}_

I see the thematic break color and height configuration in documentation , but i can't find how to set margin-top and margin-bottom.
In my project, margin of thematic break is too large.

Help me please.

**Comment by noties** [comment]
Hello @csgajcr ,

there is currently no configuration option to set top or bottom margin for the thematic break specifically. But you should know that this margin is created by a new line character, which you can control with the `BlockHandler`. I've create a [sample](https://noties.io/Markwon/app/sample/20200813154415) you can run.

In short - sample does not insert a new line, but if you wish to still have a margin, you can insert a new line and use a technique mentioned in the #106 (adjusting text size of a new line character)

**Comment by csgajcr** [comment]
@noties Thanks for your help, your method is help me solve the problem.

**Comment by noties** [comment]
You are welcome @csgajcr 🙌
