### ISSUE TITLE
How to get the text inside delimiter?

### ISSUE THREAD

**Issue by rshah** [noties/Markwon#279]
* **Markwon version**: _4.5.0_

I have similar problem like in #140  , i tried SimpleExtPlugin, but i don't know how to get the text inside the delimiter.
I'm using these as opening and closing delimiters `[[` and `]]`

I want to get the text inside delimiters and convert it to link.
For example [[My Example]], will be rendered as [My Example](https://www.example.com)

Could please advice some pointers?

**Comment by noties** [comment]
Hello @rshah ,

you can obtain clicked text using technique from the [sample](https://noties.io/Markwon/app/sample/20200629122230) (check the `ClickSelfSpan` and its `linkTitle` method)

**Comment by rshah** [comment]
Thank you for the sample @noties .

Actually i want to get the text `My Example` from `[[My Example]]` and convert it to any other span, for example link or just change the foreground color.

I tried with SimpleExtPlugin like this:
```
Markwon.builder(view.context)
     .usePlugin(SimpleExtPlugin.create {plugin ->
             plugin.addExtension(2, '[', ']') { configuration, props ->
                    ForegroundColorSpan(Color.RED)
              }
      })
``` 

But it will not be rendered as red color also the text still have delimiters `[[My Example]]`

**Comment by rshah** [comment]
I tried change the delimiter as in your simple-ext `@` and `$`, it's work.
So i guess these delimiters `[[` cannot be used in SimpleExtPlugin.

May be i should follow something like reddit spoiler sample, but how to remove the delimiter instead of hide it/make it transparent i want to remove the delimiter completely.

**Comment by rshah** [comment]
I managed to get the text `My Example` using these:
- Create plugin from `AbstractMarkwonPlugin` and replace `[[` with other delimiters
- Create inline processor to parse replaced text above and return `Text` node when matched.

Not sure if this is the good way.

**Comment by noties** [comment]
Hello @rshah ,

yes, `[` character is considered a _special_ one and thus won't be used when creating own delimiter or inline processors. For inline you could disable `OpenBrackerInlineProcessor` but this would disable markdown links also, so it might not be a good solution. 

Anyway, if you have found a solution that works for you - I think it is good enough 😄
