### ISSUE TITLE
Bullet/Unordered list unable to have a newline

### ISSUE THREAD

**Issue by mochadwi** [noties/Markwon#281]
* **Markwon version**: 4.5.1

Actual:

<img width="370" alt="Screen Shot 2020-08-21 at 8 18 41 AM" src="https://user-images.githubusercontent.com/7057959/90841700-7fa79280-e387-11ea-9ca9-b408774aebaf.png">

Expected:

Should have a newline for unordered/bullet list

Using:

Writing the character `*, -, &#8226;` unable to have a new line for each item

<img width="244" alt="Screen Shot 2020-08-21 at 8 18 55 AM" src="https://user-images.githubusercontent.com/7057959/90841746-a6fe5f80-e387-11ea-8a6e-5b25e47171ac.png">

**Comment by noties** [comment]
Hello @mochadwi ,

`<br>` is not a proper newline character, use `\n` to add a newline

**Comment by mochadwi** [comment]
closing this issue. Our backend decided to replace HTML entities by using common markdown instead
