### ISSUE TITLE
Justification Mode

### ISSUE THREAD

**Issue by ubuntudroid** [noties/Markwon#285]
* **Markwon version**: 4.5.1

1. I'd like to enable justification on the rendered text.
2. I'm using markwon in a RecyclerView. Setting `justificationMode` on either the TextView in the entry XML or via a `TextSetter` does not work - it just's cuts of the text at some line ends (see the cut off _t_ a the end of the second line from the bottom in the next screenshot), but no justification is applied.

![CleanShot 2020-08-24 at 12 02 51](https://user-images.githubusercontent.com/519867/91032108-c7d1e980-e601-11ea-9b14-d64cb4a7ceaa.png)

The screenshot is from an API level 30 emulator.

Setting the break strategy doesn't change anything either.

**Comment by noties** [comment]
Hello @ubuntudroid ,

this is definitely an Android issue - [sample](https://noties.io/Markwon/app/sample/20200826084338)

**Comment by ubuntudroid** [comment]
Hmm, could it be caused by the fact that I'm using the RecyclerView approach for rendering?

**Comment by noties** [comment]
Hardly, it seems to be a _universal_ behavior. Sample is not using RecyclerView and still reproduces the issue

**Comment by ubuntudroid** [comment]
On my Android 10 phone it looks fine - gonna try it on my Android 11 emulator as soon as I'm near my computer.

**Comment by noties** [comment]
Yeah, the sample displays it correctly - navigate to its source to see how 😄 

In short you should explicitly use `textView.setText(spanned);` method and not `textView.setText(md, TextView.BufferType.SPANNABLE);`. If any type is passed to the `setText` method then no justification happens

**Comment by ubuntudroid** [comment]
Oh, my bad - many thanks for the explanation! 🙏
