### ISSUE TITLE
Deep linking is not triggered

### ISSUE THREAD

**Issue by DaphnevdVeeke** [noties/Markwon#286]
* Markwon version: **4.5.1**

1. When I click a certain link in a text that uses Markwon I'd expect deep linking to trigger, just like when I would open this exact same link from a message or notes. The actual behaviour is that deep linking is not triggered and the link is opened in the browser.
2. The layout element `description` is a TextView and since I can't post the actual content and links here I'll provide an example of how I use Markwon:
    `Markwon.create(activity).setMarkdown(description, "[This is an example](https://google.com)")`

I've looked into other issues and documentation, but wasn't able to find anything on deep linking.

**Comment by noties** [comment]
Hello @DaphnevdVeeke ,

deeplinks should work as usual. Markwon does not make any assumptions about them. You can inspect the code that is used to handle all the link clicks in the `LinkResolverDef` ([source](https://github.com/noties/Markwon/blob/master/markwon-core/src/main/java/io/noties/markwon/LinkResolverDef.java), [documentation](https://noties.io/Markwon/docs/v4/core/configuration.html#linkresolver)) class. I also created a [sample](https://noties.io/Markwon/app/sample/20200826122247) that deeplinks into self (please note that it uses defaults and does not configure anything additionally).

You should re-check your links maybe there is some mis-configuration. If you are deeplinking into your own app check if you have configured deeplinks properly (you can inspect the [sample app](https://github.com/noties/Markwon/blob/master/app-sample/src/main/AndroidManifest.xml#L35) also)
