### ISSUE TITLE
HTML tags is disappearing instead of parsing

### ISSUE THREAD

**Issue by MatyashDen** [noties/Markwon#288]
* **Markwon version**: 4.2.0

1. I want to parse html tags, but it disappear
2. I have this html code: `someText <img src='pathOfImage' width='100%'>`, but see only `someText`

Here is my code:
```
val markwon = Markwon.builder(requireContext())
                .usePlugin(ImagesPlugin.create { plugin -> plugin.addSchemeHandler(FileSchemeHandler.create()) })
                .usePlugin(object : AbstractMarkwonPlugin() {
                    override fun configureVisitor(builder: MarkwonVisitor.Builder) {
                        builder.on(SoftLineBreak::class.java) { visitor: MarkwonVisitor, _ ->
                            visitor.forceNewLine()
                        }
                    }
                })
                .build()
markwon.setMarkdown(view.theory, exercise.text)
```

**Comment by noties** [comment]
Hello @MatyashDen ,

please refer to the [documentation](https://noties.io/Markwon/docs/v4/html/) and sample-app [examples](https://noties.io/Markwon/app/search?a=html) to get started

**Comment by MatyashDen** [comment]
> Hello @MatyashDen ,
> 
> please refer to the [documentation](https://noties.io/Markwon/docs/v4/html/) and sample-app [examples](https://noties.io/Markwon/app/search?a=html) to get started

thanks
