### ISSUE TITLE
How to configure a rounded shape with colored background for each word when using markdown for `<code>` syntax

### ISSUE THREAD

**Issue by mochadwi** [noties/Markwon#292]
* **Markwon version**: 4.5.1

1. Please specify expected/actual behavior

In current v4.5.1 we can't find `SpannableTheme` anymore.

We want to style the code similar to this library: https://github.com/kingideayou/MarkwonCodeEx

2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)

Nothing, it's a feature request (or maybe any equivalent approach in the v4.5.1 that we can't find in documentation)

**Comment by noties** [comment]
Hello @mochadwi ,

it's been some time since `MarkwonCodeEx` was introduced and some functionality has changed. For example current visitor might look like this:

```java
final Markwon markwon = Markwon.builder(context)
  .usePlugin(new AbstractMarkwonPlugin() {
    @Override
    public void configureVisitor(@NonNull MarkwonVisitor.Builder builder) {
      builder.on(Code.class, new MarkwonVisitor.NodeVisitor<Code>() {
        @Override
        public void visit(@NonNull MarkwonVisitor visitor, @NonNull Code code) {
          final int length = visitor.length();

          visitor.builder()
            .append('\u00a0')
            .append(code.getLiteral())
            .append('\u00a0');

          visitor.setSpans(length, new Object[] {
            new CodeSingleMetricSpan(),
            new ForegroundColorSpan(/*your code text color*/)
          });
        }
      });
    }
  })
  .build();
```

Unfortunately it won't be possible to use current version of `MarkwonCodeEx` with the latest `Markwon` as some minor changes are required. But I think the repo owner wouldn't mind a pull request 😉

**Comment by mochadwi** [comment]
Nice! As long there's an equivalent migration we might use the `MarkwonCodeEx` code and modify it to use latest `Markwon`

**Comment by mochadwi** [comment]
Does the Markwon 4.5.1 visitor also able to use rounded background? @noties

**Comment by noties** [comment]
The rounded background functionality comes from a custom [TextView](https://github.com/kingideayou/MarkwonCodeEx/blob/master/code_extension/src/main/java/me/next/codex/roundedbg/RoundedBgTextView.kt) implementation that you can find in the `MarkwonCodeEx`

**Comment by adesamp** [comment]
do you know equivalent for `SpannableTheme` in latest version? @noties 
![image](https://user-images.githubusercontent.com/61401530/92586672-c91d3a80-f2c0-11ea-8fd8-aa4554eca4ad.png)

**Comment by noties** [comment]
Hello @adesamp ,

of cause I do - `MarkwonTheme`
