### ISSUE TITLE
Is it possible to override destination when clicking link of HTML tag & Markdown syntax

### ISSUE THREAD

**Issue by mochadwi** [noties/Markwon#294]
* **Markwon version**: 4.5.1

### expected:
destination when clicking the link is overridden to a customized WebView instead of browser

### actual:
opening a browser instead

## 2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)

Using this:

```
[link](https://google.com)
// or
<a href="https://google.com">link</a>
```

both the above approach when clicked redirect to browser instead. Is it possible to override this behaviour so we can choose to our built-in customized WebView instead of default browser

**Comment by mochadwi** [comment]
Oops, looks like this is what we've been looking for? https://noties.io/Markwon/docs/v4/core/configuration.html#linkresolver

*will try this and close the issue if it works

**Comment by noties** [comment]
Hello @mochadwi ,

you are on the right track with the link resolver 😄
