### ISSUE TITLE
Animating spans on text set

### ISSUE THREAD

**Issue by c-b-h** [noties/Markwon#297]
* **Markwon version**: _4.6.0_

1. Please specify expected/actual behavior
This is a question rather than an issue but I can't seem to find the way raising it other than filing an issue.

2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)
Out team wants to achieve a simple animation involving `BackgroundSpan` when the `TextView`'s value is being set or when the view is attached to window. So now I am curious of _where_ @noties would recommend such a mechanism should be placed among plugins.
![untitled-YGz642Uz-D9X2](https://user-images.githubusercontent.com/14194998/93930571-e1a83e80-fd1d-11ea-9fb9-680259892bb8.gif)

**Comment by noties** [comment]
Hello @c-b-h ,

I would advice to follow the [kingideayou/MarkwonCodeEx](https://github.com/kingideayou/MarkwonCodeEx) approach based on [googlearchive/android-text/tree/master/RoundedBackground-Kotlin](https://github.com/googlearchive/android-text/tree/master/RoundedBackground-Kotlin) as you will need a fine grained control and access to `Canvas`.

A possible approach based on spans could be based on `LineBackgroundSpan` span implementation (one of the few that has access to `Canvas`). It has it limitations through, for example, span will receive coordinates for the full text line and you will have to find actual position of text chunk that you are interested; the other thing is you will have to deal with multiple lines of text inside the span, which can a major pain.

So, it seems that having own `TextView` widget is a more reliable way to implement such a feature

**Comment by c-b-h** [comment]
My question isn't necessary about the particular span to use but rather when to start and stop the animation that updates the span.

**Comment by noties** [comment]
It seems you did answer the question yourself 😉 

> when the TextView's value is being set or when the view is attached to window

**Comment by c-b-h** [comment]
I'm curious of if there is a way in Markwon of triggering updates of the span(s) being applied. Pseudo:

```
onTextSet = { text ->
   val valueAnimator = [0..text.length]
   setSpanStartEnd(valueAnimator.value, text.length)
}
```

I don't know if my question makes sense.

**Comment by noties** [comment]
A text changed notification can be received via regular `TextWatcher`. You can use a single-shot `TextWatcher` in your plugin from `beforeSetText` method (do not to unsubscribe in `afterTextChanged` method), or use plugins's `afterSetText` directly:

```java
@Override
public void afterSetText(@NonNull TextView textView) {
  final CharSequence cs = textView.getText();
  // process text, start animations, etc
}
```

**Comment by c-b-h** [comment]
I was considering this option:
```kotlin
private val animator = ValueAnimator().setDuration(5000)
override fun beforeSetText(textView: TextView, markdown: Spanned) {
}
override fun afterSetText(textView: TextView) {
}
```
but realised that `markdown` is `Spanned` and not `Spannable` (at least by contract) so I cannot intercept the output before it is set to the `TextView`. Is there a way of *intercepting* and mutating the outcome?

**Comment by noties** [comment]
Hello @c-b-h ,

it's been on my radar for some time, I think it is reasonable to change to the `Spannable` so it is _safe_ to edit resulting char sequence that will be applied. For now act dirty - cast to the `Spannable`

**Comment by c-b-h** [comment]
Thanks for clearing that out.

**Comment by c-b-h** [comment]
I thought I could share the way I went about implementing this behavior.

The html text being rendered is
```html
<h3>Lorem ipsum dolor sit amet.</h3>\n

Phasellus congue finibus ex, vitae <i>accumsan</i> leo accumsan ac.
Aliquam sagittis nunc quis mi facilisis elementum.
Etiam elementum <mark>sodales efficitur.
Mauris</mark> mattis a enim quis blandit.
```

```kotlin
.usePlugin(object : AbstractMarkwonPlugin() {

        override fun beforeSetText(textView: TextView, markdown: Spanned) {
            val highlightStart = markdown.getSpanStart(Highlight)
            val highlightEnd = markdown.getSpanEnd(Highlight)

            if (highlightStart < 0 || highlightEnd < 0) {
                return
            }

            val highlightLength = highlightEnd - highlightStart

            val spannableText = markdown.toSpannable()

            ValueAnimator.ofInt(highlightStart, highlightEnd).setDuration(highlightLength * 50L)
                .apply {
                    val span = BackgroundColorSpan(textView.highlightColor)

                    ValueAnimator.AnimatorUpdateListener { animation ->
                        val animatedValue = animation.animatedValue as Int

                        spannableText[highlightStart, animatedValue] = span

                        textView.text = spannableText
                    }.also { updateListener ->
                        addUpdateListener(updateListener)

                        doOnEnd {
                            removeUpdateListener(updateListener)
                        }
                    }
                }.start()
        }
    }
```

Also `HtmlPlugin` is used for allowing custom tags:

```kotlin
.usePlugin(HtmlPlugin.create { plugin ->
        plugin.addHandler(HighlightHandler)
    }

private object HighlightHandler : SimpleTagHandler() {
    override fun supportedTags() = setOf("mark")
    override fun getSpans(
        configuration: MarkwonConfiguration,
        renderProps: RenderProps,
        tag: HtmlTag,
    ): Any? {
        return Highlight
    }
}

private object Highlight
```

**Comment by noties** [comment]
Hello @c-b-h ,

thanks for posting code here, it might help some one in future.

There are some nitpicks though:
* current implementation won't allow multiple highlights - only one will be used (change `Highlight` to be regular class instead of a singleton)
* animation is a bit different from the GIF that you'd posted before, you are adding a background to individual letter and right now there will overdraw (for the number of characters in the `mark`) as with each animation step a new span is created starting with the very first position until current animation value. You can set new span for currently animated character instead to reduce overdraw
* `textView.text = spannableText` won't be required if you could operate on `TextView` internal spannable instance (calling a mere `invalidate` on the `TextView` should do the trick). You can obtain it from `afterSetText` method of your plugin by calling `textView.text as Spannable` directly

**Comment by c-b-h** [comment]
> current implementation won't allow multiple highlights - only one will be used (change Highlight to be regular class instead of a singleton)

The current requirement is one `<mark>` per markdown but you're right. This part isn't future-proof.

> animation is a bit different from the GIF that you'd posted before, you are adding a background to individual letter and right now there will overdraw (for the number of characters in the mark) as with each animation step a new span is created starting with the very first position until current animation value. You can set new span for currently animated character instead to reduce overdraw

What do you mean by overdraw? The span is shared among each animation step. I assumed that internally, `SpannableStringBuilder` changes the index of the start and end when spotting an existing instance of the same span. Notice that the span is instantiated outside of the callback functions:

```kotlin
val span = BackgroundColorSpan(textView.highlightColor)
```
> * `textView.text = spannableText` won't be required if you could operate on `TextView` internal spannable instance (calling a mere `invalidate` on the `TextView` should do the trick). You can obtain it from `afterSetText` method of your plugin by calling `textView.text as Spannable` directly

I'll try that out, thanks!

**Comment by c-b-h** [comment]
@noties 
A somewhat related question:

Using `<h3>` instead of `###` results in different line height (zero). Is this intentional?

**Comment by noties** [comment]
I missed that span is reused, so yeah, no overdraw 😄 

> Using \<h3> instead of ### results in different line height (zero). Is this intentional?

Not intentional, but HTML is just different. For example, consider markdown:

```java
final String md = "" +
  "### Head3 (markdown)\n\n" +
  "some text\n\n" +
  "<h3>Head3 (HTML)</h3>\n\n\n\n\n\n" +
  "some text";
```

Here, the whole line `<h3>Head3 (HTML)</h3>\n\n\n\n\n\n` is considered to be an HTML literal (in commonmark terms). And in HTML white space (new lines, spaces, tabs, etc) doesn't have any meaning unless it is inside a `<pre>` tag. This results in `\n\n\n\n\n\n` being consumed by HTML parser, which disregards it. This is why the `some text` will come right after the line with `<h3>...`. Whilst there will be a new line after markdown header. To add a new line after the HTML heading, we must _speak HTML_ and add `<br>` somewhere after `</h3>`:

```html
<h3>Head3 (HTML)</h3>\n\n\n\n\n\n<br>
```

**Comment by c-b-h** [comment]
Thanks for the clarification. 🙏
