### ISSUE TITLE
How to resize placeholder in GlideImagesPlugin?

### ISSUE THREAD

**Issue by HongBeenKim** [noties/Markwon#299]
* **Markwon version**: __4.6.0__

1. Please specify expected/actual behavior
I'm trying to get placeholder drawable have same dimension with the image to be loaded.
e.g. suppose my placeholder is a drawable of simple gray rectangle, this is what I want to achieve.
![image](https://raw.githubusercontent.com/HongBeenKim/milligram_server/master/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202020-09-30%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%207.58.01%20%E1%84%87%E1%85%A9%E1%86%A8%E1%84%89%E1%85%A1%E1%84%87%E1%85%A9%E1%86%AB.png?token=AIKQGRJQLGMQOEERHZYLYHS7PWZRE)

2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)
I'm using GlideImagesPlugin to load images with
  1)custom GlideStore to set placeholder
  2)custom ImageSizeResolver to fit the image width to canvas
```kotlin
class ArticleTestActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_article_test)

        val markwon = Markwon.builder(this)
            .usePlugin(GlideImagesPlugin.create(object : GlideImagesPlugin.GlideStore {
                override fun cancel(target: Target<*>) {
                    Glide.with(this@ArticleTestActivity).clear(target)
                }

                override fun load(drawable: AsyncDrawable): RequestBuilder<Drawable> {
                    return Glide.with(this@ArticleTestActivity)
                        .load(drawable.destination)
                        .placeholder(R.drawable.shape_placeholder)
                }

            }))
            .usePlugin(object: AbstractMarkwonPlugin() {
                override fun configureConfiguration(builder: MarkwonConfiguration.Builder) {
                    builder.imageSizeResolver(object: ImageSizeResolverDef() {
                        override fun resolveImageSize(imageSize: ImageSize?, imageBounds: Rect,
                            canvasWidth: Int, textSize: Float): Rect {
                            val newImageSize = ImageSize(ImageSize.Dimension(100f, "%"), null)
                            return super.resolveImageSize(newImageSize, imageBounds, canvasWidth, textSize)
                        }
                    })
                }
            })
            .build()

        markwon.setMarkdown(articleContentsTv,
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod " +
                    "tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, " +
                    "quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. " +
                    "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu " +
                    "fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in " +
                    "culpa qui officia deserunt mollit anim id est laborum. \n\n" +

                    "![](https://i.picsum.photos/id/866/536/354.jpg?hmac=tGofDTV7tl2rprappPzKFiZ9vDh5MKj39oa2D--gqhA)\n\n" +

                    "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod " +
                    "tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, " +
                    "quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. " +
                    "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu " +
                    "fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in " +
                    "culpa qui officia deserunt mollit anim id est laborum. \n\n")

    }
}
```

And this is code for placeholder drawable (shape_placeholder.xml).
```xml
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="@color/iosGray1" />
    <size android:width="300dp" android:height="100dp"/>
</shape>
```

With above code, placeholder appears like below, which does not satisfy my requirement.
![image](https://raw.githubusercontent.com/HongBeenKim/milligram_server/master/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202020-09-30%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%207.58.01.png?token=AIKQGRLV3HGFC6DNV3KY26S7PWZOQ)

How can I get image dimension in advance and apply it to placeholder?

**Comment by noties** [comment]
Hello @HongBeenKim ,

in order to display placeholder with the same size as the image - the image size must be known before loading. For example if you display your image with HTML you can specify width and height:

```html
<img src="{{location}}" width="100px" height="150px" />
```

Then size can be retrieved from `imageSize` property of an `AsyncDrawable`. Unfortunately this won't work for relative sizes (for example `width=100%`) as we must know aspect ratio in order to calculate height (given that we know available canvas width). So, if you happen to know aspect ratio of the image or can indicate it somehow (with custom URL or special property in markdown) you can display placeholder the same size as resulting image. Otherwise I'm afraid this won't be possible without downloading image first (before displaying markdown). But if you'd downloaded the image there is little need to display placeholder for it

**Comment by HongBeenKim** [comment]
Passing aspect ratio through custom URL should be the most practicable way.
Thanks a lot!
