### ISSUE TITLE
How to get the markup text from a EditText (paired with MarkwonEditor)

### ISSUE THREAD

**Issue by diman169** [noties/Markwon#300]
* **Markwon version**: 4.6.0

I am trying to create a WYSIWYG editor and then save the editing result to an md file.
EditText.getText().toString() returns plain text without markup. How to get text with markup?

**Comment by noties** [comment]
Hello @diman169 ,

what kind of markup you expect there to be? For example your _raw_ input is '\*\*hey** there!', then WYSIWYG editor would display: '**hey** there!'. In turn `EditText` when called `editText.getText().toString()` will return you the _raw_ input (`**hey** there!`). This is the result that can be persisted and used in future as it contains markdown markup (in this case `**` is markdown markup)

о какой разметке идёт речь? Например введён текст: '\*\*hey** there!', WYSIWYG редактор отобразит его как '**hey** there!'. В свою очередь `EditText` при вызове `editText.getText().toString()` вернёт исходный (сырой и необработанный) текст '\*\*hey** there!'. Этот текст можно сохранить и он не потеряет стиль в последствии, потому что `**` является синтаксисом markdown (его markup'ом)

**Comment by diman169** [comment]
In my case only clean text is returned.

This is the code:

```
class MainActivity extends AppCompatActivity {
    static String mText;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        EditText editText = findViewById(R.id.editText);
        mText = "# Hello world\n**Line 1**\n~~Line 2~~";

        Markwon markwon = Markwon.builder(this)
                .usePlugin(StrikethroughPlugin.create())
                .build();
        CharSequence cs = markwon.toMarkdown(mText);
        editText.setText(cs);

        Toast.makeText(this, editText.getText().toString(), Toast.LENGTH_LONG).show();
    }
}
```
This is the result:

![Screenshot_1601580759](https://user-images.githubusercontent.com/19308834/94857378-14e37f80-043a-11eb-9e36-f94cfc25b97c.png)

**Comment by diman169** [comment]
Thank you Dmitry for giving me the opportunity to figure it out myself. )
The example I gave above is incorrect. To implement the WYSIWYG editor, you need to use the code from the demo example. It does not translate the source text into CharSequence. HidePunctuationSpan is used to hide the markup characters. All markup characters are stored in the editor text. The author's previous answer was sufficient.
