### ISSUE TITLE
Markdown preview is not showing

### ISSUE THREAD

**Issue by RoblokazPlays** [noties/Markwon#302]
* **Markwon version**: _4.6.0_

### Please specify expected/actual behavior
I expect my EditText to preview the markdown like the video [here](https://noties.io/Markwon/docs/v4/editor/#getting-started-with-editor), and my EditText is not previewing the markdown I entered

### Please specify conditions/steps to reproduce (layout, code, markdown used, etc)
My dependencies
```gradle
implementation "io.noties.markwon:core:4.6.0"
implementation "io.noties.markwon:editor:4.6.0"
implementation "io.noties.markwon:ext-strikethrough:4.6.0"
implementation 'io.noties.markwon:ext-tables:4.6.0'
implementation 'io.noties.markwon:ext-tasklist:4.6.0'
implementation 'io.noties.markwon:html:4.6.0'
```

Code I am using
```java
final Markwon markwon = Markwon.create(ChatActivity.this);
final MarkwonEditor markwonEditor = MarkwonEditor.create(markwon);

etMessage.addTextChangedListener(MarkwonEditorTextWatcher.withPreRender(markwonEditor, Executors.newCachedThreadPool(), etMessage));
```

I'm trying to preview bold markdown

**Comment by noties** [comment]
Hello @RoblokazPlays ,

you need a special `EditHandler` in order to additionally process styles in editor. Take a look at the [sample](https://noties.io/Markwon/app/sample/20200629165136) and [refer to the documentation](https://noties.io/Markwon/docs/v4/editor/)

**Comment by RoblokazPlays** [comment]
I'm really dumb, so how do I use the EditHandler?

**Comment by chrisbarth01** [comment]
@noties I noticed that the textview in which the markdown content is shown is clickable by default. I've tried setting the XML attribute of clickable to `false` but it doesn't change anything. I also tried it from the Java code, yet, the textview is clickable. How can this be resolved?

**Comment by noties** [comment]
Hello @chrisbarth01 ,

if you wish `TextView` to not be clickable (this applies to all links in text) - you need to disable implicit movement method:
* [DisableImplicitMovementMethodPluginSample](https://github.com/noties/Markwon/blob/master/app-sample/src/main/java/io/noties/markwon/app/samples/movementmethod/DisableImplicitMovementMethodPluginSample.kt)
* [DisableImplicitMovementMethodSample](https://github.com/noties/Markwon/blob/master/app-sample/src/main/java/io/noties/markwon/app/samples/movementmethod/DisableImplicitMovementMethodSample.kt)

**Comment by chrisbarth01** [comment]
Thank you!
