### ISSUE TITLE
Multiline messages are not working correctly with Markwon

### ISSUE THREAD

**Issue by RoblokazPlays** [noties/Markwon#306]
* **Markwon version**: _4.6.0_

### Please specify expected/actual behavior
I'm making a messaging app, and I need multi line messages, so people can press enter to add a new line to their message. I think that Markwon is messing with this. Whenever I want to type multi line messages and press send, all of the words are on one line.

### Please specify conditions/steps to reproduce (layout, code, markdown used, etc)
I am using this code in MessagesAdapter
```java
final Markwon markwon = Markwon.builder(context)
                    .usePlugin(StrikethroughPlugin.create())
                    .usePlugin(HtmlPlugin.create())
                    .build();

markwon.setMarkdown(holder.tvSentMessage, message.getMessage());
```

I'm tried with no markdown, and the issue is present.
I tried with blockquotes, the issue is still present.
Bold, italics, etc will obviously still have the issue present.

**Comment by noties** [comment]
Hello @RoblokazPlays ,

this is a _feature_ of [commonmark specification](https://spec.commonmark.org/0.29/#soft-line-breaks) on which this library is based. What you are asking is how to treat soft breaks as hard ones. Refer to the `Soft line break` section of the [documentation page](https://noties.io/Markwon/docs/v4/core/core-plugin.html#props)
