### ISSUE TITLE
OnClickListeners do not work on textviews with Markwon

### ISSUE THREAD

**Issue by RoblokazPlays** [noties/Markwon#307]
* **Markwon version**: _4.6.0_

### Please specify expected/actual behavior
I am making a messaging app in Android Studio, and long pressing on messages and tapping on chats are super hard to touch since Markwon is apparently interfering with OnClickListeners.

### Please specify conditions/steps to reproduce (layout, code, markdown used, etc)
The markdown used can either be no markdown or markdown. Any text that has Markwon enabled no longer has a functional OnClickListener.

To try to reproduce, add a textview, set an onclicklistener, add markwon to that textview, and try tapping on it. For me, tapping on it no longer works.

**Comment by noties** [comment]
Hello @RoblokazPlays ,

take a look at the [pinned issue](https://github.com/noties/Markwon/issues/233) regarding click events in a `RecyclerView`. There are multiple way to deal with this issue, but the most effective, if your markdown does not have links  - would be:

```kotlin
val markwon = Markwon.builder(context)
  // explicit `none` movement method
  .usePlugin(MovementMethodPlugin.none())
  .build()
```
