### ISSUE TITLE
GrammarLocatorDef Not Found

### ISSUE THREAD

**Issue by TheMelody** [noties/Markwon#308]
![image](https://user-images.githubusercontent.com/9635441/96328471-0f12ae80-1076-11eb-9548-ed9b41bb9424.png)

**Comment by noties** [comment]
<img width="358" alt="Screenshot 2020-10-19 at 14 23 11" src="https://user-images.githubusercontent.com/7278986/96444314-95a5c800-11fd-11eb-9625-5f3549b9c86b.png">

**Comment by A5H1Q** [comment]
Hi @noties , I'm getting same error. above code doesn't help either. any ideas?

**Comment by noties** [comment]
Hello @A5H1Q ,

you need to check if:
- your project build script includes the [kapt](https://kotlinlang.org/docs/kapt.html):
   ```gradle
   plugins {
       id 'com.android.application'
       id 'org.jetbrains.kotlin.android'
       id 'org.jetbrains.kotlin.kapt' // THIS ONE
   }
   ```
- your have `kapt 'io.noties:prism4j-bundler:2.0.0'` in your dependencies block
- you put `@PrismBundle(includeAll = true)` annotation of one of your classes (without which annotation processing won't be triggered), `includeAll = true` would include all know grammars, you can configure this as needed by specifying other languages in `include` parameter:
   ```kotlin
   // include all know languages
   @PrismBundle(includeAll = true)
   
   // include just languages specified
   //@PrismBundle(include = ["kotlin", "java"])
   
   // include all languages and generate `MySuperGrammerLocator` 
   //  in the same package as annotated class, instead of `GrammarLocatorDef`
   //@PrismBundle(includeAll = true, grammarLocatorClassName = ".MySuperGrammerLocator")
   class MyApp: Application() {
   
   }
   ```

If you use java the same applies except the first point - you just need to specify `annotationProcessor 'io.noties:prism4j-bundler:2.0.0'` in your dependencies block
