### ISSUE TITLE
I want to load local drawable image 

### ISSUE THREAD

**Issue by Jsx9989** [noties/Markwon#309]
* **Markwon version**: 4.5.0

1. I want to load local drawable image , It doesn't work if I follow your documentation, Can you give me a specific example?

2. This is my code

        val markwon = Markwon.builder(this)
            .usePlugin(ImagesPlugin.create { plugin ->
                // for example to return a drawable resource
                plugin.addSchemeHandler(object : SchemeHandler() {
                    @SuppressLint("NewApi")
                    override fun handle(raw: String, uri: Uri): ImageItem {
                        // will handle URLs like `drawable://ic_account_24dp_white`
                        val resourceId: Int = resources.getIdentifier(
                            raw.substring("drawable://".length),
                            "drawable",
                            packageName
                        )

                        // it's fine if it throws, async-image-loader will catch exception
                        val drawable: Drawable = getDrawable(resourceId)!!
                        return ImageItem.withResult(drawable)
                    }

                    override fun supportedSchemes(): Collection<String> {
                        return Collections.singleton("drawable")
                    }
                })
            })
            .build()

markwon.setMarkdown(
            text_test, "<drawable>drawable://emoji_loading<drawable>"
        )

**Comment by noties** [comment]
Hello @Jsx9989 ,

images in markdown are displayed with syntax:

```markdown
![text description](image source)
```

So you need to change your markdown to `![emoji](drawable://emoji_loading)`

**Comment by holywend** [comment]
I have this issue as well, instead of using drawable:// I am planning to use book:// instead but it wont even print Log.e

```
private fun updateDisplay() {
        var content = book.chapters[currentIndex].chapContent
        binding!!.tvReadingTitle.text = book.chapters[currentIndex].chapTitle
        val imageLoader = ImageLoader.Builder(requireContext())
            .availableMemoryPercentage(0.25)
            .crossfade(true)
            .build()
        val markwon: Markwon = Markwon.builder(requireContext())
            .usePlugin(ImagesPlugin.create { plugin ->
                plugin.addSchemeHandler(object : SchemeHandler() {
                    override fun handle(raw: String, uri: Uri): ImageItem {
                        Log.e("images", "raw: $raw, uri: $uri")
                        val resourceId = context!!.resources.getIdentifier(
                            raw.substring("book://".length),
                            "book",
                            context!!.packageName
                        )
                        val drawable = context!!.getDrawable(resourceId)
                        return ImageItem.withResult(drawable!!)
                    }
                    override fun supportedSchemes(): Collection<String> {
                        return Collections.singleton("book")
                    }
                })
            })
            .usePlugin(CoilImagesPlugin.create(requireContext(), imageLoader))
            .build()
        markwon.setMarkdown(binding!!.tvContent, content)
    }
```
   
I was planning to read the image file from assets folder but even the Log.e wont print. I was planning to see what is the raw and uri there and work with it to get the resource in assets folder.

and the markdown 
`![](book://marble.jpg)`

**Comment by noties** [comment]
Hello @holywend ,

you are applying 2 images plugins - `ImagesPlugin` and `CoilImagesPlugin`. Each of them configures own instance of `AsyncDrawableLoader`. Of which only one instance is used by the `Markwon`. Your last call `.usePlugin(CoilImagesPlugin.create(requireContext(), imageLoader))` overrides `.usePlugin(ImagesPlugin.create { plugin ->` and thus nothing happens
