### ISSUE TITLE
Question: how to mark text to not parse it by Markwon

### ISSUE THREAD

**Issue by alexander-smityuk** [noties/Markwon#313]
* **Markwon version**: _{4.6.0}_

I have a question: Is it any way to mark a specific part of text with markdowns to say Markwon not to parse this part of text?

**Comment by noties** [comment]
Hello @alexander-smityuk ,

the most effortless solution would be not passing that part of text to markdown parser. For example, you can pre-process your input and extract parts that are not to be passed to markdown parser. I created a [sample](https://noties.io/Markwon/app/sample/20201111221945) that you can inspect as a reference

**Comment by alexander-smityuk** [comment]
@noties Thank you for the answers and the example. I will check.
