### ISSUE TITLE
How can i change color of Header and sub-Header Text?

### ISSUE THREAD

**Issue by chiragsharma991** [noties/Markwon#318]
I would like to change the color of the text in the Header. I added "headingBreakColor" to change color but it is not reflecting. could anyone guide me on what I miss?

    final Markwon markwon = Markwon.builder(getContext())
                                    .usePlugin(new AbstractMarkwonPlugin() {
                                        @Override
                                        public void configureTheme(@NonNull MarkwonTheme.Builder builder) {
                                            builder
                                                    .isLinkUnderlined(false).headingTextSizeMultipliers(new float[]{1.1F, 1.1F, 1.1F, 1.1F, .35F, .38F}).headingBreakHeight(0).headingBreakColor(Color.RED);
                                        }
                                    })
                                    .build();

**Comment by noties** [comment]
Hello @chiragsharma991 ,

you need an additional `SpanFactory` for that (`headingBreakColor` controls the line under 1 & 2 level heading):

```java
    final Markwon markwon = Markwon.builder(context)
      .usePlugin(new AbstractMarkwonPlugin() {
        @Override
        public void configureSpansFactory(@NonNull MarkwonSpansFactory.Builder builder) {
          builder.appendFactory(Heading.class, (configuration, props) -> {
            // here you can also inspect heading level
            final int level = CoreProps.HEADING_LEVEL.require(props);
            final int color;
            if (level == 1) {
              color = Color.RED;
            } else if (level == 2) {
              color = Color.GREEN;
            } else {
              color = Color.BLUE;
            }
            return new ForegroundColorSpan(color);
          });
        }
      })
      .build();
```
