### ISSUE TITLE
How to change dot bullet point with image ?

### ISSUE THREAD

**Issue by chaurasiadilip** [noties/Markwon#319]
I am using version 4.6.0  in the project.
I want to replace the dot bullet point with the image in the list. I do not want to replace the number-based bullet point.

Please specify expected/actual behavior
Test number list\n1. Number1\n2. Number2\n3. Number3\n4. Number4\n\nTest bullet list\n- Bullet1\n- Bullet2\n- Bullet3\n- Bullet4\n"

So please guide me on how to do it.

**Comment by chaurasiadilip** [comment]
@noties  please help me

**Comment by noties** [comment]
Hello @chaurasiadilip ,

you can use custom span for bullet lists - [ChangeBulletSpanSample](https://github.com/noties/Markwon/blob/923b00b6d0e791b9838cb6100b8ad979bba4c28f/app-sample/src/main/java/io/noties/markwon/app/samples/ChangeBulletSpanSample.java). How image is used depends on your needs. But most likely you will want to look at existing `LeadingMarginSpan` implementations, like:

* [BulletListItemSpan](https://github.com/noties/Markwon/blob/c939c0fa5c915778f46f22e2caa64f9beded77ba/markwon-core/src/main/java/io/noties/markwon/core/spans/BulletListItemSpan.java)
* [TaskListSpan](https://github.com/noties/Markwon/blob/dcd9d428eeaf4b4bc8399be2bdffd2daf02e1fd3/markwon-ext-tasklist/src/main/java/io/noties/markwon/ext/tasklist/TaskListSpan.java)

**Comment by chaurasiadilip** [comment]
@noties  Thanks for guiding me. I got success for me.
