### ISSUE TITLE
Coloring headlines

### ISSUE THREAD

**Issue by curiousily** [noties/Markwon#32]
Hi,

Is there a way to color all headlines in some color? I found the option for the line below a headline but not the text color itself.

Thanks for creating Markwon!

**Comment by noties** [comment]
Hello @curiousily !

First of all you are welcome :)

Secondly, yes, this definitely can be done. For example in #20 we have changed typeface of a quote element and here we can use the same technique:

*(I'm omitting everything else, this is your subclass of the `SpannableMarkdownVisitor` )*

```java
@Override
public void visit(BlockQuote blockQuote) {

    // mark current length
    final int length = builder.length();

    // pass to super to apply markdown
    super.visit(blockQuote);
    
    builder.setSpan(new ForegroundColorSpan(color), length, builder.length());
}
```

Please note though that this won't change underline color of a heading, so this still must be done when configuring SpannableTheme.

Hope this helps! 🙌

**Comment by curiousily** [comment]
Hey @noties,

That worked perfectly! Btw, nice use of the Visitor!

Side note: `SpannableRenderer` doesn't look that extendible. Maybe a template factory method can be used to create the instance of `SpannableMarkdownVisitor`.

Again, thanks for the library & the helpful response!
