### ISSUE TITLE
How to remove out-of-the-box plugin with no side effects?

### ISSUE THREAD

**Issue by Shunaylov** [noties/Markwon#320]
* **Markwon version**: _{v4.6.0}_

1. I'm trying to implement my own CorePlugin to disable some core markdowns (for example, bullet list).
2. I removed corresponding SpanFactory from configureSpansFactory method. 
3. Now there's no span over a list but the delimeter symbols disappear. 

So here's the question. How could I remove out-of-the-box plugin without any side effects? (For example, how could I remove a bullet list processing with saving delimeter symbols.)

**Comment by Shunaylov** [comment]
@noties can you help me?

**Comment by noties** [comment]
Hello @Shunaylov ,

what you are trying to do needs to modify markdown parsing. Which is controlled by the [commonmark-java] library. For example, if you want to modify _block_ behavior, you can inspect the _core_ blocks in the `CorePlugin.enabledBlockTypes()`. [And disable them](https://github.com/noties/Markwon/blob/72f6174db9530d2fab976b75a1451b63740390f7/app-sample/src/main/java/io/noties/markwon/app/samples/EnabledBlockTypesSample.kt). Note that both bullet and ordered lists share the same block parser, so you will need to create own implementation that disregards bullet lists but still processes ordered ones. Disabling bullet lists also disables task lists (if you use `ext-tasklist` artifact). 

If you need to disable _inline_ markdown nodes, then you will need to use special artifact - [inline-parser](https://github.com/noties/Markwon/tree/master/markwon-inline-parser). For starters you can look at the [100% disabled parser](https://github.com/noties/Markwon/blob/72f6174db9530d2fab976b75a1451b63740390f7/app-sample/src/main/java/io/noties/markwon/app/samples/NoParsingSample.java). And then start adding features as required. There are multiple samples in the `app-sample` module available that should cover most of the use cases

[commonmark-java]: https://github.com/commonmark/commonmark-spec

**Comment by Shunaylov** [comment]
Hmmm, @noties, these options give same results:
``` builder.enabledBlockTypes(setOf(IndentedCodeBlock::class.java)) ```

``` builder.enabledBlockTypes(Collections.emptySet()) ```

Is it a problem of commonmark-java only?

**Comment by noties** [comment]
Hello @Shunaylov ,

from my quick test the first sample would render only indented code blocks (code blocks prefixed with 4 spaces) and the second - rendering no blocks. What kind of problem do you see?
