### ISSUE TITLE
Ideas on how to support flow.js flows in code blocks

### ISSUE THREAD

**Issue by ankush-dcoder** [noties/Markwon#322]
* **Markwon version**: Latest

1. Would like markwon to support flow.js (https://flowchart.js.org/) flow diagrams.

example
```flow
st=>start: Start
e=>end: End
op=>operation: My Operation
op2=>operation: lalala
cond=>condition: Yes or No?

st->op->op2->cond
cond(yes)->e
cond(no)->op2
```

should produce :
![Screenshot 2020-12-09 at 10 02 38 PM](https://user-images.githubusercontent.com/58418945/101657861-61ff5580-3a6a-11eb-9bd7-d1f1d70cd24a.png)

**Comment by noties** [comment]
Hello @ankush-dcoder ,

I believe your best chance would be to use pre-rendered diagrams as images and display them via regular image-loading capabilities

**Comment by ankush-dcoder** [comment]
@noties I was going through documentation and saw markwon-recyclerview and an example of fenced code block with horizontal scroll.
The flow code to add in md is:

 ```` 
```flow
st=>start: Start
e=>end: End
op=>operation: My Operation
op2=>operation: lalala
cond=>condition: Yes or No?

st->op->op2->cond
cond(yes)->e
cond(no)->op2
``` 
````

If only in fencedblock handler I could detect the code as flow and render it in a webview component with js? Can you pass a webview component as a different item type to this adapter? Does the approach seems real to you?

**Comment by noties** [comment]
Hello @ankush-dcoder ,

it is real and it is possible to do so. You might struggle with performance/rendering issues though as `WebView` is a special kind especially when used inside a `RecyclerView`. But you should try and see for yourself if result fits your requirements. The only thing I would suggest is creating own custom block and parser for flow charts. Then supplying custom widget to render such a bock will be trivial with `markwon-recycler` artifact
