### ISSUE TITLE
Infinity for Reddit is using Markwon!

### ISSUE THREAD

**Issue by Docile-Alligator** [noties/Markwon#326]
Please provide the following:
* Infinity for Reddit
* https://play.google.com/store/apps/details?id=ml.docilealligator.infinityforreddit
* https://play-lh.googleusercontent.com/m6jSo9ki-Vga40SDj0bJrZHW7ma0h56EtNPfoNqYjzW_ehlrXodWpBsK8f_IH1p3VA=s180-rw
🙌

**Comment by Docile-Alligator** [comment]
I did not find a way to label this issue as "awesome".

**Comment by noties** [comment]
Awesome!
