### ISSUE TITLE
Table with horizontal scroll

### ISSUE THREAD

**Issue by chaurasiadilip** [noties/Markwon#327]
* **Markwon version**: _{4.6.1}_
I am using TablePlugin for showing content in the table format. Small content is showing properly. But when big content is showing improper like below image.
![device-2021-01-08-184746](https://user-images.githubusercontent.com/11071181/104020424-385d5980-51e3-11eb-84f6-9d0546cbdbf5.png)

I want to show content in the table with a horizontal scroll. I see your example with the recycler view that is working. But I do not want to use the recycler view. so can anyone help me by showing content in the table with a horizontal scroll.

SC-1\n\n| POS     | URL     | Name     |\n| ---------- | ---------- | ---------- |\n| 1      
     | https://www.google.com/search?ei=ChD4X_GmB86P9QO7k554&q=markdown+table+render+in+markwon&oq=markdown+table+render+in+markwon&gs_lcp=CgZwc3ktYWIQAzIHCCEQChCgAToECAAQRzoECAAQDToGCAAQDRAKOggIABANEAUQHjoKCAAQCBANEAoQHjoICAAQCBANEB46BggAEA0QHjoFCAAQzQJQ05XqAliv6OoCYOWK6wJoAHACeAGAAYcDiAGWG5IBCDEuMjMuMS4xmAEAoAEBqgEHZ3dzLXdpesgBCMABAQ&sclient=psy-ab&ved=0ahUKEwjx0_mV7ovuAhXOR30KHbuJBw8Q4dUDCA0&uact=5       
     | Release Notes -  Widget Deployment       |\n| 2       | https://www.google.com/search?ei=ChD4X_GmB86P9QO7k554&q=markdown+table+render+in+markwon&oq=markdown+table+render+in+markwon&gs_lcp=CgZwc3ktYWIQAzIHCCEQChCgAToECAAQRzoECAAQDToGCAAQDRAKOggIABANEAUQHjoKCAAQCBANEAoQHjoICAAQCBANEB46BggAEA0QHjoFCAAQzQJQ05XqAliv6OoCYOWK6wJoAHACeAGAAYcDiAGWG5IBCDEuMjMuMS4xmAEAoAEBqgEHZ3dzLXdpesgBCMABAQ&sclient=psy-ab&ved=0ahUKEwjx0_mV7ovuAhXOR30KHbuJBw8Q4dUDCA0&uact=5
        | WEB-Support Release     |\n| 3     
          | https://www.google.com/search?ei=ChD4X_GmB86P9QO7k554&q=markdown+table+render+in+markwon&oq=markdown+table+render+in+markwon&gs_lcp=CgZwc3ktYWIQAzIHCCEQChCgAToECAAQRzoECAAQDToGCAAQDRAKOggIABANEAUQHjoKCAAQCBANEAoQHjoICAAQCBANEB46BggAEA0QHjoFCAAQzQJQ05XqAliv6OoCYOWK6wJoAHACeAGAAYcDiAGWG5IBCDEuMjMuMS4xmAEAoAEBqgEHZ3dzLXdpesgBCMABAQ&sclient=psy-ab&ved=0ahUKEwjx0_mV7ovuAhXOR30KHbuJBw8Q4dUDCA0&uact=5    | Article       |\n| 4       | https://www.google.com/search?ei=ChD4X_GmB86P9QO7k554&q=markdown+table+render+in+markwon&oq=markdown+table+render+in+markwon&gs_lcp=CgZwc3ktYWIQAzIHCCEQChCgAToECAAQRzoECAAQDToGCAAQDRAKOggIABANEAUQHjoKCAAQCBANEAoQHjoICAAQCBANEB46BggAEA0QHjoFCAAQzQJQ05XqAliv6OoCYOWK6wJoAHACeAGAAYcDiAGWG5IBCDEuMjMuMS4xmAEAoAEBqgEHZ3dzLXdpesgBCMABAQ&sclient=psy-ab&ved=0ahUKEwjx0_mV7ovuAhXOR30KHbuJBw8Q4dUDCA0&uact=5     | Article       |\n| 5       | google.com       | Article       |\n| 6       | www.facebook.com      | \n "QA test title\")\n\nSC-2\n\n| Header1     | Header2     | Header3     |\n| ---------- | ---------- | ---------- |\n| Cell1       | Cell1       | Cell1       |\n| Cell2       | Cell2       | Cell2       |\n| Cell3       | Cell3       | Cell3       |\n\n![1017386943-LAT-20190313- J6I2618](https://www.nytimes.com/2021/01/06/us/politics/trump-riot-dc-capitol-photos.html)\n\nTest number list\n1. Number1\n2. Number2\n3. Number3\n4. Number4\n\nTest bullet list\n- Bullet1\n- Bullet2\n- Bullet3\n- Bullet4\n"

 Thanks
Dileep

**Comment by chaurasiadilip** [comment]
@noties  can you help with this?

**Comment by noties** [comment]
Hello @chaurasiadilip ,

it is possible to do, but it would require an effort. At this point it is much easier just to use the `RecyclerView` version. I have a feature planned that could've solved your issue, but I have no estimate for it, so I would not put your hopes high. If you are inclined to use a `LinearLayout` (or similar ViewGroup), then you could:

* parse markdown and obtain `Node`
* then use `MarkwonReducer` to create a list of nodes
* then use a special widget for each node in that list (`TableBlock` would appear here) and create a view for it, which you append to your ViewGroup contaner

so far I'm describing the logic that `markwon-adapter` is using. 

* take `TableEntry` and see what it does, there is no _magic_ &mdash; it is using all public constructs, methods and properties, and adjust it to fit your needs

---
For the future, please format your code snippets accordingly, it is super easy with markdown, surround your code with three backticks (<code>```</code>):

```markdown
Hello **there**, _hey_!
```
