### ISSUE TITLE
How to remove default margin or spacing of TextView android (I used Markwon for text formatting but it comes up with the following spaces that is shown in the figure)

### ISSUE THREAD

**Issue by arbaz07** [noties/Markwon#328]
<img width="368" alt="Screenshot 2021-01-12 at 4 28 04 PM" src="https://user-images.githubusercontent.com/53600335/104308970-436dfd80-54f3-11eb-8408-44ead1fb7afe.png">
* **Markwon version**: _{REQUIRED}_

1. Please specify expected/actual behavior
2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)

**Comment by noties** [comment]
Hello @arbaz07 ,

can you provide your markdown input and the output of the `DumpNodes.dump()` method?

**Comment by arbaz07** [comment]
Markwon markwon;
markwon.setMarkdown(textView, " **Demo Text** ");

When I enter text, bottom spacing  also added in textview(android). I want to remove that bottom space from textview. Any solution ?

**Comment by noties** [comment]
Hello @arbaz07 ,

it seems there is an some issue with your layout, Markwon does not add any spacing to a TextView
