### ISSUE TITLE
BlockHandler not get called for HTML tags

### ISSUE THREAD

**Issue by Adambl4** [noties/Markwon#332]
* **Markwon version**: 4.6.1

`BlockHandler` not get called for HTML tags, but works well for Markdown tags. I'm not sure is this intended behaviour or a bug.

```
 val markwon = Markwon
            .builder(Const.context)
            .usePlugin(HtmlPlugin.create())
            .usePlugin(object : AbstractMarkwonPlugin() {
                override fun configureVisitor(builder: MarkwonVisitor.Builder) {
                    builder.blockHandler(object : BlockHandlerDef() {
                        override fun blockStart(visitor: MarkwonVisitor, node: Node) {
                            // not get called
                            super.blockStart(visitor, node)
                        }

                        override fun blockEnd(visitor: MarkwonVisitor, node: Node) {
                            // not get called
                            super.blockEnd(visitor, node)
                        }
                    })
                }
            })
            .build()

        val string = "<h1>Hello there!</h1>"
        markwon.setMarkdown(textView, string)
```

**Comment by noties** [comment]
Hello @Adambl4 ,

it is intentional according to the commonmark specification. You can handle HTML tags with the `HtmlPlugin` plugin. There  are multiple samples in the [sample application](https://github.com/noties/Markwon/tree/master/app-sample/src/main/java/io/noties/markwon/app/samples/html) that show how to do it

**Comment by Adambl4** [comment]
I had tried to use BlockHandler to control number of new lines between HTML tags and did not realized that it works only for markdown blocks.
I've achieved this kind of control using custom HTML tag handlers.

Thank you for the response and for the great library!
