### ISSUE TITLE
D/skia: --- Failed to create image decoder with message 'unimplemented'

### ISSUE THREAD

**Issue by dummyco** [noties/Markwon#334]
**Markwon version**: 4.6.1

```
implementation "io.noties.markwon:core:4.6.1"
implementation "io.noties.markwon:image:4.6.1"
implementation "com.caverock:androidsvg:1.4"
```

It seems like when combining `FileSchemeHandler.createWithAssets` and `SvgMediaDecoder`, `ImageItem` fails to get `contentType` for asset-based SVGs, resulting in no `SvgMediaDecoder` resolved from `mediaDecoders` _(AsyncDrawableLoaderImpl:114)_

```
ImagesPlugin.create { plugin ->
  plugin
    .addSchemeHandler(FileSchemeHandler.createWithAssets(itemView.context))
    .addMediaDecoder(SvgMediaDecoder.create(itemView.context.resources))
}
```

![image](https://user-images.githubusercontent.com/3989453/105916354-6e9b3580-6039-11eb-8eb5-e30d850ca39a.png)

**Comment by noties** [comment]
Hello @dummyco ,

`FileSchemeHandler` uses file extension to detect content type: 

```java
final String contentType = MimeTypeMap
        .getSingleton()
        .getMimeTypeFromExtension(MimeTypeMap.getFileExtensionFromUrl(fileName));
```

Do your SVG assets have proper extensions, like `my_file.svg`?

**Comment by dummyco** [comment]
@noties, thank you for such a quick response and great library!
Indeed, just found out that `FileSchemeHandler` is fetching `MimeType` from the extension.
It seems like I'll need to override `handle` a bit 👍🏻

**Comment by noties** [comment]
You are welcome 🙌
