### ISSUE TITLE
Image size for SVG

### ISSUE THREAD

**Issue by imarindam** [noties/Markwon#335]
* **Markwon version**: 4.6.1

I want to show HTML with SVG <img> in textview (in Recyclerview) with Markwon. I can see the images but its incorrect dimension. 
Can anyone help me to get it right?

**My code:**

**build.gradle:**

```
implementation 'io.noties.markwon:core:4.6.1'
implementation 'io.noties.markwon:image:4.6.1'
implementation 'io.noties.markwon:html:4.6.1'
implementation 'io.noties.markwon:image-picasso:4.6.1'
implementation 'io.noties.markwon:inline-parser:4.6.1'
```
**Java:**

```
final Markwon markwon = Markwon.builder(mContext)
                .usePlugin(ImagesPlugin.create(plugin -> {
                    plugin.addMediaDecoder(SvgMediaDecoder.create());
                }))
                .usePlugin(HtmlPlugin.create())
                .build();
        markwon.setMarkdown(((ListTypeViewHolder) holder).excerpt_text,object.excerpt);
```

**HTML:**

`<p><img loading=\"lazy\" src=\"https://asedusolution.com/wp-content/ql-cache/quicklatex.com-ba6a824ce9e4765a56404bef612cc73d_l3.svg\" class=\"ql-img-inline-formula \" alt=\"&#92;&#108;&#101;&#102;&#116;&#32;&#91;&#32;&#65;&#92;&#99;&#97;&#112;&#32;&#66;&#32;&#92;&#114;&#105;&#103;&#104;&#116;&#32;&#93;&#92;&#99;&#117;&#112;&#32;&#92;&#108;&#101;&#102;&#116;&#32;&#91;&#32;&#65;&#92;&#99;&#97;&#112;&#32;&#67;&#32;&#92;&#114;&#105;&#103;&#104;&#116;&#32;&#93;\" title=\"Rendered by QuickLaTeX.com\" height=\"19\" width=\"137\" style=\"vertical-align: -5px;\"/><br />\nIf <img loading=\"lazy\" src=\"https://asedusolution.com/wp-content/ql-cache/quicklatex.com-86cad50cd5715bca8c9499e530d9f2d5_l3.svg\" class=\"ql-img-inline-formula \" alt=\"&#85;&#61;&#92;&#108;&#101;&#102;&#116;&#32;&#92;&#123;&#32;&#120;&#58;&#48;&#60;&#32;&#120;&#60;&#32;&#50;&#48;&#44;&#32;&#120;&#92;&#105;&#110;&#32;&#78;&#32;&#92;&#114;&#105;&#103;&#104;&#116;&#32;&#92;&#125;\" title=\"Rendered by QuickLaTeX.com\" height=\"19\" width=\"231\" style=\"vertical-align: -5px;\"/><br />\nA = {x : x is prime number less than 20}<br />\nB = {x :  x is divisible by 3, <img loading=\"lazy\" src=\"https://asedusolution.com/wp-content/ql-cache/quicklatex.com-9fb9af592fe2d49fcbc73cb4c9c1c2c3_l3.svg\" class=\"ql-img-inline-formula \" alt=\"&#120;&#92;&#108;&#101;&#113;&#115;&#108;&#97;&#110;&#116;&#32;&#49;&#53;\" title=\"Rendered by QuickLaTeX.com\" height=\"16\" width=\"54\" style=\"vertical-align: -3px;\"/> }<br />\nC = {x : x is an odd number less than 18}<br />\n(a) {1, 3, 5, 7}<br />\n(b) {3, 5, 7, 11, 13, 17}<br />\n(c) {1, 7, [&#8230;]</p>\n`

`<p><img loading=\"lazy\" src=\"https://asedusolution.com/wp-content/ql-cache/quicklatex.com-17b102676bd9f78a1ccbaeea0b59ad12_l3.svg\" class=\"ql-img-inline-formula \" alt=\"&#65;&#32;&#92;&#116;&#105;&#109;&#101;&#115;&#32;&#92;&#108;&#101;&#102;&#116;&#32;&#40;&#32;&#66;&#92;&#99;&#97;&#112;&#32;&#67;&#32;&#92;&#114;&#105;&#103;&#104;&#116;&#32;&#41;&#61;&#63;\" title=\"Rendered by QuickLaTeX.com\" height=\"19\" width=\"131\" style=\"vertical-align: -5px;\"/><br />\n(a) <img loading=\"lazy\" src=\"https://asedusolution.com/wp-content/ql-cache/quicklatex.com-53ac988b3bdd3cb5182d031417d31318_l3.svg\" class=\"ql-img-inline-formula \" alt=\"&#92;&#108;&#101;&#102;&#116;&#32;&#40;&#32;&#65;&#92;&#116;&#105;&#109;&#101;&#115;&#32;&#66;&#32;&#92;&#114;&#105;&#103;&#104;&#116;&#32;&#41;&#92;&#99;&#117;&#112;&#32;&#92;&#108;&#101;&#102;&#116;&#32;&#40;&#32;&#65;&#92;&#116;&#105;&#109;&#101;&#115;&#32;&#67;&#32;&#92;&#114;&#105;&#103;&#104;&#116;&#32;&#41;\" title=\"Rendered by QuickLaTeX.com\" height=\"19\" width=\"152\" style=\"vertical-align: -5px;\"/><br />\n(b) <img loading=\"lazy\" src=\"https://asedusolution.com/wp-content/ql-cache/quicklatex.com-7e97f294306c02f7434bd024b2ddb953_l3.svg\" class=\"ql-img-inline-formula \" alt=\"&#92;&#108;&#101;&#102;&#116;&#32;&#40;&#32;&#65;&#32;&#92;&#116;&#105;&#109;&#101;&#115;&#32;&#66;&#32;&#92;&#114;&#105;&#103;&#104;&#116;&#32;&#41;&#45;&#32;&#92;&#108;&#101;&#102;&#116;&#32;&#40;&#32;&#65;&#32;&#92;&#116;&#105;&#109;&#101;&#115;&#32;&#67;&#32;&#92;&#114;&#105;&#103;&#104;&#116;&#32;&#41;\" title=\"Rendered by QuickLaTeX.com\" height=\"19\" width=\"154\" style=\"vertical-align: -5px;\"/><br />\n(c) <img loading=\"lazy\" src=\"https://asedusolution.com/wp-content/ql-cache/quicklatex.com-2829d7b64ed51f54ef97fab2e3caf183_l3.svg\" class=\"ql-img-inline-formula \" alt=\"&#92;&#108;&#101;&#102;&#116;&#32;&#40;&#32;&#65;&#92;&#116;&#105;&#109;&#101;&#115;&#32;&#66;&#32;&#92;&#114;&#105;&#103;&#104;&#116;&#32;&#41;&#92;&#99;&#97;&#112;&#32;&#92;&#108;&#101;&#102;&#116;&#32;&#40;&#65;&#92;&#116;&#105;&#109;&#101;&#115;&#32;&#67;&#32;&#92;&#114;&#105;&#103;&#104;&#116;&#32;&#41;\" title=\"Rendered by QuickLaTeX.com\" height=\"19\" width=\"152\" style=\"vertical-align: -5px;\"/><br />\n(d) None of these</p>\n`

**O/P Screenshot:**

![Inked1612084783513_LI](https://user-images.githubusercontent.com/18639540/106379762-47938980-63d4-11eb-9b7a-b0a356b79ada.jpg)

Thank you.

**Comment by noties** [comment]
Hello @imarindam ,

I see that your images have dimension information (`width` and `height` attributes), but those do not specify units. And default `ImageSizeResolverDef` assumes them to be pixels. This might be the problem here. A quick fix would be using `em` units (relative to text size) - for example, `19em`. Or creating custom `ImageSizeResolver` that processes values differently

**Comment by noties** [comment]
take a look at the [sample](https://github.com/noties/Markwon/blob/master/app-sample/src/main/java/io/noties/markwon/app/samples/image/ImageSizeResolverSample.kt)

**Comment by imarindam** [comment]
> take a look at the [sample](https://github.com/noties/Markwon/blob/master/app-sample/src/main/java/io/noties/markwon/app/samples/image/ImageSizeResolverSample.kt)

Thank you so much for your reply. This is really helpful.
But the file is inKotlin which I am not familiar with yet. Can you help me with this chunk of code and help me convert to java?
`class DensityImageSizeResolver : ImageSizeResolverDef() {

    val density: Float by lazy(LazyThreadSafetyMode.NONE) {
      Resources.getSystem().displayMetrics.density
    }

    override fun resolveAbsolute(dimension: ImageSize.Dimension, original: Int, textSize: Float): Int {
      if (dimension.unit == null) {
        // assume density pixels
        return (dimension.value * density + 0.5F).toInt()
      }
      return super.resolveAbsolute(dimension, original, textSize)
    }
  }`
It will be really helpful. Thanks.

**Comment by imarindam** [comment]
Thank you so much for your reply. It is really helpful.
Can you please help me with Java of 

```
class DensityImageSizeResolver : ImageSizeResolverDef() {

    val density: Float by lazy(LazyThreadSafetyMode.NONE) {
      Resources.getSystem().displayMetrics.density
    }

    override fun resolveAbsolute(dimension: ImageSize.Dimension, original: Int, textSize: Float): Int {
      if (dimension.unit == null) {
        // assume density pixels
        return (dimension.value * density + 0.5F).toInt()
      }
      return super.resolveAbsolute(dimension, original, textSize)
    }
  }
```
I don't understand Kotlin yet.

**Comment by noties** [comment]
It is a fairly trivial code snippet that almost identically matches Java:

```java
class DensityImageSizeResolver extends ImageSizeResolverDef {

    final float density = Resources.getSystem().getDisplayMetrics().density;

    @Override
    protected int resolveAbsolute(@NonNull ImageSize.Dimension dimension, int original, float textSize) {
        if (dimension.unit == null) {
            return (int) (dimension.value * density + 0.5F);
        }
        return super.resolveAbsolute(dimension, original, textSize);
    }
}
```
