### ISSUE TITLE
Extract HTML String from HtmlTag

### ISSUE THREAD

**Issue by seanghay** [noties/Markwon#336]
* **Markwon version**: 4.6.0
* **Dependencies**
```groovy
implementation 'io.noties.markwon:core:4.6.0'
implementation 'io.noties.markwon:html:4.6.0'
implementation 'io.noties.markwon:recycler:4.6.0'
implementation 'io.noties.markwon:image-glide:4.6.0'
implementation 'io.noties.markwon:image:4.6.0'
implementation 'io.noties.markwon:linkify:4.6.0'
```
---
### The Problem

I want to display a custom thumbnail of a YouTube video.

Let's say I have HTML content that looks something like this:

```html
<p>lorem ipsum</p>
<div class="custom-youtube-player">https://www.youtube.com/watch?v=abcdefgh</div>
```

So how do I extract the YouTube URL(`https://www.youtube.com/watch?v=abcdefgh`) from `HtmlTagImpl` object?
I tried using `HtmlTag#getChildren()` and it returns an empty list. I think it should have returned a `TextNode` instead.

As far as I checked inside the source code, I didn't see any method for getting children's content.

**Comment by noties** [comment]
Hello @seanghay ,

there is no `TextNode` associated with `HtmlTag`, but you can inspect text content via `MarkwonVisitor` that is supplied to your custom `TagHandler`, here is a [sample](https://github.com/noties/Markwon/blob/master/app-sample/src/main/java/io/noties/markwon/app/samples/html/InspectHtmlTextSample.kt) that does that

**Comment by seanghay** [comment]
> Hello @seanghay ,
> 
> there is no `TextNode` associated with `HtmlTag`, but you can inspect text content via `MarkwonVisitor` that is supplied to your custom `TagHandler`, here is a [sample](https://github.com/noties/Markwon/blob/master/app-sample/src/main/java/io/noties/markwon/app/samples/html/InspectHtmlTextSample.kt) that does that

Thanks so much!
