### ISSUE TITLE
Is there any type of this library for iOS?

### ISSUE THREAD

**Issue by Chomroeun** [noties/Markwon#338]
* **Markwon version**: _{REQUIRED}_

1. Please specify expected/actual behavior
2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)

**Comment by noties** [comment]
Hello @Chomroeun ,

I'm pretty sure there are plenty iOS libraries of this type available. You need to be more specific if you are looking for an actual answer

**Comment by Chomroeun** [comment]
Thanks @noties for reply!
Yes it has many libraries on iOS but most of them is WebView base and also did not support Latex plugin

**Comment by noties** [comment]
Hello @Chomroeun ,

there are multiple iOS libraries that render markdown as `NSAttributedString` (similar to spans on Android). But I'm not aware of one that supports LaTeX. Maybe someone else here can recommend you a way to go. 

By the way, have you already tried WebView based library on iOS? In my experience WebView works much better on iOS, and overall performance is much better than on Android
