### ISSUE TITLE
Some questions related to superscript and SimpleExtPlugin addExtension

### ISSUE THREAD

**Issue by Docile-Alligator** [noties/Markwon#339]
* **Markwon version**: 4.6.2

1. Please specify expected/actual behavior
Reddit uses one ^ to show superscript (e.g. ^foobar) while Markwon only supports \<sup>. So, I use regex to manually add another ^ and add
```
.usePlugin(SimpleExtPlugin.create(plugin ->
                                plugin.addExtension(1, '^', (configuration, props) -> {
                                    return new SuperscriptSpan();
                                })
                        )
                )
```
when initializing Markwon to show superscript. As a result, `^something^` is now parsed as superscript with no issue. But `^something ^`, `^ something ^` or `^ something^` (you can see there is a space before the second ^ or after the first ^) is displayed as-is. It should be treated as superscript. Also, `something^?^` is not working, only `something ^?^` (you can see there is a space before the first ^) works.

Another problem is that SuperscriptSpan does not make the superscript smaller. How can I make it use a smaller font?

2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)
Initialize Markwon as the following:
```
Markwon.builder(this)
.usePlugin(SimpleExtPlugin.create(plugin ->
                                plugin.addExtension(1, '^', (configuration, props) -> {
                                    return new SuperscriptSpan();
                                })
                        )
                )
.build();
```

Should I use SimpleExtPlugin to add an ^ extension? Currently, Reddit's superscript only requires one ^ while addExtension requires opening and closing characters. Do you have a better method to show Reddit's superscript without using regex? Thank you in advance.

**Comment by noties** [comment]
Hello @Docile-Alligator ,

`SimpleExtPlugin` is a the best tool here as, as you have noticed, it processes whitespace in the _commonmark_ way. I suggest _preprocessing_ your markdown first by inserting HTML `<sup></sup>` tag. This way superscript will appear exactly where you put it. There is no other steps except from using `HtmlPlugin` when building `Markwon` instance.

Customization of the `SuperscriptSpan` is not supported. By default `HtmlPlugin.SCRIPT_DEF_TEXT_SIZE_RATIO` (0.75F) is used to calculate superscript size (`original text size * ratio` is the formula). If you wish to change that you can create own span (it is pretty trivial). I've added a [sample] to show how to do it

[sample]: https://github.com/noties/Markwon/blob/master/app-sample/src/main/java/io/noties/markwon/app/samples/parser/RedditSuperscriptSample.kt

**Comment by Docile-Alligator** [comment]
Thank you so much for your help!!!!
