### ISSUE TITLE
ImagesPlugin class is missing

### ISSUE THREAD

**Issue by chrisbarth01** [noties/Markwon#343]
I'm trying to implement images in my markdown view but it seems that the **````ImagesPlugin.create()````** is missing.

![image](https://user-images.githubusercontent.com/49325171/110636609-be2e5e80-81ac-11eb-87e4-906ab4f7cdfc.png)

**Comment by noties** [comment]
Hello @chrisbarth01 ,

you need the `io.noties.markwon:image:$version` artifact. The list of available artifacts is available in the [install section](https://noties.io/Markwon/docs/v4/install.html) of documentation

**Comment by chrisbarth01** [comment]
I see. I'd suggest that you add them in front of the repo so many others can find it without having to dig that deep. Thanks.

**Comment by chrisbarth01** [comment]
Oh... Just saw it. I guess I didn't read between the lines. Thank you!

**Comment by chrisbarth01** [comment]
Hello again @noties, I added the code for displaying GIFs 
```
.usePlugin(ImagesPlugin.create { plugin ->
                        plugin.addMediaDecoder(GifMediaDecoder.create())
                    })
```
and I get a crash which says
``` 
java.lang.IllegalStateException: `pl.droidsonroids.gif:android-gif-drawable:*` dependency is missing, please add to your project explicitly if you wish to use GIF media-decoder
```

So I added the dependency
```
implementation 'pl.droidsonroids.gif:android-gif-drawable:1.2.22'
```

According to what I saw on the sample app, all I needed is `ImagesPlugin` but even after all these steps, I am unable to get the GIF to play. It rather shows an Image.

Am I doing something wrong?

**Comment by noties** [comment]
Hello @chrisbarth01 ,

if it is working for you in the sample app, then check your GIF:
* is it really an animated GIF?
* does response correctly respond with `Content-Type: image/gif` content type?
* `GifMediaDecoder.create()` accepts an optional `autoplay` argument, have you tried passing an explicit `true`?

**Comment by chrisbarth01** [comment]
The sample app I mean is the Markwon app. I saw the source code there. And [here's the link](https://i.gifer.com/XnWQ.gif) to the gif so you could confirm yourself.

**Comment by noties** [comment]
Hello @chrisbarth01 ,

there is a problem with the GIF that you had shared - gifer.com responds with `content-type: text/plain`. `markwon-image` relies on proper content type in order to trigger specific `MediaDecoder`. In this case response is decoded as a regular image (as a fallback strategy) and thus is not animated. You can try other image loaders or provide `ImagesPlugin` with a custom `defaultMediaDecoder` which handles such a case:

```java
final Markwon markwon = Markwon.builder(context)
  .usePlugin(ImagesPlugin.create(plugin -> {
    plugin.defaultMediaDecoder(new MyGifAwareDefaultMediaDecoder());
  }))
  .build();
```

Other available image loaders that have GIF support are:
* [glide](https://noties.io/Markwon/docs/v4/image-glide/)
* [coil](https://noties.io/Markwon/docs/v4/image-coil/)

**Comment by ChristophyBarth** [comment]
Hello @noties, I've added glide to my project but still don't get how to add it as the `GifDecoder`. Hope you can assist with that. Thanks. 

Also, how can I make images stretch to fit the screen size. I've noticed that a lot / almost all my images are aligned to the start of the screen. So, how can I make it align to the center of the screen? And also, how can I make it fit the screen edges (maybe zoom)? 

![Screenshot_2021-03-23-03-06-58-71_779daadb935d1ae03125a264c67e2d2a.jpg](https://user-images.githubusercontent.com/49325171/112081996-dfb42080-8b84-11eb-8b64-f1dcb03d4160.jpg) This is what the markdown shows for an image I cropped. Whereas loading it into an imageview, I can get something like this 👇 


![Screenshot_2021-03-23-03-08-29-71_779daadb935d1ae03125a264c67e2d2a.jpg](https://user-images.githubusercontent.com/49325171/112082270-5bae6880-8b85-11eb-8cbb-ae76a8e306f6.jpg)
Thank you in advance!

**Comment by noties** [comment]
Hello @chrisbarth01 ,

you can use special `ImageSizeResolver` that explicitly makes all images fit the width of the screen. How to use custom `ImageSizeResolver` is shown in [this sample](https://github.com/noties/Markwon/blob/205ae7b47a66d7bd33a0b21c7c9105929cd8a117/app-sample/src/main/java/io/noties/markwon/app/samples/image/ImageSizeResolverSample.kt). Then you can apply `100%` as width dimension, for example:

```kotlin
class FitWidthImageSizeResolver : ImageSizeResolverDef() {
  override fun resolveImageSize(drawable: AsyncDrawable): Rect {
    return resolveImageSize(
      ImageSize(
        ImageSize.Dimension(100F, UNIT_PERCENT),
        null
      ),
      drawable.result.bounds,
      drawable.lastKnownCanvasWidth,
      drawable.lastKnowTextSize
    )
  }
}
```

**Comment by ChristophyBarth** [comment]
Great! And how about the `GifDecoder`... can you help with that too? I appreciate your support.

**Comment by ChristophyBarth** [comment]
I'm using glide ATM and I can see that it can load GIFS... The thing is..., how to set it up.

**Comment by ChristophyBarth** [comment]
@noties ?

**Comment by noties** [comment]
@chrisbarth01 Glide handles GIF by own means, you should refer to the Glide documentation

**Comment by ChristophyBarth** [comment]
What I'm asking is for a sample code. I can't find a sample code for the GIF implementation.

**Comment by noties** [comment]
> What I'm asking is for a sample code. I can't find a sample code for the GIF implementation.

I think this is the logical end to an already closed issue. I cannot help you find what is easily accessible via search interface here on Github and via sample application

**Comment by ChristophyBarth** [comment]
It has been about 3 weeks now. I did search and couldn't find it. But, it's fine if you really can't help ;)
Thanks.

**Comment by noties** [comment]
https://github.com/noties/Markwon/search?q=glide+gif
