### ISSUE TITLE
Add copy button on right top of editor

### ISSUE THREAD

**Issue by ankush-dcoder** [noties/Markwon#344]
* **Markwon version**:  Latest

I am trying to display some markdown with code editors which works well as expected.

![1AFEF9DD-1F7D-4748-AF72-EBF354F519DD](https://user-images.githubusercontent.com/58418945/111062258-c7ca0600-84cd-11eb-8bd7-e21301b41c97.jpeg)

I need a copy button on right top of this code editor, to copy the code, how can i achieve that?
Also the md content is user generated, directly editing the content might not work but if there is a listener or extensibility build around code editor component in library, how do we achieve this particular task?

**Comment by noties** [comment]
Hello @ankush-dcoder ,

you can use the similar approach to [LinkTitleSample](https://github.com/noties/Markwon/blob/205ae7b47a66d7bd33a0b21c7c9105929cd8a117/app-sample/src/main/java/io/noties/markwon/app/samples/LinkTitleSample.java) in order to obtain text content of already rendered markdown node. Register your `SpanFactory` for the `FencedCodeBlock` and apply your logic in `onClick` method call

**Comment by ankush-dcoder** [comment]
Thanks for help @noties , this is helpful. As much as I can understand, register a SpanFactory for FencedCodeBlock and add one ClickableSpan to this spanfactory. This will allow the whole fenced block to be clickable and then I can handle the logic in onClick.

Is there a way to achieve something like:
1. Add a copy icon with ImageSpan on right top of FencedCodeBlock using this spanfactory and also apply clikablespan to it, so I can handle the click?
![fencedblock1](https://user-images.githubusercontent.com/58418945/111145181-fa4b3000-85ad-11eb-9757-3ea2b734aa35.jpg)

2. Add an element outside the FencedCodeBlock, like in the image, what should be right approach to implement this?
![fencedblock2](https://user-images.githubusercontent.com/58418945/111145189-fd462080-85ad-11eb-9545-e0398851cc3f.jpg)

**Comment by noties** [comment]
I think it is better to implement such feature with another span. I've uploaded a new sample indicating the pathway - [CopyCodeBlockSample](https://github.com/noties/Markwon/blob/master/app-sample/src/main/java/io/noties/markwon/app/samples/CopyCodeBlockSample.kt)

* no need for custom visitor to add text content that is further styled (see how `CorePlugin` creates a visitor for code blocks)
* actual code contents are not modified, thus there is no need to _clean_ it from manually added `copy` texts
* icon is drawn relatively easily 
* text content can be added also (drawn manually on Canvas, but still)

**Comment by ankush-dcoder** [comment]
Hi, 
Thanks @noties for explaining the case and sharing an example, worked like a charm. Also I feel this is a pretty command use case and will help the community. I understand how we can draw text and Square also probably to achieve Click to copy code button effect as in design shared.

2 things I still have doubts on:
1. I'm still not sure how can I draw this outside the code editor like in the design shared
2. Also here the code block itself is clickable, how can I make just the Click to copy code or code icon clickable.

**Comment by noties** [comment]
Hello @ankush-dcoder ,

1) you will need to have a different entity in you markdown outside code block (and thus code block span)
2) there are multiple options:
  * custom `TextView` and touch handling
  * custom `MovementMethod`, take a look at [Better-Link-Movement-Method](https://github.com/saket/Better-Link-Movement-Method) for a reference

**Comment by tutosrive** [comment]
It's ok?

https://github.com/tutosrive/mcbfc/
https://github.com/tutosrive/mcbfc/blob/master/app/src/main/res/layout/fenced_code_view.xml
https://github.com/tutosrive/mcbfc/blob/master/app/src/main/java/com/srm/markdown_render/BlockCodeEntry.kt
