### ISSUE TITLE
How to make code block scrollable?

### ISSUE THREAD

**Issue by kalucky0** [noties/Markwon#345]
In my app there are a lot of code blocks, but because of word wrapping most of it is completely unreadable and I would want to implement a horizontal scroll to all scroll blocks. How can I do that?

![App Screenshot](https://i.imgur.com/03O6JlC.jpg)

**Comment by noties** [comment]
Hello @kalucky0 ,

there is a sample that demonstrates how to do it with `MarkwonAdapter` in a RecyclerView: [RecyclerSample](https://github.com/noties/Markwon/blob/205ae7b47a66d7bd33a0b21c7c9105929cd8a117/app-sample/src/main/java/io/noties/markwon/app/samples/RecyclerSample.java)

**Comment by kalucky0** [comment]
Works like a charm
![Screenshot_20210326-000800_OSDev Wiki.jpg](https://user-images.githubusercontent.com/10831698/112554873-6c4e2100-8dc7-11eb-9dff-856ae5a1d4f9.jpg)
