### ISSUE TITLE
STATIC LAYOUT/DYNAMICLAYOUT support?

### ISSUE THREAD

**Issue by STICKnoLOGIC** [noties/Markwon#346]
* **Markwon version**: _{4.6.2}_
#ask
1. Render the MD in dynamiclayout/staticlayout for custom view
2. I want to know if its possible to render the MarkDown text in dynamicLayout/staticLayout using the Markwon?

By the way, the staticlayout/dynamiclayout is here
DynsmicLayout:
https://developer.android.com/reference/android/text/DynamicLayout

StaticLayout
https://developer.android.com/reference/android/text/StaticLayout

Reason to post it as issue:
Im just wandering since textview is inheritted the static/dynamiclayout(i dont know if its true), why should not use this to render markwon in customview?

**Comment by noties** [comment]
Hello @STICKnoLOGIC ,

`Markwon` creates `Spanned` text that you can use in a `StaticLayout` or `DynamicLayout`:

```kotlin
val spanned: Spanned = markwon.toMarkdown(md)
val staticLayout: StaticLayout = StaticLayout.Builder.obtain(
  spanned,
  0,
  spanned.length,
  // these are specific to your use-case
  TextPaint(),
  100
).build()
```

Please note that _dynamic_ content (images, tables) won't be displayed properly, as they require async communication with resulting layout. You can inspect `TableRowSpan` to see how you can possibly add support for dynamic content also

**Comment by STICKnoLOGIC** [comment]
Tnx @noties it works!! 


> Please note that dynamic content (images, tables) won't be displayed properly, as they require async communication with resulting layout. You can inspect TableRowSpan to see how you can possibly add support for dynamic content also

Yes. I use this to display some portion of the markdown.
