### ISSUE TITLE
Jetpack Compose support milestone

### ISSUE THREAD

**Issue by mochadwi** [noties/Markwon#348]
Now Compose in beta03, any milestone to support Jetpack Compose? :))))

**Comment by noties** [comment]
Hello @mochadwi ,

there are no plans to support Compose right now. It is still not available to general population, as it still requires canary version of Android Studio. But after things get _3-stable_ (as in `*.*.3` version rule for Android Studio), sure - Compose support is possible 😄

**Comment by mochadwi** [comment]
Awesome👍👏😊 thanks for the updates

**Comment by mochadwi** [comment]
For those wants to use Markdown support for Jetpack compose, as alternative we can use this https://github.com/jeziellago/compose-markdown

Or we can also still use TextView as AbstractComposeView or AndroidView in Compose afaik

**Comment by noties** [comment]
Thanks @mochadwi for the information. It seems, though, that the library is using `Markwon` internally so it might not be an alternative, more like an option. Still, good to know 👍 

I'm going to close this issue now until further developments

**Comment by mochadwi** [comment]
Compose now stables: https://developer.android.com/jetpack/androidx/releases/compose#versions 🎉

**Comment by mochadwi** [comment]
> For those wants to use Markdown support for Jetpack compose, as alternative we can use this https://github.com/jeziellago/compose-markdown
> 
> Or we can also still use TextView as AbstractComposeView or AndroidView in Compose afaik

other references: https://github.com/halilozercan/compose-richtext

**Comment by MaratTursynbek** [comment]
Maybe it is time to reopen? Would be really nice to get compose version of `toMarkdown` method that returns annotatedString.

**Comment by holywend** [comment]
I am also migrating to compose, :-)

**Comment by svenjacobs** [comment]
We're currently migrating a screen which uses Markwon from `Fragment` to Compose. It would be really nice if Markwon provides native Compose support, especially since Compose is now already at version 1.4 😃 Thank you! 🙏🏼

**Comment by svenjacobs** [comment]
If your only requirement is handling Markdown-style hyperlinks and **not** formatting, please have a look at my [MarkdownLinkText](https://gist.github.com/svenjacobs/918a05ca40e4b6916b31cc9481467533) composable which I just wrote as a workaround.
