### ISSUE TITLE
collapsing list

### ISSUE THREAD

**Issue by damionx7** [noties/Markwon#349]
Its a more of feature request. Is it possible to collapse headlines ( or # tags in markdown ) ?

**Comment by noties** [comment]
Hello @damionx7 ,

it is impossible to tell given your abrupt description. Please share as much details as possible if you wish to receive a possible resolution

**Comment by damionx7** [comment]
@noties I apologize for being so vague. This is what i meant. Expanded and Collapsed list items. 
Expanded

![Screenshot from 2021-04-12 08-12-12](https://user-images.githubusercontent.com/6530843/114333849-d2150980-9b38-11eb-82a0-8386e66b5ffb.png)

Collapsed

![Screenshot from 2021-04-12 08-12-18](https://user-images.githubusercontent.com/6530843/114333847-d0e3dc80-9b38-11eb-9f52-2f50c690797f.png)

**Comment by noties** [comment]
I think it is possible by using approach similar to the one in #181 issue. It will require quite an effort though and the result might not be 100% predictable across different devices because `TextView` was not designed with such functionality in mind
