### ISSUE TITLE
why do table markdown have to be done separately?

### ISSUE THREAD

**Issue by dreacot** [noties/Markwon#357]
* **Markwon version**: 4.6.2

1. Please specify expected/actual behavior

While marking down a file I expected that the entire file be marked down, but I'm seeing that tables are not marked down, rather from the documentation it says to markdown tables separately.

2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)

Try marking down a file that has both regular text and also a table in between the text.

Any reason in particular why that feature isn't currently supported?
Are there any plans to add the table markdown together with the basic markdown?

**Comment by noties** [comment]
Hello @dreacot ,

tables are supported via plugin. You can refer to the [Install](https://noties.io/Markwon/docs/v4/install.html) section of the documentation site. Make sure to pick `Tables` and see gradle script generated. Generated script goes into `build.gradle` of you project under `dependencies` block. Current latest version is `4.6.2`, so your script should look like:

```groovy
final def  markwon_version =  '4.6.2'
implementation "io.noties.markwon:core:$markwon_version"
implementation "io.noties.markwon:ext-tables:$markwon_version"
```

then go ahead and see samples that refer to tables. For example, the [TableLinkifySample](https://github.com/noties/Markwon/blob/master/app-sample/src/main/java/io/noties/markwon/app/samples/table/TableLinkifySample.java) and see how `Markwon` instance is created to support tables:

```java
final Markwon markwon = Markwon.builder(context)
    .usePlugin(LinkifyPlugin.create())
    .usePlugin(TablePlugin.create(context))
    // use TableAwareLinkMovementMethod to handle clicks inside tables
    .usePlugin(MovementMethodPlugin.create(TableAwareMovementMethod.create()))
    .build();
```

**Comment by dreacot** [comment]
hello @noties 

thanks for your help, it works now
