### ISSUE TITLE
Bold is not applied

### ISSUE THREAD

**Issue by hmasum52** [noties/Markwon#358]
* **Markwon version**: _4.6.2_

## Actual text:
```
Suppose , we live in a world where the precedence of  the operator\n**+** and  **-** is greater than that of ***** and **/**.You are given a mathematical expression where some operators are missing. You are asked to find the results.Can you do that?  

**The expression is 5?3*4-10?2=-24\nHere missing operators are presented as '?' symbol.Choose the correct operators .\n**\n
```

## expected/actual behavior(Rendered in web)
![image](https://user-images.githubusercontent.com/55390870/119171098-efb58700-ba85-11eb-8345-02a71f7f8094.png)

## markwon shows
![image](https://user-images.githubusercontent.com/55390870/119171202-1378cd00-ba86-11eb-9c47-728bab7ff428.png).

## Issues:
- ***** should be *
-  \*\*This is a bold text\*\* should be bold text

**Comment by noties** [comment]
Hello @Hmasum18 ,

thanks for the properly defined issue with reproduction steps and visual representation 👍 

The thing is - Markwon uses _opinionated_  markdown parsing based on [commonmark specification](https://spec.commonmark.org) and implementation by the [commonmark-java](https://github.com/atlassian/commonmark-java). Its vision of how certain markdown snippets are rendered can be checked in [the dingus tool](https://spec.commonmark.org/dingus/?text=Suppose%20%2C%20we%20live%20in%20a%20world%20where%20the%20precedence%20of%20%20the%20operator%0A**%2B**%20and%20%20**-**%20is%20greater%20than%20that%20of%20*****%20and%20**%2F**.You%20are%20given%20a%20mathematical%20expression%20where%20some%20operators%20are%20missing.%20You%20are%20asked%20to%20find%20the%20results.Can%20you%20do%20that%3F%20%20%0A%0A**The%20expression%20is%205%3F3*4-10%3F2%3D-24%0AHere%20missing%20operators%20are%20presented%20as%20%27%3F%27%20symbol.Choose%20the%20correct%20operators%20.%0A**%0A). 

if you follow that link you will see the output is the same as in Markwon. How to _fix_ that:
* `*****` is too ambitious, you can use escaped symbol - `**\***`, or change delimiters - `__*__`
* closing delimiter for strong emphasis cannot have space character (that includes new lines and tabs) directly before that. Remove new line character to make the whole paragraph bold

[result](https://spec.commonmark.org/dingus/?text=Suppose%20%2C%20we%20live%20in%20a%20world%20where%20the%20precedence%20of%20%20the%20operator%0A**%2B**%20and%20%20**-**%20is%20greater%20than%20that%20of%20**%5C***%20and%20**%2F**.You%20are%20given%20a%20mathematical%20expression%20where%20some%20operators%20are%20missing.%20You%20are%20asked%20to%20find%20the%20results.Can%20you%20do%20that%3F%20%20%0A%0A**The%20expression%20is%205%3F3*4-10%3F2%3D-24%5CnHere%20missing%20operators%20are%20presented%20as%20%27%3F%27%20symbol.Choose%20the%20correct%20operators%20.**%0A)

**Comment by hmasum52** [comment]
Ok. After replacing ** with __ and removing space character(space, newlines, tabs) directly before the closing delimiter solved my issues. 
![image](https://user-images.githubusercontent.com/55390870/119222974-c134bc00-bb18-11eb-8946-0a5d23b1e6bb.png)

__Thanks for your reply__ @noties. I am closing the issue now.
