### ISSUE TITLE
Unable to generate google calendar Link correctly 

### ISSUE THREAD

**Issue by gideonseven** [noties/Markwon#361]
* **Markwon version**: 4.6.2

1. unable to generate link to google calendar / meet correctly
2. raw body json (delete quotes)
"Nama kegiatan: Dental Health Education\r\nWaktu : 31 Juli 2021 06:42\r\nTandai di kalender [Google](https://www.google.com/calendar/render?action\u003dTEMPLATE\u0026text\u003dDental Health Education\u0026dates\u003d20210731T064204+0700/20210731T084204+0700\u0026ctz\u003dAsia/Jakarta\u0026location\u003dDental Health Education\u0026details\u003dCek kembali detail event di https://cicil.co.id/events/detail/57\u0026sf\u003dtrue\u0026sprop\u003dwebsite:www.cicil.co.id\u0026sprop\u003dname:CICIL)\r\nLokasi : Dental Health Education\r\nKota : KOTA SURABAYA"

using this builder 
```
 private val markwon by lazy {
        Markwon.builder(this)
                .usePlugin(ImagesPlugin.create {
                    it.addSchemeHandler(OkHttpNetworkSchemeHandler.create())
                })
                .usePlugin(LinkifyPlugin.create())
                .usePlugin(MovementMethodPlugin.create(BetterLinkMovementMethod.getInstance()))
                .usePlugin(ImagesPlugin.create {
                    it.defaultMediaDecoder(DefaultMediaDecoder.create(resources))
                }).build()
    }
```

```
  val node = markwon.parse(response.detail.body.orEmpty())
  val markdown = markwon.render(node)
  markwon.setParsedMarkdown(binding.tvContentDetail, markdown)
```

generated
![1s](https://user-images.githubusercontent.com/13301518/126622168-ad27bed0-6c91-4ed9-952a-4499b19a1ddc.PNG)

expected
![2s](https://user-images.githubusercontent.com/13301518/126622204-6b8fe9ce-0d9c-4136-ac48-642e72e43a81.PNG)

**Comment by noties** [comment]
Hello @gideonseven ,

your link should be URL-encoded. You can try your input in the [dingus](https://spec.commonmark.org/dingus/) to validate it

**Comment by gideonseven** [comment]
@noties thank you for your reply its actually works
