### ISSUE TITLE
How can I add custom attribute on an existing HTML tag?  

### ISSUE THREAD

**Issue by hakobyan1221** [noties/Markwon#373]
* **Markwon version**: _{4.6.2}_

1. I want to add a custom attribute on existing HTML tag e.g. I want to parse this &lt;h1 style = "color:#FFFFFF;"&gt;This is colored header&lt;h1&gt; 
2. When attribute is handled in custom tag handler header is not shown correctly because tag handler has been overridden.

**Comment by noties** [comment]
Hello @hakobyan1221 ,

unfortunately you would need to provide the whole tag handler in order to parse additional attributes
