### ISSUE TITLE
Please,add support for hiding unknown tags

### ISSUE THREAD

**Issue by hakobyan1221** [noties/Markwon#376]
* **Markwon version**: 4.6.2

1. HtmlPlugin parses all tags.
2. Please, add support to parse and show only those tags that are predefined in INLINE_TAGS or BLOCK_TAGS or VOID_TAGS.

**Comment by noties** [comment]
Hello @hakobyan1221 ,

would you say you need to parse only standard HTML tags and keep the rest untouched? It is not something that could be done easily. But it seems you might have better results by escaping non-standard HTML tags instead

**Comment by hakobyan1221** [comment]
Can you,please, tell how it's possible to skip non-standard HTML tags?

**Comment by noties** [comment]
For example, you could have a list of allowed tags. Then, before sending your markdown to the parser you could process it to substitute the `<` character to the `&lt;`. This way HtmlParser won't be involved and your input for unlisted tags would be the same

**Comment by hakobyan1221** [comment]
> For example, you could have a list of allowed tags. Then, before sending your markdown to the parser you could process it to substitute the `<` character to the `&lt;`. This way HtmlParser won't be involved and your input for unlisted tags would be the same

But in that case all html tags won't be processed by parser

**Comment by noties** [comment]
Yes, this is why you would need to process only non-supported tags. And ignore tags that should still be sent to the parser
