### ISSUE TITLE
Feature: Adding MAP view

### ISSUE THREAD

**Issue by damionx7** [noties/Markwon#382]
Hey @noties Bugging you again 😄 . Is it possible to add custm map view in markwon ?

**Comment by noties** [comment]
Hello @damionx7 ,

you could add static map representation as a regular image. Interactive map, I'm afraid, won't be possible. As you cannot add interactivity to a span inside a `TextView`. Not to mention embedding a `SurfaceView` which most interactive maps use. 

You best bet is to separate the features and display markdown and map in different views

**Comment by damionx7** [comment]
Thanks. I ended up replacing location with a static image.
