### ISSUE TITLE
Unorder list second level invalid when RecyclerView use MarkwonAdapter

### ISSUE THREAD

**Issue by ZuiRenA** [noties/Markwon#385]
* **Markwon version**: 4.6.2
- unordered list first level
    - unordered list second level1
    - unordered list second level2
``` PlainText
- unordered list first level
    - unordered list second level1
    - unordered list second level2
 ```

 When I use it, it doesn't display in standard Markdown format, I use `MarkwonAdapter` in RecyclerView for preview display
[Type before previewing](https://raw.githubusercontent.com/ZuiRenA/images/main/issues/noties%3AMarkwon/Screenshot_2022-01-11-15-31-24-785_%E5%8A%9B%E6%89%A3%20LeetCode.png)
[Preview effect](https://raw.githubusercontent.com/ZuiRenA/images/main/issues/noties%3AMarkwon/Screenshot_2022-01-11-15-31-28-605_%E5%8A%9B%E6%89%A3%20LeetCode.png)

**Comment by noties** [comment]
Hello @ZuiRenA ,

can you explain a bit more why it doesn't display in standard Markdown format? I see 2 levels of un-ordered list correctly on your preview image

**Comment by ZuiRenA** [comment]
Hello @noties 
The first picture is what I entered, the second picture is my preview of the input, the unordered list I entered has two levels, the content of the second level `-unordered list content1` is not correct when previewing is recognized as the second level of an unordered list

**Comment by noties** [comment]
Well, I see that the first and second lines are merged. You should validate your input - that you send exactly
```
- test
   - unordered list second level1
   - unordered list second level2
```

It seems you process the input somehow, and might be removing some parts of the original input, which breaks the parser and renderer. It also seems that `RecyclerView` has nothing to do here and if you use regular `TextView` you might see the same results

**Comment by ZuiRenA** [comment]
Thank you for your reply
I checked multiple times and pasted the available unordered list directly from the clipboard, still have this problem, and I tried using `TextView`, the same error occurred

**Comment by noties** [comment]
Hello @ZuiRenA ,

unfortunately I will need to close this issue, as you did not provide any details of how this would be reproduced. This had not gathered any feedback so I would assume there is an issue of your side. Which could be a library misconfiguration or a device specific bug
