### ISSUE TITLE
Text and background color not working

### ISSUE THREAD

**Issue by vivek-modi** [noties/Markwon#387]
Hey I am learning this Markwon. I tried to use this Markdown attribute but it's not working.

**buidl.gradle**

`implementation"io.noties.markwon:core:4.6.2"`

**activity.xml**

```
<TextView
        android:id="@+id/textView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="10dp"
        android:text="xyz"
        android:textSize="16sp"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
```

**Activity.kt**

```
val string = "# Hey my Name is Vivek"

val markwon = Markwon.builder(this)
                .usePlugin(object : AbstractMarkwonPlugin() {
                    override fun configureTheme(builder: MarkwonTheme.Builder) {
                        builder
                            .codeTextColor(Color.RED)
                            .codeBackgroundColor(Color.GREEN)
                    }
                })
                .build()
            markwon.setMarkdown(binding.textView, string) 
```

I tried to change colour of text and background is not working. Can someone please guide me.

**Comment by noties** [comment]
Hello @vivek-modi ,

both `codeTextColor` and `codeBackgroundColor` control the appearance of markdown code nodes - `this is code`
```
and this is code
```

If you wish to change text color and background of a `TextView` you should use specific to `TextView` settings - like you normally do for a TextView - `textColor` and `background`
