### ISSUE TITLE
Parsing html <code> and <codeblock> tag in Markwon Android

### ISSUE THREAD

**Issue by MinhPhamMobile** [noties/Markwon#398]
* **Markwon version**: 4.6.2 - Android 

I'm using markwon to extract the html tag <code> , but it does show as I experienced while using Markdown syntax code.
This is the html code I try to read 
`<p><code>code here</code></p>` 
Do you guys have any idea about configuration of Markwon builder to parse this tag
For other tags I tried, it run properly
`
<h1>heading1</h1><h2>heading2</h2><h3>heading3</h3><h4>heading4</h4><h5>heading5</h5><h6>heading1</h6><p><strong>asdasdasdasda</strong></p><p><i>asdasdasdasdasd</i></p><p><i><strong>bold italic</strong></i></p><p><a href="https://google.com/">https://google.com/</a></p><h6>asdsd</h6><p>asdasd</p><p><s>strike through</s></p><blockquote><p>content</p><p><s>strike through in quote</s></p><p><strong>bold in quote</strong></p><p><i>italic in quote</i></p><p><i><strong>bold italic in quote</strong></i></p></blockquote>`

@noties : sorry for direct mention you

**Comment by noties** [comment]
Hello @Sotatek-MinhPham ,

you can create a custom `TagHandler` for the `<code>` tag. For example - [HtmlRandomCharSize](https://github.com/noties/Markwon/blob/2ea148c30a07f91ffa37c0aa36af1cf2670441af/app-sample/src/main/java/io/noties/markwon/app/samples/html/HtmlRandomCharSize.java) shows how to use one.
