### ISSUE TITLE
Last bullet at end of markdown is rendered too small

### ISSUE THREAD

**Issue by litrik** [noties/Markwon#40]
If the markdown ends with a bullet list, the last bullet is smaller than the others.

The markdown `"* Line 1\n* Line 2\n* Line 3"` gets rendered as 
![image](https://user-images.githubusercontent.com/688765/40424388-b7a5d1ca-5e95-11e8-845d-03b8afd8211b.png)

If you add an extra paragraph, the last bullet gets rendered correctly.

**Comment by noties** [comment]
Hello @litrik !

Can confirm. During investigation I also have noted that the first bullet is a big bigger than others. It seems to me that this bug is connected with the way TextView renders spans. Will investigate if we can have a workaround.

Thanks for the find

**Comment by noties** [comment]
![screen shot 2018-05-24 at 12 16 20](https://user-images.githubusercontent.com/7278986/40476293-5bdf6e66-5f4c-11e8-8e81-ce0291f77d1e.png)

**Comment by noties** [comment]
Hello @litrik !

I have uploaded a snapshot version in the https://github.com/noties/Markwon/tree/v1.0.6 branch. It will render bullet items properly (depend on text line height and not arguments that are passed to the Span).

**Comment by litrik** [comment]
The snapshot version fixes the issue. Thanks for your quick response!

**Comment by litrik** [comment]
Do you have any plans of releasing a 1.0.6 with this fix?
