### ISSUE TITLE
How to make Latex show in RemoteView？

### ISSUE THREAD

**Issue by zhouzhuo810** [noties/Markwon#403]
* **Markwon version**: 4.6.2

1. Please specify expected/actual behavior

I need to display the Latex formula in an Android AppWidget. I use Markwon inside the App, but I can't assign a value because I can't get the TextView object in the AppWidget. Is there any way to solve this?

2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)

```
Spanned xxx = markwon.toMarkdown("$$\n"+"xxx"+"\n$$");
RemoteViews views = new RemoteViews(context.getPackageName(), R.layout.appwidget_xxx);
views.setTextViewText(R.id.tv_xxx, xxx);
```

ask for help

**Comment by zhouzhuo810** [comment]
@noties ask for help

**Comment by noties** [comment]
Hello @zhouzhuo810 ,

unfortunately it won't be possible to display Markwon in a widget. Widgets use IPC (interprocess communication), so to display a spanned content - only platform spans can be used (that come from Android directly). Markwon uses own spans, so they won't be displayed - not only LaTeX, but others too. 

You can take a look at the [RemoteViewsSample](https://github.com/noties/Markwon/blob/2ea148c30a07f91ffa37c0aa36af1cf2670441af/app-sample/src/main/java/io/noties/markwon/app/samples/notification/RemoteViewsSample.java), which substitutes custom spans with platform ones. But still LaTeX won't be possible, as internally it uses `Drawable`, which cannot be sent between processes
