### ISSUE TITLE
LastLineSpacingSpan applies spacing on each list item when used on a Paragraph Node

### ISSUE THREAD

**Issue by pramod-knidal** [noties/Markwon#410]
* **Markwon version**: _{4.6.2}_ (latest as of this writing)

1. Please specify expected/actual behavior

Expected : Using [LastLineSpacingSpan](https://noties.io/Markwon/docs/v4/recipes.html#list-item-spacing) on a `Paragraph` node should add spacing only after paragraph texts.
Actual : `LastLineSpacingSpan` adds spacing even after `ListItem`s

2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)

Add the following code to the Markwon builder :

``` 
 private val paraEndSpacingPlugin =
    object : AbstractMarkwonPlugin() {
      override fun configureSpansFactory(builder: MarkwonSpansFactory.Builder) {
        val paragraphSpacing =
          appContext.resources.getDimension(R.dimen.markwon_paragraph_spacing).toInt()
                builder.appendFactory(Paragraph::class.java) { _, _ ->
                  LastLineSpacingSpan(paragraphSpacing)
                }
      }
    }

val  markwon = 
    Markwon.builder(sAppContext)
        .usePlugin(CorePlugin.create())
        .usePlugin(paraEndSpacingPlugin)
        .build()
```

and use that markwon to render text paragraphs and lists. See that the list item spacing would also have increased.

**Comment by noties** [comment]
Hello @pramodshri-tgsys ,

there seems to be a confusion about paragraphs. Here a `Paragraph` represents a commonmark node, which is not always the same as a text paragraph. You can inspect the [dingus](https://spec.commonmark.org/dingus/?text=Hello%0A%0A-%20first%0A-%20two%0A-%20three%0A%0A) AST tab to see that each list item has a `paragraph` child. 

Thus, if you are applying `LastLineSpacingSpan` for a `Paragraph` node - each list item would have line spacing after it - as each of them contains a `Paragraph`
