### ISSUE TITLE
Spacing after last node of TableBlock (say) isn't consistent with previous node spacing of similar type

### ISSUE THREAD

**Issue by pramod-knidal** [noties/Markwon#411]
**Markwon version**: _4.6.2_

### Please specify expected/actual behavior

When `AbsoluteSizeSpan` is used to apply spaces between blocks as explained [here](https://github.com/noties/Markwon/issues/337#issuecomment-773991312), it works fine for all nodes except the last node. For the last node, regardless of what spacing is set for the absoluteSizeSpan, the spacing after the last node appears to have applied 2 times.

### Please specify conditions/steps to reproduce (layout, code, markdown used, etc)

Below is the custom block handler we use for applying spacing after table blocks.

```
  private class SpacingBlockHandler : MarkwonVisitor.BlockHandler, KoinComponent {

    val context: Context by inject()

    override fun blockStart(visitor: MarkwonVisitor, node: Node) {
      // ensure that content rendered on a new line
      visitor.ensureNewLine()
    }

    override fun blockEnd(visitor: MarkwonVisitor, node: Node) {
      if (visitor.hasNext(node)) {
        visitor.ensureNewLine()
      }
      // Spacing after TableBlock
      if (node is TableBlock) {
        val tableSpacing = context.resources.getDimension(R.dimen.markwon_spacing_paragraph).toInt()
        setEndAbsoluteSpan(visitor, tableSpacing)
      }
    }

    private fun setEndAbsoluteSpan(visitor: MarkwonVisitor, spacing: Int) {
      visitor.forceNewLine()
      visitor.builder().setSpan(AbsoluteSizeSpan(spacing), visitor.length() - 1, visitor.length())
    }
  }
```

For the text below  (without the start & end triple backticks of course), the spacing after the first table is what is expected. However, the spacing after the last table node is not as expected. It appears to have doubled.

```
Colons can be used to align columns.

| Tables        | Are           | Cool |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

There must be at least 3 dashes separating each header cell. The outer pipes (|) are optional, and you don't need to make the raw Markdown line up prettily. You can also use inline Markdown.

Markdown | Less | Pretty
--- | --- | ---
*Still* | `renders` | **nicely**
1 | 2 | 3

```

Screenshot of how it looks like with layout bounds enabled.

![Screenshot_20220810-110423](https://user-images.githubusercontent.com/73175526/183823878-02c70113-3060-418c-9c93-6a43c1ba57a5.png)

#### Some Observations

1. If the `tableSpacing` value is set to `0`, the spacing after the first table would change to `0`. However, the spacing after the last table remains the same.
2. The issues is there even with other blocks like `BlockQuote` and `FencedCodeBlock`
3. `LastLineSpacingSpan` produces a similar result

**Comment by pramod-knidal** [comment]
I figured out a work around for the above problem. Leaving a note here in case it helps anyone.

I add a Dummy `SpecialBlockEndMarkerSpan` at the block end which basically does nothing and in the `beforeSetText` plugin call, I set the bottom padding. Below is the code.

1. The block handler which adds the `SpecialBlockEndMarkerSpan`

```
  private class SpacingBlockHandler : MarkwonVisitor.BlockHandler, KoinComponent {

    val context: Context by inject()
    private val standardSpacing =
      context.resources.getDimension(R.dimen.markwon_block_standard_spacing).toInt()

    override fun blockEnd(visitor: MarkwonVisitor, node: Node) {
      if (visitor.hasNext(node)) {
        visitor.ensureNewLine()
      }
      if (node is TableBlock) {
        if (visitor.hasNext(node)) {
          setEndAbsoluteSpan(visitor, standardSpacing)
        } else {
          visitor.builder().setSpan(SpecialBlockEndMarkerSpan(), visitor.length() - 1)
        }
      }
    }

    private fun setEndAbsoluteSpan(visitor: MarkwonVisitor, spacing: Int) {
      visitor.forceNewLine()
      visitor.builder().setSpan(AbsoluteSizeSpan(spacing), visitor.length() - 1, visitor.length())
    }
  }

  private class SpecialBlockEndMarkerSpan
```

2. Implement a custom plugin which adds the padding in the `beforeSetText`

```
class SpacingPlugin : AbstractMarkwonPlugin(), KoinComponent {

  private val context: Context by inject()
  private val standardSpacing =
    context.resources.getDimension(R.dimen.markwon_block_standard_spacing).toInt()

  override fun beforeSetText(textView: TextView, markdown: Spanned) {
    // If there are any special block end marker spans, add a bottom padding to the textView
    val endMarkerSpans = markdown.getSpans<SpecialBlockEndMarkerSpan>()
    if (endMarkerSpans.isNotEmpty()) {
      textView.setPadding(0, 0, 0, standardSpacing)
    }
  }

  override fun configureVisitor(builder: MarkwonVisitor.Builder) {
    builder.blockHandler(SpacingBlockHandler())
  }
}
```

**Comment by pramod-knidal** [comment]
BTW, thanks for this wonderful library @noties

**Comment by noties** [comment]
Hello @pramodshri-tgsys ,

it seems there is some special handling of `AbsoluteSizeSpan`. Sometimes, if it is applied to just `new-line` character, the results might be strange. In your example, you could add some additional character after enforced new line and apply span to it, for example:

```java
  if (node instanceof TableBlock) {
    visitor.builder().append("\n\u00a0");
    visitor.builder().setSpan(
      new AbsoluteSizeSpan(48, true),
      // NB! apply to only `unbreakable` space character - `\u00a0`, but not
      //  new-line character
      visitor.length() - 1,
      visitor.length()
    );
  // it is also important to not `ensure` before checking if it is a TableBlock, as
  // this would lead to 2 new lines after TableBlock, if it has content after it
  } else if (visitor.hasNext(node)) {
    visitor.ensureNewLine();
  }
```


> BTW, thanks for this wonderful library @noties 

You are welcome 😉
