### ISSUE TITLE
Arabic latex support

### ISSUE THREAD

**Issue by AzharRagab** [noties/Markwon#412]
* **Markwon version**: _{4.6.2}_

I am using `JLatexMathPlugin` to display math formula it works well in english equation but when i want to display Arabic equation The Arabic letters appears well, but the numbers still appears in English.

FYI: the Arabic number is displayed well in Markwon without latex plugin but when using `JLatexMathPlugin` the arabic number doesn't display in Arabic.

Below is the code i used 
```
 Markwon.builder(context) // required plugin to support inline parsing
                .usePlugin(MarkwonInlineParserPlugin.create())
                .usePlugin(HtmlPlugin.create()) // support html
                .usePlugin(JLatexMathPlugin.create(textSize) { builder -> // ENABLE inlines
                    builder.inlinesEnabled(true)
                })
                .usePlugin(SoftBreakAddsNewLinePlugin.create()) // to add new line
                .build()
```
Screenshot of how it looks like with english equation.
<img width="363" alt="Screen Shot 2022-08-18 at 5 35 49 PM" src="https://user-images.githubusercontent.com/90331306/185435814-32fbb039-792e-48d4-b27a-8341a7306a5a.png">

Screenshot of how it looks like with arabic equation.
<img width="363" alt="Screen Shot " src="https://user-images.githubusercontent.com/90331306/185435113-db854674-be81-4b0d-8f5d-c9f5ec474d82.png">

any solution for this @noties ?

**Comment by noties** [comment]
Hello @AzharRagab ,

I'm not really versed in Arabic and do not know how it is rendered in LaTeX. But it appears that you should be able to achieve that by manually specifying text for the power values, like this:

```tex
2^{2} + 3^{yep}
```
=
```math
2^{2} + 3^{yep}
```
