### ISSUE TITLE
How to remove spacing between list item parent and children?

### ISSUE THREAD

**Issue by jja08111** [noties/Markwon#413]
* **Markwon version**: 4.6.2

There is an enter character between list item parent and children like below.

```
- [x] checked
- [ ] unchecked
- jj
- parent
  - child1
  - child2
- bottom
```

### Actual

![image](https://user-images.githubusercontent.com/57604817/185851339-91e26c6c-5ca1-4e91-8a94-e82871193bb4.png)

### Expected

![image](https://user-images.githubusercontent.com/57604817/185851696-39a6ac49-b3a3-4567-ae7f-35d55df3cb00.png)

I can remove the space like the expected screenshot by using [FirstLineSpacingSpan](https://github.com/noties/Markwon/issues/143#issuecomment-506666146), but text selection is weird when using the hack.

![image](https://user-images.githubusercontent.com/57604817/185852206-d82d5fa5-7ac5-4ecb-a688-ef829a191bf6.png)

How can I remove the space? Thanks for your awesome plugin.

**Comment by noties** [comment]
Hello @jja08111 ,

I'm not sure there is something we can do here. Text selection is unpredictable and works differently between Android versions and each individual device. 

But still, what does it copy in your last screenshot?
