### ISSUE TITLE
Unable to load images even after using images plugin

### ISSUE THREAD

**Issue by roshnibatra** [noties/Markwon#414]
* **Markwon version**: _4.6.2

I wanted images to load after adding image plugin but thats not happening, if i am adding html plugin it identifies the link and makes it clickable 

code snippet used 

        markwon = Markwon.builder(applicationContext)
            .usePlugin(CorePlugin.create())
              .usePlugin(ImagesPlugin.create())
            .usePlugin(HtmlPlugin.create())
            .usePlugin(object : AbstractMarkwonPlugin() {
                                override fun configure(registry: MarkwonPlugin.Registry) {
                    registry.require(ImagesPlugin::class.java
                    ) { imagesPlugin -> imagesPlugin.addSchemeHandler(NetworkSchemeHandler.create()) }
                }
                override fun configureConfiguration(builder: MarkwonConfiguration.Builder) {
                    builder.asyncDrawableLoader(AsyncDrawableLoader.noOp())
                    builder.linkResolver(LinkResolverDef())
                }
            })
            .build()

I tried multiple combination of glide as well but that also didnt work 
Let me know what i am doing wrong here 
Tried removing html plugin, in that case nothing comes in place of image link provided 

tried to render readme section from sample app as well as few from network call for e.g 
[<img src="https://srm-sbox-cdn.a4b.io/images/library//cf27a33b-5fcc-4786-9610-c29a81d571f5.png" width="100%">](https://srm-sbox-cdn.a4b.io/images/library//cf27a33b-5fcc-4786-9610-c29a81d571f5.png)

**Comment by noties** [comment]
Hello @roshnibatra ,

`builder.asyncDrawableLoader(AsyncDrawableLoader.noOp())` applies a no-op image loading, so all your configuration is ignored. Remove this line
