### ISSUE TITLE
Q: Unable to parse both markdown and HTML within the same string

### ISSUE THREAD

**Issue by enamuls** [noties/Markwon#416]
* **Markwon version**: _{4.6.2}_

1. I want to parse a mixture of `markdown` and `HTML` within the same string. For example my sample string is 

`"<div>You are only eligible for a booster dose of COVID-19 vaccine if you meet the following requirements:</div> <ul><li> You are **over 16 years of age**.</li> <li>You have **completed 2 doses of your Covid-19 vaccination**.</li><li>It has been **more than 3 calendar months since your second dose and not one day before**.</li></ul><div>&nbsp;**For example** second COVID-19 vaccine completed on the 15th of July, eligible to receive your booster from (and not before) the 15th of October.&nbsp;</div><div> If you attend your appointment earlier, you will be turned away until you are eligible.</div><p>For more information on eligibility, please refer to the [Department of Health website](https://www.health.gov.au/sites/default/files/documents/2021/10/atagi-recommendations-on-the-use-of-a-booster-dose-of-covid-19-vaccine.pdf)</p>"`

3. I have used below to parse the string but it only seem to parse HTML but not markdown at all

`Markwon.builder(context).usePlugin(HtmlPlugin.create()).build()`

4. The output I get is like below on a `textView`

![Screenshot_20221019_103221](https://user-images.githubusercontent.com/31089628/196583652-25ac8a67-35c2-444c-bf7c-4188318558ed.png)

**Comment by noties** [comment]
Hello @sam911 ,

you cannot mix html and markdown in such a way. Take a look at the [reference implementation](https://spec.commonmark.org/dingus/?text=%3Cdiv%3EYou%20are%20only%20eligible%20for%20a%20booster%20dose%20of%20COVID-19%20vaccine%20if%20you%20meet%20the%20following%20requirements%3A%3C%2Fdiv%3E%20%3Cul%3E%3Cli%3E%20You%20are%20**over%2016%20years%20of%20age**.%3C%2Fli%3E%20%3Cli%3EYou%20have%20**completed%202%20doses%20of%20your%20Covid-19%20vaccination**.%3C%2Fli%3E%3Cli%3EIt%20has%20been%20**more%20than%203%20calendar%20months%20since%20your%20second%20dose%20and%20not%20one%20day%20before**.%3C%2Fli%3E%3C%2Ful%3E%3Cdiv%3E%26nbsp%3B**For%20example**%20second%20COVID-19%20vaccine%20completed%20on%20the%2015th%20of%20July%2C%20eligible%20to%20receive%20your%20booster%20from%20(and%20not%20before)%20the%2015th%20of%20October.%26nbsp%3B%3C%2Fdiv%3E%3Cdiv%3E%20If%20you%20attend%20your%20appointment%20earlier%2C%20you%20will%20be%20turned%20away%20until%20you%20are%20eligible.%3C%2Fdiv%3E%3Cp%3EFor%20more%20information%20on%20eligibility%2C%20please%20refer%20to%20the%20%5BDepartment%20of%20Health%20website%5D(https%3A%2F%2Fwww.health.gov.au%2Fsites%2Fdefault%2Ffiles%2Fdocuments%2F2021%2F10%2Fatagi-recommendations-on-the-use-of-a-booster-dose-of-covid-19-vaccine.pdf)%3C%2Fp%3E).

Your whole input is parsed as html. Given your use-case it seems it is better to pick one - either HTML or markdown and use it exclusively
