### ISSUE TITLE
Unable to parse \textbf{} LaTex tag in the release app.

### ISSUE THREAD

**Issue by kundan1293** [noties/Markwon#417]
* **Markwon version**: 4.6.2

1. I am using \textbf{} tag to set font style bold, it's working fine in the developer mode but when I build signed apk then its not working.
2. When I checked log of release app then got error:
    E/MarkWon: \textbf{Staining}
   E/MarkWon: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference

**Comment by noties** [comment]
Hello @kundan1293 ,

it is hard to tell what might cause it - the error message does not say much. But as dev builds are OK, there might be something in your build that affects release versions, like proguard, or other code/resource processor
