### ISSUE TITLE
Can I use another Android View in between Markwon RecyclerView?

### ISSUE THREAD

**Issue by Meet-Miyani** [noties/Markwon#419]
* **Markwon version**: 4.6.2

1. I saw the demo app, in which there a Recycler-View example, and your repo says that it's not the Web view, which could be meant that your are using the different kind of view together to render the Markdown Output. E.G. : ImageView, TextView, etc

2. So my question is, can I add my custom view in between ? Let's say I want to add my custom shape view, or the video view along the Markwon Recyclerview, E.g. After my 2 paragraphs of information I want to add a Video View and then continue with the remaining content.

So is it possible ? How can I achieve that ?

**Comment by Meet-Miyani** [comment]
Is it possible?

**Comment by noties** [comment]
Hello @Meet-Miyani ,

it is possible. You can take a look at how the `markwon-recycler` does it. In short, it _reduces_ parsed markdown to a list of nodes. And uses specific views for each node. `markwon-recycler` does not allow any other content except a child of `Node`, so you could create own `Node` subclass and manually place it in a list of nodes. Or adjust the solution to your means - `markwon-recycler` does not use any internal API, it relies on public API which can be used freely

**Comment by Meet-Miyani** [comment]
Sure, I'll try to make some changes

**Comment by lishangwl** [comment]
> * **Markwon version**: 4.6.2
> 
> 1. I saw the demo app, in which there a Recycler-View example, and your repo says that it's not the Web view, which could be meant that your are using the different kind of view together to render the Markdown Output. E.G. : ImageView, TextView, etc
> 2. So my question is, can I add my custom view in between ? Let's say I want to add my custom shape view, or the video view along the Markwon Recyclerview, E.g. After my 2 paragraphs of information I want to add a Video View and then continue with the remaining content.
> 
> So is it possible ? How can I achieve that ?

Did it work?
