### ISSUE TITLE
No GIF playback with textIsSelectable=true

### ISSUE THREAD

**Issue by tariqueislam** [noties/Markwon#42]
I am having an issue displaying GIF with textIsSelectable=true in TextView. The GIF loads, but it does not play. If I make textIsSelectable false, it plays just fine. I have tried both in emulator and actual device with version 1.0.5

**Comment by noties** [comment]
@tariqueislam Unfortunately I must postpone this fix for a later release. I have stumbled with this issue and could not find a solution. The information that I have obtained:

* When `textIsSelectable=true` TextView internally creates an `Editor` (which makes text _kinda_ editable)
* When there is an `Editor` attached to a TextView `View#invalidate` just doesn't seem to work no matter what
* Changing `layer_type` of a TextView doesn't seem to change anything (only getting worse, with `LAYER_TYPE_SOFTWARE` nothing is displayed at all)
* In `DrawableScheduler` we could've used something like this:
```java
if (view.isTextSelectable()) {
    view.setTextKeepState(view.getText(), TextView.BufferType.SPANNABLE);
} else {
    view.invalidate();
}
```
But this leads to awful performance (with each update of a GIF (each GIF that markdown contains!) text is invalidated) and even more bugs like fixed scroll position (cannot scroll past selection even after selection is cleared), scroll position always returns to the first created selection, etc.

So, I would gladly accept any suggestions for possible fixes of this issue, meanwhile 🤷‍♂️ , nothing can be done now (at least for _now_!)

🙌

**Comment by tariqueislam** [comment]
It is working now with textIsSelectable=true. I have tested on v2.0.0

**Comment by noties** [comment]
Hello @tariqueislam !

Like.. really? What about actual text selection? Is it preserved in a TextView with playing GIF? What about performance?

**Comment by tariqueislam** [comment]
Text selection worked, and I was able to copy text. I did not feel any delay, but I only used one GIF. Below is what I tried:
```
Cute cat 
![CaText](https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif)
```

**Comment by noties** [comment]
It actually does work 🤔
