### ISSUE TITLE
Coil gifs

### ISSUE THREAD

**Issue by DanielJ06** [noties/Markwon#424]
* **Markwon version**: 4.6.2

Hey! I'm currently using coil as the image renderer, but I can't figure out how to render gifs.
I tried this image loader following coil docs:
```
val coilLoader = ImageLoader.Builder(context)
        .apply {
            crossfade(true)
            components {
                if (SDK_INT >= 28) {
                    add(ImageDecoderDecoder.Factory())
                } else {
                    add(GifDecoder.Factory())
                }
            }
        }.build()
    //...
    .usePlugin(CoilImagesPlugin.create(context, coilLoader))
   //...
```
The gif renders but never starts

The gif is declared this way in my markdown: `\n\n![Gif Aplicação](https://victor-harry.s3.sa-east-1.amazonaws.com/V%C3%ADdeo+do+WhatsApp+de+2023-01-23+%C3%A0(s)+22.47.05.gif)\n\n`

I don't know if I have to do an extra step to work with Markwon, or if my gif is declared wrong, can someone help me?
thx

**Comment by wax911** [comment]
I thought of using `.target()` and providing a `object : Target {  }` to check if the `onSuccess(drawable: Drawable)` instance was an `AnimatedDrawable` and triggering the `.start()` method for it since this is similar to how Glide would handle gifs in Markwon. Unfortunately this didn't work 😞

**Comment by noties** [comment]
Hello @wax911 ,

you would need to use `Animatable` interface to check if loaded drawable is a GIF. And call `start` if you wish for it to start playing
