### ISSUE TITLE
How to break apart markdown so accessibility services can focus on each individual heading

### ISSUE THREAD

**Issue by dmohan12** [noties/Markwon#425]
Markwon version: 4.6.2

Right now my markdown with multiple headings gets rendered in a single text view.  So when I try to use accessibility services like Android talkback, everything gets focused inside one giant block because all of the content is contained inside a single text view. Is it possible to break apart markdown content into multiple focusable chunks?

**Comment by noties** [comment]
Hello @dmohan12 ,

you could render each markdown block in an individual `TextView`, do take a look at the - https://github.com/noties/Markwon/blob/master/markwon-core/src/main/java/io/noties/markwon/MarkwonReducer.java

You would need to customize the rendering and layout though. Something like this:

```kotlin
// pseudo code
val container: ViewGroup = TODO()
for (block in markdownBlocks) {
  val textView: TextView = createTextView(block)
  container.addView(textView)
}
```
