### ISSUE TITLE
Can Markwon support line spacing?

### ISSUE THREAD

**Issue by lanhuaguizha** [noties/Markwon#427]
When I use Markwon to load text into textView, the default looks like this:

![Screenshot_20230323_121832](https://user-images.githubusercontent.com/9106780/227102817-998cc979-cc4e-4545-895b-c285e0c8daec.jpg)

But what I want to achieve is as follows:

![Screenshot_20230323_121911](https://user-images.githubusercontent.com/9106780/227103043-cce41748-b6f3-4f14-803e-2faa9c835c96.jpg)

How should I use Markwon to achieve this line spacing effect ?

**Comment by noties** [comment]
Hello @lanhuaguizha ,

you can use normal `TextView` line spacing attributes, parsed markdown would automatically use them
