### ISSUE TITLE
Help with syntax HighLight using Prism4j

### ISSUE THREAD

**Issue by Javi3rV** [noties/Markwon#431]
* **Markwon version**: latest one

I need help with syntax highlight plugin, I add the annotation in the build.gradle file, then I add it like:
```
@PrismBundle(
    includeAll = true,
    grammarLocatorClassName = ".MyGrammarLocatorTest"
)
class MyGrammarLocator {}
```
But "MyGrammarLocatorTest" is never generated..

**Comment by noties** [comment]
Hello @Javi3rV ,

you need to use bundler in order to generate the class.

For java (in `build.gradle`):
```gradle
dependencies {
  annotationProcessor 'io.noties:prism4j-bundler:2.0.0'
}
```

for kotlin:
```
apply plugin: 'kotlin-kapt'

dependencies {
  kapt 'io.noties:prism4j-bundler:2.0.0'
}
```
