### ISSUE TITLE
Table not rendred at all

### ISSUE THREAD

**Issue by wessel007** [noties/Markwon#436]
* **Markwon version**: _{4.6.2}_

1. Supposed rendred table in TextView android Kotlin not working as expected as in the attached screen below.

2. this is the project files code activity XML layout and Implementation used : 

Im using Markwon TablePlugin :
final def markwon_version = '4.6.2'
 - implementation
implementation"io.noties.markwon:core:$markwon_version"
implementation"io.noties.markwon:ext-tables:$markwon_version"

* **Activity** :_{ 
package com.example.markdowntest
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.WindowCompat
import com.example.markdowntest.databinding.FragmentFirstBinding
import io.noties.markwon.Markwon
import io.noties.markwon.ext.tables.TablePlugin

class MarkDownActivity : AppCompatActivity() {

    private lateinit var binding: FragmentFirstBinding
    private lateinit var markwon: Markwon
    override fun onCreate(savedInstanceState: Bundle?) {
        WindowCompat.setDecorFitsSystemWindows(window, false)
        super.onCreate(savedInstanceState)

        binding = FragmentFirstBinding.inflate(layoutInflater)
        setContentView(binding.root)

        val markdownText = """
  To solve this problem, let's first look at how the sequence progresses:

| n  | Sequence |
|----|----------|
| 1  | 1        |
| 2  | 2        |
| 3  | 4        |
| 4  | 9        |

From the table, we can try to find any particular pattern between the `n` (term position) and the sequence (term value).

1. First term: 1² = 1
2. Second term: 1² + 1 = 2
3. Third term: 2² = 4
4. Fourth term: 2² + 1 = 9

It seems that the sequence alternates between the squares of natural numbers and the squares of natural numbers plus 1, starting with 1².

Given this pattern, let's find the next two numbers in the sequence:

5. Fifth term: 3² = 9
6. Sixth term: 3² + 1 = 10

So, the next two numbers in the sequence are 9 and 10. Now let's add these to the table:

| n  | Sequence |
|----|----------|
| 1  | 1        |
| 2  | 2 |
| 4  | 9        |
| 5  | 9        |
| 6  | 10       |
""".trimIndent()

        markwon = Markwon.builder(this)
            .usePlugin(TablePlugin.create(this))
            .build()

        val renderedText = markwon.toMarkdown(markdownText)
        markwon.setMarkdown(binding.textviewFirst, renderedText.toString())

    }
}
}_

* **XML Layout**:_{

<?xml version="1.0" encoding="utf-8"?>
<androidx.core.widget.NestedScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MarkDownActivity">

    <androidx.coordinatorlayout.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:padding="16dp">

<ScrollView
    android:layout_width="match_parent"
    android:layout_height="match_parent">
        <TextView
            android:textIsSelectable="true"
            android:textColor="@color/black"
            android:id="@+id/textview_first"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="200dp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="parent" />
</ScrollView>
    </androidx.coordinatorlayout.widget.CoordinatorLayout>
</androidx.core.widget.NestedScrollView>

* 
* }_

![image](https://github.com/noties/Markwon/assets/16480300/2a7d1d84-f64e-4a10-a7aa-d0b3aa516f9b)

**Comment by gt-zhenqiang** [comment]
hi，do you solve it
