### ISSUE TITLE
Latex matrix not rendered when I enable R8/Progaurd 

### ISSUE THREAD

**Issue by kinglighthill** [noties/Markwon#464]
* **Markwon version**: 4.3.0
When R8/Progaurd is enabled the latex matrix notations don't render but it renders when I disable it. Are there any progaurd rules available for the Markwon library and its extensions?

**Comment by Uche01** [comment]
@noties  I'm facing the same issue. Perhaps there are some proguard rules that needs to be set to enable matrices to render correctly on android. They render correctly in debug but in release after enabling proguard, matrix fails to render.

**Comment by joaozemind** [comment]
add the following line to your proguard 
`-keep class org.scilab.forge.jlatexmath.** { *; }
`

**Comment by kinglighthill** [comment]
Thank you @joaozemind it worked.

**Comment by AndraxDev** [comment]
I'm reopening this issue as "-keep class org.scilab.forge.jlatexmath.** { *; }" doesn't work for me. And the following rules also not working (based on the source code):

```
-keep class org.commonmark.node.** { *; }
-keep class io.noties.markwon.ext.latex.** { *; }
```
