### ISSUE TITLE
Support multi visitor

### ISSUE THREAD

**Issue by 337240552** [noties/Markwon#47]
I want to custom multi node processor, if i call visitor, the content is dumplicated.

`// trigger visit
        node.accept(visitor);
        node.accept(channelVisitor);`

**Comment by noties** [comment]
Hello @337240552 !

Yes, it's true. Each time visitor is used (each time `node.accept(visitor)` is called) content is duplicated as visitor is used to construct spannables. I did describe it earlier [here](https://github.com/noties/Markwon/issues/26#issuecomment-368075852). So if you can combine your visitors in one, then content won't be duplicated.
