### ISSUE TITLE
Single new line is ignored.

### ISSUE THREAD

**Issue by tobwithu** [noties/Markwon#479]
* **Markwon version**: 4.6.2

1. Please specify expected/actual behavior
  '\n' should be displayed as new line.
2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)
`Hello\nworld` is displayed as
![image](https://github.com/noties/Markwon/assets/8775150/103f3c0d-083b-4670-825f-4c4091e31651)
 Expected behavior is
![image](https://github.com/noties/Markwon/assets/8775150/b9ec1d15-9a7b-423b-859e-3a900d2da734)

Multiple new lines like '\n\n' works as expected.

**Comment by tobwithu** [comment]
I found that two or more spaces are needed for line break.

**Comment by travinhloc** [comment]
I have another way:
`usePlugin(HtmlPlugin.create())`
and then 
`val result = markdown.replace("\n", "<br>")`
