### ISSUE TITLE
More customizable headers

### ISSUE THREAD

**Issue by edenman** [noties/Markwon#50]
Great library.  I'm not crazy about these two things related to headers, though:

1) I'd like to control the typeface of the header.  I'm following this approach (https://github.com/noties/Markwon/issues/20) but it feels super clunky.  If I submitted a PR with this added to `SpannableTheme`, would that be acceptable?
2) I'd like to specifically control the textSize of the header.  AFAICT this isn't supported at all (the `HEADING_SIZES` multipliers are private and final).  Same question about PR-friendliness.

**Comment by edenman** [comment]
Submitted https://github.com/noties/Markwon/pull/51 thanks!

**Comment by noties** [comment]
I've just merged #51 into `v1.1.0` development branch. Thanks!

**Comment by noties** [comment]
Closing this issue now as the implementation is in the `1.1.0` release already
