### ISSUE TITLE
text\ntext not parsed correctly

### ISSUE THREAD

**Issue by DSofter** [noties/Markwon#54]
Hello, thank you for this amazing library! I really love it!

While I was using it, I found a small bug where the \n character is not rendered correctly. When I did `Markwon.setMarkdown(textView, "haha\ngaga");`, the outcome looks like this:

![image](https://user-images.githubusercontent.com/1687829/43502291-ea3e8096-950e-11e8-8f49-1940501046aa.png)

Where I would expect there's a newline between "haha" and "gaga". Could anyone show me how to fix this? Greatly appreciated!

**Comment by noties** [comment]
Hello @DSofter !

Thank you for your feedback! About the `new line` - yeah, it's not that it's parsed _incorrectly_. The thing is one new line (`\n`) character in markdown (according to the [spec](https://spec.commonmark.org/0.28/#soft-line-breaks)) is considered a `soft line break`. Currently Markwon does not provide a way to configure it (treat a soft line break as a hard one). But now I'm planning to add it to the next release. Meanwhile you can follow the generic advice from here (#20) and override `visit(SoftLineBreak softLineBreak)` to insert a `\n` character instead.

Also, you could try `haha\n\ngaga` and it will be rendered like you expect (double new line characters)

🙌

**Comment by DSofter** [comment]
@noties That's awesome to hear! I can't wait for the new release!

**Comment by DSofter** [comment]
Also, `haah\n\ngaga` wouldn't work because there will be some empty space between the two lines, and that's not what i want.

**Comment by DSofter** [comment]
@noties Nice. Look forward to the next release!

**Comment by noties** [comment]
Hello @DSofter !

I did publish a snapshot `1.1.1-SNAPSHOT` with ability to treat soft breaks as hard ones. Just construct a `SpannableConfiguration` and specify `softBreakAddsNewLine` option:

```java
final SpannableConfiguration configuration = SpannableConfiguration.builder(context)
        .softBreakAddsNewLine(true)
        .build();
```

**Comment by DSofter** [comment]
@noties Wow amazing! How can I get it?

![image](https://user-images.githubusercontent.com/1687829/43783973-e1672604-9a17-11e8-9ae1-39794d5d7aef.png)

**Comment by noties** [comment]
@DSofter you will have to add snapshot repository and you are good to go. How to do it is described in the [README](https://github.com/noties/Markwon#snapshot)

**Comment by DSofter** [comment]
@noties I tried. Works like a charm!
