### ISSUE TITLE
Text alignment on the Ordered list

### ISSUE THREAD

**Issue by carlosefonseca** [noties/Markwon#55]
Testing with the GitHub Cheatsheet, I'm seeing the numbers on the list not being baseline aligned to the text.

![](https://dsc.cloud/carlosefonseca/screen-2018-08-06_12.31.04-HAlBX.png)

Using 1.1.0. I am using BetterLinkMovement and a SpannableMarkdownVisitor subclass to handle soft breaks, but I don't think this should have anything to do with that.

**Comment by noties** [comment]
Hello @carlosefonseca !

I can confirm. What typeface do you use?

**Comment by carlosefonseca** [comment]
I'm currently using OpenSans.

**Comment by noties** [comment]
@carlosefonseca I did publish a snapshot version with the fix, can you please test it? Branch: [v1.1.1](https://github.com/noties/Markwon/tree/v1.1.1) and snapshot version: `1.1.1-SNAPSHOT`
