### ISSUE TITLE
Exception in selection mode

### ISSUE THREAD

**Issue by DSofter** [noties/Markwon#62]
Hello, thanks for helping me fix the newline bug, I really appreciate it!

I would like to report another bug that's affecting a lot of our users, and it's trigger when I enable the selection mode using TextView.setIsTextSelectable(true). The error is shown as below:

![image](https://user-images.githubusercontent.com/1687829/44694734-1e60b900-aa24-11e8-9f19-c806fb61d4ed.png)

Any idea why this is happening and how to fix this?

Really appreciate it!

**Comment by noties** [comment]
Hello @DSofter !

What version of the library are you using? Is this behavior reproducible on your device? What devices are affected?

I remember I saw some exception like this when I was investigating #42 . What I did is apply `textIsSelectable` in a `post` block after markdown is set:

```java
textView.post(() -> textView.setTextIsSelectable(true););
```

**Comment by noties** [comment]
This is one can also be the cause of the crash (maybe not even directly connected with Markwon): https://stackoverflow.com/questions/33821008/illegalargumentexception-while-selecting-text-in-android-textview#34072449

And linked issue on Android issue tracker: https://issuetracker.google.com/issues/37117740

I also remember that there was an error on 6.0 when user clicks outside of text selection popup (maybe it's the one).

**Comment by noties** [comment]
@DSofter any update on that?
