### ISSUE TITLE
Data Uri image loading doesn't work

### ISSUE THREAD

**Issue by Andy671** [noties/Markwon#74]
I am trying to implement raw images in my markdown. But I can't make it work. Can you give the working example of simple image loading?

**Comment by noties** [comment]
Hello @Andy671 !

Nice catch and you are absolutely right, it should be `data:image`. I will take a look and try to make it uniform with original data URI

**Comment by noties** [comment]
Hey @Andy671 ! Sorry it takes so much time. But I have updated SNAPSHOT version with the fix (2.0.1). I hope soon it will be released 🙌
