### ISSUE TITLE
Add support for Android X

### ISSUE THREAD

**Issue by garwedgess** [noties/Markwon#76]

**Comment by noties** [comment]
Hello @garwedgess !

This feature will be implemented at some point for sure, just not now. Migration to `android-x` is far from complete in a lot of applications. Plus, there is a tool that lets a project use _old_ compat libraries ([from here](https://developer.android.com/jetpack/androidx/migrate)):

```
android.useAndroidX=true
android.enableJetifier=true
```

and there is none the other way (`android-x` -> `compat`). Markwon (main artifact) only uses `support-annotations`, so there should be no problems with migration tool that Google provided

**Comment by garwedgess** [comment]
Hi @noties 

No problem, I'm not in a rush for it at the moment as I switched back to compat. I did try converting using Android Studios "migrate" option but it couldn't convert the annotations and therefore wouldn't build.

Good to know that you will implement support in the near future. Many thanks for the great library.

**Comment by noties** [comment]
Implemented in `4.0.0` version
