### ISSUE TITLE
Can't change code blocks margin

### ISSUE THREAD

**Issue by jahirfiquitiva** [noties/Markwon#77]
Hi

I recently started using this lib, but I'm unable to change the margin (left and right) of code blocks. I've set it as low as 1 (px if I'm not wrong) but it doesn't works.

Also, the annotation is set as `@Dimension` when it should be either `@Px`, I think.

Additionally I want to ask how can I increase the line spacing, because 2 code parts in different lines look like they are connected when they are not.

I've already set `android:lineSpacingMultiplier="1.2"` in the `TextView` but it doesn't work.

Thanks in advance.

Here's the setup

```kotlin
val theme = SpannableTheme.builder()
    .blockMargin(1)
    .codeMultilineMargin(1)
    .blockQuoteWidth(1)
    .build()
val config = SpannableConfiguration.builder(context)
    .softBreakAddsNewLine(true)
    .theme(theme)
    .build()
Markwon.setMarkdown(it, config, message.message)
```

Here's the text I'm showing
```markdown
`this is a test`
`and another one`

---

`this is a test`

`and another one`
```

And here's the final look:
![screenshot_20181111-203430](https://user-images.githubusercontent.com/10360816/48321733-16132580-e5f2-11e8-8517-5e665f89b76e.png)

**Comment by noties** [comment]
Hello @jahirfiquitiva !

The thing is: what you are referring is not a `code-block` but instead `inline-code`. You cannot customize it's margins via `SpannableTheme`. (And those margins are just space characters that are added to resulting output). If you would like to customize that you should create own subclass of `SpannableMarkdownVisitor` and override `#visit(Code code)` method and then provide your own logic. As a reference you can use code snippet from `sample-latex-module`: [L65-101](https://github.com/noties/Markwon/blob/e0563dca435c3378b07ef7f040964eabdd15fa1f/sample-latex-math/src/main/java/ru/noties/markwon/sample/jlatexmath/MainActivity.java#L65-L101).

You code could be as simple as:
```java
@Override
public void visit(Code code) {

    final int length = builder.length();

    builder.append(code.getLiteral());

    setSpan(length, factory.code(theme, false));
}
```

Please note that you should also store an instance of `SpannableFactory` (from `SpannableConfiguration` that you will receive in `SpannableMarkdownVisitor` constructor). it's a all a bit too much, I agree.  But things should change with plugin system that I've been planning for some time (scheduled for 3.0.0 version).

Also, if you want code blocks (and not inlines), you can use [fenced-code-block](https://spec.commonmark.org/0.28/#fenced-code-blocks) or [intended-code-block](https://spec.commonmark.org/0.28/#indented-code-blocks)

About the `@Dimension` annotation. I agree with you that `@Px` would be much better there.

🙌

**Comment by jahirfiquitiva** [comment]
Thanks for the info. I will try they. Can you help me with the line spacing?

**Comment by noties** [comment]
I'm actually investigating how to draw background for inline code that doesn't take the whole _visual_ height. So far I have found [this so post](https://stackoverflow.com/questions/19292838/android-spannablestring-set-background-behind-part-of-text) which should help solve the problem. I'm planning to add this to the library, but if you cannot wait, you can create own implementation and return it from `SpannableFactory#code(@NonNull SpannableTheme theme, boolean multiline);` method

**Comment by noties** [comment]
UPD: the post that I have provided won't help us here 😞 . Replacement span won't respect new lines. Unfortunately we need to look for another solution

**Comment by jahirfiquitiva** [comment]
Hmm.. I see... I hope you find something to support that

**Comment by jahirfiquitiva** [comment]
@noties 

Can't use this line
```java
setSpan(length, factory.code(theme, false));
```

Because the `setSpan`, `factory` and `theme` are private 🤦‍♂️ 😕

**Comment by jahirfiquitiva** [comment]
@noties 

Where am I supposed to put the instance of my `SpannableMarkdownVisitor` for `Markwon` to use it? 😕

**Comment by jahirfiquitiva** [comment]
@noties 

I just tried the customization, and as you said, it's way too complicated.
Maybe you could simply add a `boolean` parameter for whether one wants spaces before and after code blocks (inline and actual blocks)

**Comment by noties** [comment]
@jahirfiquitiva I'm sorry this customization is not on roadmap now

**Comment by noties** [comment]
This can be achieved in upcoming `3.0.0` release.

For example, remove spaces before and after incline code nodes:

```java
final Markwon markwon = Markwon.builder(context)
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configureVisitor(@NonNull MarkwonVisitor.Builder builder) {
                builder.on(Code.class, new MarkwonVisitor.NodeVisitor<Code>() {
                    @Override
                    public void visit(@NonNull MarkwonVisitor visitor, @NonNull Code code) {
                        final int length = visitor.length();
                        visitor.builder().append(code.getLiteral());
                        visitor.setSpansForNodeOptional(code, length);
                    }
                });
            }
        })
        .build();
```
