### ISSUE TITLE
Implementation of WYSIWYG Editor / Colored Text

### ISSUE THREAD

**Issue by NKnuelle** [noties/Markwon#79]
I have 2 issues I am working on:

1. I'd like to implement a WYSIWYG Editor based on Markwon.
- Switching from Plaintext to rendered Markdown is no problem.
- I like to have one view with buttons/functions so the user does not need to write Markdown or switch the views
- How to achieve that? Is there anything possible with the use of Markwon?
2. I'd like to be able to change the text color of normal text and to save it. Markdown is not capable nor designed to implement something like color. Are there any suggestions on how to achieve that? Maybe something like adding custom attributes/values to the markdown file/string and render them with a custom Markwon parser?

**Comment by noties** [comment]
Hello @NKnuelle !

1. WYSIWYG editor requires a lot of work. Well, good one for sure. As I see it Markwon can help you for _initial_ render. Meaning that markdown is used only to persist/transmit user input, but actual representation uses something different. For example your custom spans. After user finished his/her input you just create a markdown from it and use it in the future.

   There is also a possibility to use Markwon for continuous  parsing/rendering when user input changes. But. You won't be able to just `setText` after each change as actual _input_ will feel and act wrong from user perspective (jumping text, loosing cursor position, freezes, etc). So you will have to come up with some _diffing_ functionality that will apply changes to user input without modifying EditText.

2. It depends on your needs. If you want to change all text color in one widget I would recommend using `TextView#setTextColor`.

   If you want to change portions of input you could also create own markdown syntax for this functionality, implement own parser and create a proper markdown visitor to render it.

   You also could create a special HTML tag (or use existing), after all valid HTML is valid markdown. Create own HTML tag handler and use it along with custom HtmlRenderer.

**Comment by NKnuelle** [comment]
Hi @noties!
I just mentioned I owe an answer.

Thanks for your detailed reply! At the moment I am using this library: [Android HTML WYSIWYG](https://github.com/irshuLx/Android-WYSIWYG-Editor) and change some portions of it to my needs. This works quite good for now. 

I like Markdown at the idea behind it. But I think it is not designed for a WYSIWYG user experience - It's just a simple and easy to learn Markup language that can be used to format text so that  no WYSIWYG editor is needed. But I need something different in my project and so that html editor seems to fit the most.

Thank you for this library - especially the documentation! It's something I miss on the library I use now.. :)
