### ISSUE TITLE
Feature: image sizes

### ISSUE THREAD

**Issue by noties** [noties/Markwon#8]
Right now library doesn't support custom sizing of images. But it would be a good thing to support it.

There is no standard about image sizes in markdown. But as markdown supports inline HTML, library might be parsing HTML arguments specified in `<img>` tag:
* `width=`
* `height=`
* `style="width: ; height: ;"`

Another thing is what measure units to support. I suggest using:
* `%` percent
* `px` pixels (all other units `pt`, `em` defaults to pixels). And pixels should be treated as `dp` on Android

**Comment by liweijian** [comment]
Just wondering if maybe we could support the [Quiver-like](https://happenapps.com/) syntax as: `![IMAGE](quiver-image-url/CE441C33AC43C93AA252DD42A1E73DB9.jpg =618x164)` in the future?

**Comment by noties** [comment]
Hello @liweijian ,

there are multiple options to support images sizes now. 

For example [commonmark-java](https://github.com/atlassian/commonmark-java/tree/master/commonmark-ext-image-attributes) currently has an extension to specify width and height for an image - via `![alt](#){width=10 height=19}` syntax. They had it implemented as a delimiter processor, but unfortunately these attributes are available for HTML rendering only. We could adopt similar solution.

Then, currently commonmark allows specifying title for an image with `![alt](# "title")` syntax. So, for example `![IMAGE](quiver-image-url/CE441C33AC43C93AA252DD42A1E73DB9.jpg "=618x164")` would be a relatively easy addition. Not sure if it is a good application for title, but still it is a possibility.

And finally, a custom inline processor could be implemented. It would require quite a few changes. You can inspect code in [CloseBracketInlineProcessor](https://github.com/noties/Markwon/blob/master/markwon-inline-parser/src/main/java/io/noties/markwon/inlineparser/CloseBracketInlineProcessor.java) class. I would not modify it directly as it would diverge `Markwon` and `commonmark-java` code bases, which is not a very welcome thing at this point. Anyway, if you feel like it, you can _fork_ this class and adjust to your needs.

PS I should also mention that there is another way for specifying image size - HTML. `markwon-html` artifact supports `width` and `height` attributes from day 1

**Comment by ubuntudroid** [comment]
HTML has one problem: it seems to be applied *after* the whole image loading process. Meaning that e.g. transformations like rounded corners result in even the corners being scaled up/down together with the image to match the desired size.

So if you have

```html
<img src="https://picsum.photos/id/237/1024/800" width="100%" height="auto"></img>
```

and in e.g. your `CoilImagesPlugin` you define

```kotlin
CoilImagesPlugin.create(
    object : CoilImagesPlugin.CoilStore {
        override fun load(drawable: AsyncDrawable): LoadRequest {
            return LoadRequest.Builder(app)
                .transformations(RoundedCornersTransformation(14))
                .data(drawable.destination)
                .build()
        }

        override fun cancel(disposable: RequestDisposable) {
            disposable.dispose()
        }

    },
    ImageLoader.Builder(app)
        .okHttpClient(okHttpClient)
        .build()
)
```

you will end up with huge corners as everything (including the corners) is scaled up after the image has been loaded:

<img width="257" alt="CleanShot 2020-07-29 at 11 41 08@2x" src="https://user-images.githubusercontent.com/519867/88784542-73695480-d190-11ea-9c8c-a83e02be5803.png">

As you can see the corners are much bigger than 14px.

So whatever the solution, it should be applied before actually passing the request on to the image loader.

**Comment by ubuntudroid** [comment]
Ah, and I have to correct myself / clarify: this only happens when using `width="100%"`.

**Comment by noties** [comment]
Hello @ubuntudroid ,

I can confirm that this happens. Image loader would be asked to prepare image resource and after that `ImageSizeResolver` would do a final post processing. For example, when `width=100%` then it would scale the image (up or down depending on its original size). Another use-case is when image exceeds available width and will be scaled down to fit. A possible fix is to do resizing inside image loader itself (maybe the only one given the current state of things)
