### ISSUE TITLE
Syntax for Task Lists

### ISSUE THREAD

**Issue by NKnuelle** [noties/Markwon#80]
The readme says there is Task List Support. I tried - [ ] as well as [x] or - [X] but nothing seems to get rendered.

**Comment by noties** [comment]
Hello @NKnuelle !

It's hard to tell. Could you show markdown that you are using and code initialization?

**Comment by NKnuelle** [comment]
Yes of course. I just use a simple EditText to write Markdown and render it via `Markwon.setMarkdown`:

`final EditText editText = (EditText) findViewById(R.id.xmltestview);`
`final Button renderButton = (Button) findViewById(R.id.renderButton);`

        renderButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (renderClicked) {
                    editText.setText(markdown);
                    renderClicked = false;
                    renderButton.setText("Render");
                } else {
                    markdown = editText.getText().toString();
                    Markwon.setMarkdown(editText, markdown);
                    renderClicked = true;
                    renderButton.setText("Plain");
                }
            }
        });

These 2 images show what happens in my view. The checkboxes are not rendered (wrong syntax?):

![app_screenshot01](https://user-images.githubusercontent.com/24235417/48893758-5fa90f00-ee41-11e8-8ffc-45ee69551444.jpg)
![app_screenshot02](https://user-images.githubusercontent.com/24235417/48893759-5fa90f00-ee41-11e8-895e-c1710d9a2f24.jpg)

**Comment by noties** [comment]
<img width="336" alt="screen shot 2018-11-22 at 12 35 56" src="https://user-images.githubusercontent.com/7278986/48894232-40b37880-ee53-11e8-8980-d4efbe49532f.png">

Here is what Github has to say to it. Try adding text after `- [ ]`.
Valid syntax:
* `- [ ] $text`
* `- [x] $text`
* `- [X] $text`

**Comment by NKnuelle** [comment]
Ah well now it works. I just tried to check/uncheck the Checkboxes with touching it but this doesn't seem to work. Neither in a MarkwonView nor in an EditText. Do you know how to achieve that?

**Comment by noties** [comment]
Currently task lists are static. But there a possibility to make them clickable. **Theoretically** you create own `SpannableFactory` that has this method overridden: 

```java
@Nullable
@Override
public Object taskListItem(@NonNull SpannableTheme theme, int blockIndent, boolean isDone) {
    final TaskListSpan span = new TaskListSpan(theme, blockIndent, isDone);
    return new Object[]{
            span,
            new ClickableSpan() {
                @Override
                public void onClick(@NonNull View widget) {
                    span.done(!span.done());
                    widget.postInvalidate();
                }
            }
    };
}
```

Why **theoretically**? Because currently `TaskListSpan` provides no way to mutate `isDone` property (there is no `#done(boolean)` setter). I will change that. But please note that this is merely visual change and it **does not** make changes to underlying text. This is one you should solve by your own means

**Comment by NKnuelle** [comment]
Ah ok. Thank you for this.
You mean that a click will not result in the markdown being changed, right?

**Comment by noties** [comment]
Yep
