### ISSUE TITLE
Bullet points not showing when custom SpannableConfiguration is passed to setMarkDown method

### ISSUE THREAD

**Issue by kannans2** [noties/Markwon#84]
I am new to this library, Sorry if this isn't an issue or it might be a configuration issue!

When I use setMarkDown method with just  a textview and String the bullet point is showing:
`Markwon.setMarkdown(binding.markDownParser, configuration, "* first Bulletin")`
However when I pass a SpannableConfiguration the bullet point stops showing.
`       val latoTypeFace = ResourcesCompat.getFont(context!!, R.font.lato_regular)!!

        val latoTypeFace = ResourcesCompat.getFont(context!!, R.font.lato_regular)!!
        val textSizeMultipliers = floatArrayOf(1.5f, 1.5f, 1.5f, 1f, .5f, .25f)
        var configuration: SpannableConfiguration = SpannableConfiguration.builder(context!!)
                .theme(SpannableTheme.builder()
                        .codeBackgroundColor(ContextCompat.getColor(context!!, R.color.white))
                        .codeTextSize(activity!!.resources.getDimensionPixelSize(R.dimen.font_size_16))
                        .codeTypeface(latoTypeFace)
                        .headingTypeface(latoTypeFace)
                        .headingTextSizeMultipliers(textSizeMultipliers)
                        .build())
                .build()
        binding.markDownParser.setTextColor(ContextCompat.getColor(context!!, R.color.primary))
        Markwon.setMarkdown(binding.markDownParser, configuration, "* first Bulletin")`

Bullet points not showing when custom SpannableConfiguration is passed to setMarkDown method.

Do I have to add anything to the SpannableConfiguration builder to fix this?

**Comment by noties** [comment]
Hello @kannans2 !

You are using `SpannableTheme#builder` method to create an instance of SpannableTheme builder, but this one has no defaults at all (so you should provide everything to it). If instead you would use `SpannableTheme#builderWithDefaults(Context)` factory method, bullet lists (and many more!) should be displayed correctly

**Comment by kannans2** [comment]
Oh!! Really Sorry... My Bad..Didn't notice that!!
It's Working!!

**Comment by S-Bartfast** [comment]
Arr, I had missed this too. In fact I only discovered this solution when I attempted to create an issue for the exact same reason.

Perhaps it would be worth giving a small example in the getting started guide or possibly at the top of the theme section explaining the "builderWithDefaults(...)" method as I for one was not aware of its existence.

**Comment by S-Bartfast** [comment]
The name itself is fine, it's more the very existence of the method that threw me.

Although it's never advisable to chance existing functionality too much I think it would have been more intuitive if the regular 'builder' had included the defaults automatically and a uniquely named building was without them. However, given it has already been implemented the way it has, possibly changing the code in the examples to use "builderWithDefaults(...)" instead will at least tip people off to the methods existence and I'm sure they will then be able to find the regular 'build' method of their own accord should they need it.

**Comment by noties** [comment]
@S-Bartfast I agree with you. It should've been done this way from the start. But given that API is already public ... 🤷‍♂️ 

Anyway, I'm working on closing `3.0.0` version which won't have this issue. First of all by abstracting manual creation of `Theme` and all other components. I'm going to create an issue in this repository inviting everyone to try the new version. So we can polish it before making public.

**Comment by noties** [comment]
I've just created #96 for upcoming release discussion. Feel free to take a look
