### ISSUE TITLE
Paragraph spacing

### ISSUE THREAD

**Issue by tomblenz** [noties/Markwon#85]
I'm custom styling lists using `SpannableFactoryDef.bulletListItem()`.  I'd like to increase the paragraph spacing between each list item.  The docs say I can return multiple spans from `bulletListItem()` but I'm struggling to find a span suitable for this.  The closest I could find was LineHeightSpan, but Google's documentation [leaves something to be desired](https://developer.android.com/reference/android/text/style/LineHeightSpan).

Any ideas?  Apologies if this is the wrong place for this!

**Comment by noties** [comment]
Hello @tomblenz !

Documentation is indeed lacking. But at least we have source code 😄 . So, I navigated to the first implementation for `LineHeightSpan` it's `DrawableMarginSpan` and took a hint:

```java
public class LineHeightSpanImpl implements LineHeightSpan {
    
    private final int height;

    public LineHeightSpanImpl(@Px int height) {
        this.height = height;
    }

    @Override
    public void chooseHeight(CharSequence text, int start, int end, int spanstartv, int v, Paint.FontMetricsInt fm) {
        int need = height - (v + fm.descent - fm.ascent - spanstartv);
        if (need > 0) fm.descent += need;
        need = height - (v + fm.bottom - fm.top - spanstartv);
        if (need > 0) fm.bottom += need;
    }
}
```

This class will help us change line height, then in your `SpannableFactoryDef`:

```java
@Override
public Object bulletListItem(@NonNull SpannableTheme theme, int level) {
    return new Object[]{
            super.bulletListItem(theme, level),
            new LineHeightSpanImpl(getBulletListLineHeight())
    };
}
```

And this will work. Just beware that sometimes it can lead to weird results. For example, if you have  code items:

![device-2018-12-10-125343](https://user-images.githubusercontent.com/7278986/49724575-b05e9b80-fc7a-11e8-8ffa-a4f4b6e6bb8c.png)

We've been discussing this issue recently, but I still have no solution for code spans... so if it's the case then _maybe_ you are better creating own version of the visitor and add new lines manually after each bullet list item and applying `LineHeightSpanImpl` there

**Comment by tomblenz** [comment]
Wow, getting right in there to help! <3 

I must be doing something wrong - the simplest use case of the above isn't producing the expected result for me...

I've got a factory and your LineHeightSpanImpl:
```
class MarkdownSpannableFactory : SpannableFactoryDef() {

    private val listParagraphSpacing = dpToPx(12f).toInt()

    override fun bulletListItem(theme: SpannableTheme, level: Int): Any? {
        return arrayOf(
                super.bulletListItem(theme, level),
                LineHeightSpanImpl(listParagraphSpacing)
        )
    }
}

class LineHeightSpanImpl(val height: Int) : LineHeightSpan {
    override fun chooseHeight(text: CharSequence?, start: Int, end: Int, spanstartv: Int, lineHeight: Int, fm: Paint.FontMetricsInt) {
        var need = height - (lineHeight + fm.descent - fm.ascent - spanstartv)
        if (need > 0) fm.descent += need
        need = height - (lineHeight + fm.bottom - fm.top - spanstartv)
        if (need > 0) fm.bottom += need
    }
}
```

And I'm consuming as follows:
```
override fun onViewCreated(view: View) {

    val config = SpannableConfiguration.builder(context)
            .factory(MarkdownSpannableFactory())
            .build()

    val listContent = "* An escalator can never break: it can only become stairs. You should never see an Escalator Temporarily Out Of Order sign, just Escalator Temporarily Stairs. Sorry for the convenience. \n" +
            "* My fake plants died because I did not pretend to water them.\n" +
            "* I had a stick of CareFree gum, but it didn't work. I felt pretty good while I was blowing that bubble, but as soon as the gum lost its flavor, I was back to pondering my mortality.\n" +
            "* I was at this casino minding my own business, and this guy came up to me and said, 'You're gonna have to move, you're blocking a fire exit.' As though if there was a fire, I wasn't gonna run. If you're flammible and have legs, you are never blocking a fire exit."

    view.debugContent_text.text = Markwon.markdown(config, listContent)
}
```

My TV isn't anything crazy
```
<TextView
        android:id="@+id/debugContent_text"
        android:layout_width="0dp"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        android:background="@color/white"
        android:padding="@dimen/padding16"
        android:layout_margin="@dimen/padding16"
        android:layout_height="wrap_content" />
```

Result is this:
![screenshot_1544470975](https://user-images.githubusercontent.com/3953262/49757234-ce7ed700-fd20-11e8-81b1-ccd47abc24f7.png)

**Comment by noties** [comment]
Hey @tomblenz !

At first I wanted to point out that you were using _spacing_ argument instead of _line height_ when creating `LineHeightSpanImpl`. But then I took your sample input, applied line height and got this result:

![device-2018-12-11-161731](https://user-images.githubusercontent.com/7278986/49804243-20e0e780-fd63-11e8-8eb2-60a7ccf850b4.png)

Clearly we are doing something wrong. So, let's try and fix that. Let's create a new span that will be more obvious:

```java
public class LastLineSpacingSpan implements LineHeightSpan {
    
    private static boolean selfEnd(int end, CharSequence text, Object span) {
        // this is some kind of interesting magic here... only the last
        // span will receive correct _end_ argument, but previous spans
        // receive it tilted by one (1). Most likely it's just a new-line character... and
        // if needed we could check for that
        final int spanEnd = ((Spanned) text).getSpanEnd(span);
        return spanEnd == end || spanEnd == end - 1;
    }

    private final int spacing;

    public LastLineSpacingSpan(@Px int spacing) {
        this.spacing = spacing;
    }

    @Override
    public void chooseHeight(CharSequence text, int start, int end, int spanstartv, int v, Paint.FontMetricsInt fm) {
        if (selfEnd(end, text, this)) {
            // let's just add what we want
            fm.descent += spacing;
            fm.bottom += spacing;
        }
    }
}
```

This part is the same (almost):

```java
@Override
public Object bulletListItem(@NonNull SpannableTheme theme, int level) {
    return new Object[]{
            super.bulletListItem(theme, level),
            new LastLineSpacingSpan(spacing)
    };
}
```

So, with this code and `24dip` as spacing we will get this result:

![device-2018-12-11-163042](https://user-images.githubusercontent.com/7278986/49804395-7e753400-fd63-11e8-8b2f-a81b4bc17c7b.png)

Which I think you were trying to achieve in the first place 🙌

**Comment by tomblenz** [comment]
It completely is!

![screenshot_1544573445](https://user-images.githubusercontent.com/3953262/49838398-5c38f000-fe0f-11e8-87b0-e6f69c591fa6.png)

Thank you, I was expecting to get blown off and thrown at stackoverflow but you've gone above and beyond.  Do you have a donation link or anything :)

**Comment by SMAXLYB** [comment]
how to do in latest version ?
