### ISSUE TITLE
New Extensition: Elegant Cold Extensition

### ISSUE THREAD

**Issue by kingideayou** [noties/Markwon#86]
hello, I just release a library make Markwon support more elegant code block style.
see: [MarkwonCodeEx](https://github.com/kingideayou/MarkwonCodeEx)

**Comment by noties** [comment]
Hey @kingideayou !

Sorry, I must've missed it somehow. I will update README to include your extension (interesting technique to render code spans!)

**Comment by kingideayou** [comment]
Hey @noties 

Thanks a lot. I am honored to be recommended ! 😬
