### ISSUE TITLE
Use in a recyclerview item

### ISSUE THREAD

**Issue by adigunhammedolalekan** [noties/Markwon#90]
Hi, this is a very cool work and I love it. 

Is it safe performance-wise to use in a recyclerview item? 

Thanks!

**Comment by noties** [comment]
Hey @adigunhammedolalekan !

Generally speaking: yes, it is safe. But there is one point that should be considered:

* use `textView#setSpannableFactory` on a TextView that is used in adapter

```java
private static final NoCopySpannableFactory FACTORY = new NoCopySpannableFactory();

@NonNull
@Override
public Holder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {

    final Holder holder = new Holder(inflater.inflate(
            R.layout.adapter_markdown,
            parent,
            false));

    // set SpannableFactory when your view is inflated
    // this will reduce the amount of copying that TextView executes by default
    holder.textView.setSpannableFactory(FACTORY);

    return holder;
}

private static class NoCopySpannableFactory extends Spannable.Factory {
    @Override
    public Spannable newSpannable(CharSequence source) {
        return source instanceof Spannable
                ? (Spannable) source
                : new SpannableString(source);
    }
}
```

Other than that follow the regular steps when working with a RecyclerView and TextView:
* cache as much as possible

  for example, you can parse and create markdown `CharSequence` before sending to an adapter (by calling `Markwon.markdown(configuration, markdown)`.

  if you evaluating markdown lazily (parsing when the first time item is requested), do not forget to cache `SpannableConfiguration` and `Parser` (when not specified explicitly these 2 classes will be created _implicitly_ anyway) and re-use them between calls

* if you are still not happy with performance you can try relatively new thing called `prefetch text` (quick search will get you some results)

**Comment by adigunhammedolalekan** [comment]
Great! Very well explained, Thanks
