### ISSUE TITLE
Bullet lists and ordered lists not render correctly with indentation

### ISSUE THREAD

**Issue by LandChanning** [noties/Markwon#91]
I am new to this library, Sorry if this isn't an issue or it might be a configuration issue!

When I use setMarkdown method like this: 

```
String text = "\n" +
                "- ul1\n" +
                "- ul2\n" +
                "    - ul3\n" +
                "    - ul4\n" +
                "        - ul5\n" +
                "        - ul6\n" +
                "            - ul7\n" +
                "            - ul8\n" +
                "\n" +
                "\n" +
                "1. ol1\n" +
                "1. ol2\n" +
                "    4. ol3\n" +
                "    1. ol4";
Markwon.setMarkdown(textView, text);
```
The result is:
![image](https://user-images.githubusercontent.com/8448947/50622494-8b430d00-0f48-11e9-893b-82b836832a11.png)

I think the correct result is like this:
![image](https://user-images.githubusercontent.com/8448947/50622519-cd6c4e80-0f48-11e9-9d59-02d409f93c6f.png)

Sorry for my poor English.

**Comment by noties** [comment]
Hello @LandChanning !

Given your input:
```
- ul1
- ul2
    - ul3
    - ul4
        - ul5
        - ul6
            - ul7
            - ul8

1. ol1
1. ol2
    4. ol3
    1. ol4
```

I have these results:

<img width="155" alt="screen shot 2019-01-03 at 14 53 51" src="https://user-images.githubusercontent.com/7278986/50636524-7164f280-0f67-11e9-8b2b-6df278f24fb2.png">

Which is the same [here](https://spec.commonmark.org/dingus/?text=-%20ul1%0A-%20ul2%0A%20%20%20%20-%20ul3%0A%20%20%20%20-%20ul4%0A%20%20%20%20%20%20%20%20-%20ul5%0A%20%20%20%20%20%20%20%20-%20ul6%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20ul7%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20ul8%0A%0A1.%20ol1%0A1.%20ol2%0A%20%20%20%204.%20ol3%0A%20%20%20%201.%20ol4%0A%0A).

I have some questions about the bullet list and rendering artifacts:
* What device do you use? 
* What Android version does it have? 
* Does it happen every time? 
* What version of `Markwon` library do you use?
* Have you modified `SpannableFactory` and/or modified BulletListItemSpan (if using at all)

Now, about the ordered list. Honestly I do not know why but nested ordered lists must start with `1.`. I really do not know if it's a bug or a feature, but this behavior is consistent between commonmark tools (the dingus that I had linked before and commonmark-java that `Markwon` is using). If you go to [dingus](https://spec.commonmark.org/dingus/?text=-%20ul1%0A-%20ul2%0A%20%20%20%20-%20ul3%0A%20%20%20%20-%20ul4%0A%20%20%20%20%20%20%20%20-%20ul5%0A%20%20%20%20%20%20%20%20-%20ul6%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20ul7%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20ul8%0A%0A1.%20ol1%0A1.%20ol2%0A%20%20%20%201.%20ol3%0A%20%20%20%201.%20ol4%0A%0A) again and change the nested ordered list start number to `1.` everything will be working:

<img width="92" alt="screen shot 2019-01-03 at 15 00 25" src="https://user-images.githubusercontent.com/7278986/50636731-55ae1c00-0f68-11e9-92fb-aca53657c7fb.png">

Now let's see what's wrong with bullet lists, please answer the questions that I had asked and add (if any) your own observations. Hopefully we will be able to resolve this issue

**Comment by LandChanning** [comment]
Hello @noties 

Thank you for your reply.

About the ordered lists，it works as you say.

About the bullet lists,

- What device do you use?
Xiaomi Redmi Note 4x

- What Android version does it have?
Android 7.0 (MIUI 10)

- Does it happen every time?
Yes

- What version of Markwon library do you use?
2.0.1

- Have you modified SpannableFactory and/or modified BulletListItemSpan (if using at all)?
No

**Comment by noties** [comment]
Hello @LandChanning !

It seems to be a Nougat bug. I did reproduce it (with slightly different visual effect, but still). I think I have found the issue. Please check the `2.0.2-SNAPSHOT` version that I had just published to snapshot repository
