### ISSUE TITLE
Is this possible to add clickable event on tasklist markdown?

### ISSUE THREAD

**Issue by zabi90** [noties/Markwon#95]

**Comment by noties** [comment]
Hello @zabi90 !

It is possible with a custom `SpannableFactory`:

```java
public class MySpannableFactory extends SpannableFactoryDef {
    @Nullable
    @Override
    public Object taskListItem(@NonNull SpannableTheme theme, int blockIndent, boolean isDone) {
        return new Object[]{
                super.taskListItem(theme, blockIndent, isDone),
                new ClickableSpan() {
                    @Override
                    public void onClick(@NonNull View widget) {
                        // here is your click
                    }
                }
        };
    }
}
```

which can be used like this:

```java
final SpannableConfiguration configuration = SpannableConfiguration.builder(context)
        .factory(new MySpannableFactory())
        .build();

Markwon.setMarkdown(textView, configuration, "- [ ] my task list");
```

Please note that `Markwon` doesn't handle the mutation of task lists, so you will have to implement it by yourself. Starting with version `2.0.1` `TaskListSpan` allows _mutation_ of its state by calling: `taskListSpan#setDone(boolean)`, but it doesn't change actual markdown nor _invalidate_ the TextView, so be sure to invalidate it also

**Comment by zabi90** [comment]
@noties Hi, Thanks for your reply. How i can get the value of task list when i click on it? Following code not providing any way to get specific task value.

`public Object taskListItem(@NonNull SpannableTheme theme, int blockIndent, boolean isDone) {
        return new Object[]{
                super.taskListItem(theme, blockIndent, isDone),
                new ClickableSpan() {
                    @Override
                    public void onClick(@NonNull View widget) {
                        // here is your click
                    }
                }
        };
    }`
