### ISSUE TITLE
3.0.0: Beta-testing

### ISSUE THREAD

**Issue by noties** [noties/Markwon#96]
Hello everyone!

Version `3.0.0` is on its way and ready to be **beta-tested**. It has a lot of changes comparing to previous `x.x.x-2.x.x` versions. That's why I want to invite anyone interested to participate in finalizing upcoming release.

[3.0.0 development branch](https://github.com/noties/Markwon/tree/v3.0.0)

Documentation is still not-complete, but it can be a good starting point. Unfortunately I cannot publish new version of documentation yet, so there are few options:

<del>
<details>
<summary>Deploy documentation locally</summary>
One must have <code>npm</code> installed. Checkout into the <code>v3.0.0</code> branch and <code>cd docs</code>. <code>npm install</code> should be enough to get started. Then <code>vuepress dev</code> to serve latest version of documentation.
</details>
<br>

<details>
<summary>Inspect it directly on GitHub</summary>
One can inspect raw documentation markdown files directly on GitHub. It's not as feature-rich as documentation web-site, but still can be used to <em>read the docs</em> &copy;. Head into <code>docs/docs</code> <a href="https://github.com/noties/Markwon/tree/v3.0.0/docs/docs">folder</a>. The most important document is <a href="https://github.com/noties/Markwon/blob/v3.0.0/docs/docs/core/plugins.md">Plugins</a>.
</details>
<br>
</del>

**UPD**: Navigate to main <a href="https://noties.github.io/Markwon/">documentation web site</a> and select `BETA (3.x.x)` option from `API Version` item on top navigation bar.

Latest version `3.0.0` is already published as a snapshot:
```groovy
implementation 'ru.noties.markwon:core:3.0.0-SNAPSHOT'
```

> **Please note** that there are more artifacts now. And `group` attribute is changed to `ru.noties.markwon` (previously `ru.noties` and artifacts like: `markwon`, etc)

Any feedback on documentation itself, upcoming API of `Markwon` library or anything else actually is welcome 🙌

**Comment by noties** [comment]
Deployed Beta documentation to the main [web site](https://noties.github.io/Markwon).
* Hover on `API Version` on top navigation bar
* Select `BETA (3.x.x)`

**Comment by Tunous** [comment]
Hey,

I've went ahead and tested this release in one of my hobby projects and so far it works really good. One thing that I've ran into is an issue with **clickable images**. For some reason images added like the code below no longer load and only link text is displayed. Images that are not wrapped inside of links load correctly.

```md
[![markwon](https://img.shields.io/maven-central/v/ru.noties/markwon.svg?label=markwon)](http://search.maven.org/#search|ga|1|g%3A%22ru.noties%22%20AND%20a%3A%22markwon%22)
```

This is how I configured Markwon:

```kt
Markwon.builder(context)
            .usePlugin(CorePlugin.create())
            .usePlugin(ImagesPlugin.create(context))
            .build()
```

Everything worked correctly in 2.0.1 so I wonder if there is something else that needs to be done now or is this just a bug in 3.0.0?

**Comment by noties** [comment]
Hello @Tunous !

Thank you for the feedback!

Most likely this is due to the fact that SVG image support is moved to a standalone module now. The list of available modules can be found [here](https://noties.github.io/Markwon/docs/v3/install.html). 

So, basically, after you add `image-svg` artifact, you will have to add `usePlugin(SvgPlugin.create(Resources)` to `Markwon` initialization:

```kotlin
Markwon.builder(context)
            .usePlugin(CorePlugin.create())
            .usePlugin(ImagesPlugin.create(context))
            .usePlugin(SvgPlugin.create(context.resources))
            .build()
```

**Comment by Tunous** [comment]
I did it like this to follow the [spec](https://github.github.com/gfm/#ordered-list-marker). I'm not sure if it also applies to task lists but I assumed that it does. 

> The reason for the length limit is that with 10 digits we start seeing integer overflows in some browsers.

**Comment by Tunous** [comment]
Thanks @noties, indeed that was the case. Somehow I've missed that these images are in svg format and took wrong conclusion based on that. After adding SVG plugin everything works correctly.

**Comment by noties** [comment]
Version `3.0.0` released
