### ISSUE TITLE
No line-breaks between last un-ordered list and text

### ISSUE THREAD

**Issue by ujjwalnitw** [noties/Markwon#98]
I am using following text to be rendered as HTML 
"Text before list<ul><li>First list item</li><li>Second list item</li></ul>Text after list item"

Actual result:
<img width="319" alt="screen shot 2019-02-17 at 3 08 45 pm" src="https://user-images.githubusercontent.com/34766920/52911158-1e9c8b80-32c6-11e9-9a53-3ff218ace97a.png">

Expected result :
There should be line break between "Second List item" and "Text after list item".

**Comment by noties** [comment]
Hello @ujjwalnitw !

Markdown has a very specific place for a new line character. In a lot of cases it won't consider it as a delimiter. This allows us to format our markdown to be viewed in a raw fashion (no long one-liners).

For example, I've used [dingus](https://spec.commonmark.org/dingus/?text=Text%20before%20list%0A*%20First%20list%20item%0A*%20Second%20list%20item%0AText%20after%20list%20item%0A) with your input. And it renders the same as in the screenshot that you'd shared.

If you add another new line after your list, then result will be as you'd expect.

**Comment by ujjwalnitw** [comment]
@noties 
The text used was
""Text before list<ul><li>First list item</li><li>Second list item</li></ul>Text after list item""

Dingus example 
https://spec.commonmark.org/dingus/?text=Text%20before%20list%3Cul%3E%3Cli%3EFirst%20list%20item%3C%2Fli%3E%3Cli%3ESecond%20list%20item%3C%2Fli%3E%3C%2Ful%3EText%20after%20list%20item

It works as I expected. Could you please check this?

**Comment by noties** [comment]
You are using HTML here... I'm going to look into why this happens. Meanwhile I want to ask, if there is a specific reason to use HTML when markdown perfectly supports lists?

**Comment by ujjwalnitw** [comment]
@noties This is something that is required by the business to render HTML in-app without using webview.

**Comment by noties** [comment]
Hello @ujjwalnitw !

I've investigated a bit and here is what I had found:
* first of all, you can go _all-html_ here: add `<br>` after your list
* secondly, you can go with another new line character after your list
* finally, you can control how _soft-break_ is treated by the markdown parser, so when it sees it -> you can insert a _hard-line-break_ instead: [refer to the documentation](https://noties.github.io/Markwon/docs/configure.html#soft-line-break)
